<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">

  <!-- Must be included in .vcxproj files to use the SRT library -->

  <!-- Use Robotweax SRT with BCrypt backend if present, with OpenSSL backend otherwise -->
  <PropertyGroup>
    <!-- Define all possible properties files -->
    <LibSrtProps>$(LIBSRT)\libsrt.props</LibSrtProps>
    <BCryptSrtProps>$(ROBOTWEAX_SRT_BCRYPT)\srt.props</BCryptSrtProps>
    <OpenSslSrtProps>$(ROBOTWEAX_SRT_OPENSSL)\srt.props</OpenSslSrtProps>
    <NoSrtProps>$(MSBuildThisFileDirectory)msvc-disable-libsrt.props</NoSrtProps>
    <!-- By default, disable SRT -->
    <SrtProps>$(NoSrtProps)</SrtProps>
    <!-- If original Haivision libsrt exists, override -->
    <SrtProps Condition="Exists('$(LibSrtProps)')">$(LibSrtProps)</SrtProps>
    <!-- If SRT library with OpenSSL backend exists, override -->
    <SrtProps Condition="Exists('$(OpenSslSrtProps)')">$(OpenSslSrtProps)</SrtProps>
    <!-- If SRT library with BCrypt backend exists, override -->
    <SrtProps Condition="Exists('$(BCryptSrtProps)')">$(BCryptSrtProps)</SrtProps>
    <!-- If SRT is disabled anyway, always override -->
    <SrtProps Condition="'$(TS_NO_SRT)' != ''">$(NoSrtProps)</SrtProps>
  </PropertyGroup>

  <ImportGroup>
    <Import Project="$(SrtProps)"/>
  </ImportGroup>

</Project>
