==== Event Information Table (EIT)

Defined by DVB in <<ETSI-300-468>>.
This is the DVB version of an EIT.
ATSC uses a different structure for EIT.

If `type="pf"`, this is an EITp/f (present/following).

If `type` is a 4-bit integer, this is an EITs (schedule) with TID 0x50 + `type` (EITs Actual) or 0x60 + `type` (EITs Other),
depending on the `actual` attribute.

When an EIT is compiled by TSDuck (serialized as binary sections),
the events are sorted in ascending order of start time and spread over sections as described in <<ETSI-101-211>>.

The attribute `last_table_id` is optional.
By default, it is set to the same table id as the table.
Upon serialization, the DVB rules are enforced to bind its value within the DVB-specified limits.

When an EIT section is generated by the plugin `eitinject`, all these fields are automatically computed.

[source,xml]
----
<EIT type="pf|uint4, default=pf"
     version="uint5, default=0"
     current="bool, default=true"
     actual="bool, default=true"
     service_id="uint16, required"
     transport_stream_id="uint16, required"
     original_network_id="uint16, required"
     last_table_id="uint8, default=same as table id">

  <!-- One per event -->
  <event event_id="uint16, required"
         start_time="YYYY-MM-DD hh:mm:ss, required"
         duration="hh:mm:ss, required"
         running_status="undefined|not-running|starting|pausing|running|off-air,
                         default=undefined"
         CA_mode="bool, default=false">
    <DESCRIPTOR_LIST>
  </event>

</EIT>
----
