//----------------------------------------------------------------------------
//
// TSDuck - The MPEG Transport Stream Toolkit
// Copyright (c) 2005-2024, Thierry Lelegard
// BSD-2-Clause license, see LICENSE.txt file or https://tsduck.io/license
//
//----------------------------------------------------------------------------

=== EACEM-defined descriptors (DVB private descriptors)

==== eacem_HD_simulcast_logical_channel_descriptor

Defined by EACEM in <<EACEM-030>>.

Because there are several forms of `HD_simulcast_logical_channel_descriptor`,
this EACEM-defined form is named `<eacem_HD_simulcast_logical_channel_descriptor>`.
For compatibility, the previous XML syntax `<HD_simulcast_logical_channel_descriptor>` is still accepted and is equivalent.

[source,xml]
----
<eacem_HD_simulcast_logical_channel_descriptor>
  <!-- One per service -->
  <service service_id="uint16, required"
           logical_channel_number="uint10, required"
           visible_service="bool, default=true"/>
</eacem_HD_simulcast_logical_channel_descriptor>
----

==== eacem_logical_channel_number_descriptor

Defined by EACEM in <<EACEM-030>>.

Because there are several forms of `logical_channel_number_descriptor`,
this EACEM-defined form is named `<eacem_logical_channel_number_descriptor>`.
For compatibility, the previous XML syntax `<logical_channel_number_descriptor>` is still accepted and is equivalent.

[source,xml]
----
<eacem_logical_channel_number_descriptor>
  <!-- One per service -->
  <service service_id="uint16, required"
           logical_channel_number="uint10, required"
           visible_service="bool, default=true"/>
</eacem_logical_channel_number_descriptor>	
----

==== eacem_preferred_name_identifier_descriptor

Defined by EACEM in <<EACEM-030>>.

[source,xml]
----
<eacem_preferred_name_identifier_descriptor name_id="uint8, required"/>
----

==== eacem_preferred_name_list_descriptor

Defined by EACEM in <<EACEM-030>>.

[source,xml]
----
<eacem_preferred_name_list_descriptor>
  <!-- One per language -->
  <language code="char3, required">
    <!-- One per name -->
    <name name_id="uint8, required" name="string, required"/>
  </language>
</eacem_preferred_name_list_descriptor>
----

==== eacem_stream_identifier_descriptor

Defined by EACEM in <<EACEM-030>>.

[source,xml]
----
<eacem_stream_identifier_descriptor version_byte="uint8, required"/>
----
