//----------------------------------------------------------------------------
//
// TSDuck - The MPEG Transport Stream Toolkit
// Copyright (c) 2005-2024, Thierry Lelegard
// BSD-2-Clause license, see LICENSE.txt file or https://tsduck.io/license
//
//----------------------------------------------------------------------------

=== ISDB-defined descriptors

==== area_broadcasting_information_descriptor

Defined by ARIB in <<ARIB-B10J>>.

[source,xml]
----
<area_broadcasting_information_descriptor>

  <!-- One per station -->
  <station
      station_id="uint24, required"
      location_code="uint16, required"
      broadcast_signal_format="uint8, required">

    <additional_station_info>
      Hexadecimal content
    </additional_station_info>

  </station>

</area_broadcasting_information_descriptor>
----

==== audio_component_descriptor

Defined by ARIB in <<ARIB-B10J>>.

[source,xml]
----
<audio_component_descriptor
    stream_content="uint4, default=2"
    component_type="uint8, required"
    component_tag="uint8, required"
    stream_type="uint8, required"
    simulcast_group_tag="uint8, default=0xFF"
    main_component="bool, default=true"
    quality_indicator="uint2, required"
    sampling_rate="uint3, required"
    ISO_639_language_code="char3, required"
    ISO_639_language_code_2="char3, optional"
    text="string, optional"/>
----

==== basic_local_event_descriptor

Defined by ARIB in <<ARIB-B10J>>.

[source,xml]
----
<basic_local_event_descriptor
    segmentation_mode="uint4, required"
    start_time_NPT="uint33, optional"
    end_time_NPT="uint33, optional"
    start_time="hh:mm:ss, optional"
    duration="hh:mm:ss, optional"
    start_time_extension="mmm, optional"
    duration_extension="mmm, optional">

  <reserved_data>
    Hexadecimal content
  </reserved_data>

  <!-- One per component tag -->
  <component tag="uint8, required"/>

</basic_local_event_descriptor>
----

==== board_information_descriptor

Defined by ARIB in <<ARIB-B10J>>.

[source,xml]
----
<board_information_descriptor
    title="string, required"
    text="string, required"/>
----

==== broadcaster_name_descriptor

Defined by ARIB in <<ARIB-B10J>>.

[source,xml]
----
<broadcaster_name_descriptor name="string, required"/>
----

==== CA_contract_info_descriptor

Defined by ARIB in <<ARIB-B25>>.

[source,xml]
----
<CA_contract_info_descriptor
    CA_system_id="uint16, required"
    CA_unit_id="uint4, required"
    fee_name="string, optional">

  <!-- One per component -->
  <component tag="uint8, required"/>

  <contract_verification_info>
    Hexadecimal content
  </contract_verification_info>

</CA_contract_info_descriptor>
----

==== CA_EMM_TS_descriptor

Defined by ARIB in <<ARIB-B25>>.

[source,xml]
----
<CA_EMM_TS_descriptor
    CA_system_id="uint16, required"
    transport_stream_id="uint16, required"
    original_network_id="uint16, required"
    power_supply_period="uint8, required"/>
----

==== CA_service_descriptor

Defined by ARIB in <<ARIB-B25>>.

[source,xml]
----
<CA_service_descriptor
    CA_system_id="uint16, required"
    ca_broadcaster_group_id="uint8, required"
    message_control="uint8, required">

  <!-- One per service -->
  <service id="uint16, required"/>

</CA_service_descriptor>
----

==== carousel_compatible_composite_descriptor

Defined by ARIB in <<ARIB-B10>>.

[source,xml]
----
<carousel_compatible_composite_descriptor>

  <!-- Any number of subdescriptors -->
  <subdescriptor type="uint8, required">
    Hexadecimal content
  </subdescriptor>

</carousel_compatible_composite_descriptor>
----

==== conditional_playback_descriptor

Defined by ARIB in <<ARIB-B25>>.

[source,xml]
----
<conditional_playback_descriptor
    CA_system_id="uint16, required"
    CA_PID="uint13, required">

  <private_data>
    Hexadecimal content
  </private_data>

</conditional_playback_descriptor>
----

==== content_availability_descriptor

Defined by ARIB in <<ARIB-B10J>>.

[source,xml]
----
<content_availability_descriptor
    copy_restriction_mode="bool, required"
    image_constraint_token="bool, required"
    retention_mode="bool, required"
    retention_state="uint3, required"
    encryption_mode="bool, required">

  <reserved_future_use>
    Hexadecimal content
  </reserved_future_use>

</content_availability_descriptor>
----

==== data_component_descriptor

Defined by ARIB in <<ARIB-B10J>>.

[source,xml]
----
<data_component_descriptor data_component_id="uint16, required">
  <additional_data_component_info>
    Hexadecimal content
  </additional_data_component_info>
</data_component_descriptor>
----

==== data_content_descriptor

Defined by ARIB in <<ARIB-B10J>>.

[source,xml]
----
<data_content_descriptor
    data_component_id="uint16, required"
    entry_component="uint8, required"
    ISO_639_language_code="char3, required"
    text="string, required">

  <selector_bytes>
    Hexadecimal content
  </selector_bytes>

  <!-- One per component_ref -->
  <component ref="uint8, required"/>

</data_content_descriptor>
----

==== digital_copy_control_descriptor

Defined by ARIB in <<ARIB-B10J>>.

[source,xml]
----
<digital_copy_control_descriptor
    digital_recording_control_data="uint2, required"
    user_defined="uint4, default=0"
    maximum_bitrate="uint8, optional">

  <!-- One per component in the service -->
  <component_control
      component_tag="uint8, required"
      digital_recording_control_data="uint2, required"
      user_defined="uint4, default=0"
      maximum_bitrate="uint8, optional"/>

</digital_copy_control_descriptor>
----

Note: as specified in <<ARIB-B10J>>, the `maximum_bitrate` attribute is set in units of 1/4 Mb/s (250 kb/s).

==== download_content_descriptor

Defined by ARIB in <<ARIB-B21>>.

[source,xml]
----
<download_content_descriptor
    reboot="bool, required"
    add_on="bool, required"
    component_size="uint32, required"
    download_id="uint32, required"
    time_out_value_DII="uint32, required"
    leak_rate="uint22, required"
    component_tag="uint8, required">

  <!-- At most one compatibility_descriptor -->
  <compatibility_descriptor>

    <!-- Any number of descriptors -->
    <descriptor
        descriptor_type="uint8, required"
        specifier_type="uint8, required"
        specifier_data="uint24, required"
        model="uint16, required"
        version="uint16, required">

      <!-- Any number of subdescriptors -->
      <subdescriptor type="uint8, required">
        Hexadecimal content
      </subdescriptor>
    </descriptor>

  </compatibility_descriptor>

  <!-- One per module -->
  <module module_id="uint16, required" module_size="uint32, required">
    <module_info>
      Hexadecimal content
    </module_info>
  </module>

  <!-- At most one -->
  <private_data>
    Hexadecimal content
  </private_data>

  <!-- At most one -->
  <text_info ISO_639_language_code="char3, required" text="string, required"/>

</download_content_descriptor>
----

==== emergency_information_descriptor

Defined by ARIB in <<ARIB-B10J>>.

[source,xml]
----
<emergency_information_descriptor>

  <!-- One entry per event -->
  <event service_id="uint16, required"
         started="bool, required"
         signal_level="uint1, required">

    <!-- One entry per area code -->
    <area code="uint12, required"/>

  </event>

</emergency_information_descriptor>
----

==== event_group_descriptor

Defined by ARIB in <<ARIB-B10J>>.

[source,xml]
----
<event_group_descriptor group_type="uint4, required">

  <!-- One per event in actual network -->
  <actual service_id="uint16, required"
          event_id="uint16, required"/>

  <!-- One per event in other networks (group_type == 4 or 5) -->
  <other original_network_id="uint16, required"
         transport_stream_id="uint16, required"
         service_id="uint16, required"
         event_id="uint16, required"/>

  <!-- Optional private data for other group types -->
  <private_data>
    Hexadecimal content
  </private_data>

</event_group_descriptor>
----

==== extended_broadcaster_descriptor

Defined by ARIB in <<ARIB-B10J>>.

[source,xml]
----
<extended_broadcaster_descriptor
    broadcaster_type="uint4, required"
    terrestrial_broadcaster_id="uint16, optional">

  <!-- Any number of affiliations, when broadcaster_type == 0x01 or 0x2 -->
  <affiliation id="uint8, required"/>

  <!-- Any number of broadcasters, when broadcaster_type == 0x01 or 0x2 -->
  <broadcaster original_network_id="uint16, required" broadcaster_id="uint8, required"/>

  <private_data>
    Hexadecimal content
  </private_data>

</extended_broadcaster_descriptor>
----

Note: While the fields have different names in <<ARIB-B10J>>,
the structure of the descriptor is identical for `broadcaster_type` values 0x01 and 0x02.
In the XML, the attributes are unified.
For instance, the attribute `terrestrial_broadcaster_id` is in fact `terrestrial_sound_broadcaster_id`
when `broadcaster_type` is 0x02.

==== hierarchical_transmission_descriptor

Defined by ARIB in <<ARIB-B10J>>.

[source,xml]
----
<hierarchical_transmission_descriptor
    high_quality="bool, required"
    reference_PID="uint13, required"/>
----

==== ISDB_access_control_descriptor

Defined by ARIB in <<ARIB-B10J>>.

[source,xml]
----
<ISDB_access_control_descriptor
    CA_system_id="uint16, required"
    transmission_type="uint3, default=7"
    PID="uint13, required">

  <private_data>
    Hexadecimal content
  </private_data>

</ISDB_access_control_descriptor>
----

==== ISDB_component_group_descriptor

Defined by ARIB in <<ARIB-B10J>>.

[source,xml]
----
<ISDB_component_group_descriptor
   component_group_type="uint3, required">

  <component_group
    component_group_id="uint4, required"
    total_bit_rate="uint8, optional"
    explanation="string, optional">

    <CAUnit
       CA_unit_id="uint4, required">

      <component_tags>
        Up to 16 8-bit component tags
      </component_tags>

    </CAUnit>
  </component_group>

</ISDB_component_group_descriptor>
----

==== ISDB_connected_transmission_descriptor

Defined by ARIB in <<ARIB-B10J>>.

[source,xml]
----
<ISDB_connected_transmission_descriptor
   connected_transmission_group_id="uint16, required"
   segment_type="uint2, required"
   modulation_type_A="uint2, required"
   modulation_type_B="uint2, required"
   modulation_type_C="uint2, required">

   <addtional_connected_transmission_info>
     Hexadecimal data
   </addtional_connected_transmission_info>

</ISDB_connected_transmission_descriptor>
----

==== ISDB_hyperlink_descriptor

Defined by ARIB in <<ARIB-B10J>>.

[source,xml]
----
<ISDB_hyperlink_descriptor
    hyper_linkage_type="uint8, required"
    link_destination_type="uint8, required">

  <!-- link_destination_type = 0x01 -->
  <Service
    original_network_id="uint16, required"
    transport_stream_id="uint16, required"
    service_id="uint16, required"/>

  <!-- link_destination_type = 0x02 -->s
  <Event
    original_network_id="uint16, required"
    transport_stream_id="uint16, required"
    service_id="uint16, required"
    event_id="uint16, required"/>

  <!-- link_destination_type = 0x03 -->
  <Module
    original_network_id="uint16, required"
    transport_stream_id="uint16, required"
    service_id="uint16, required"
    event_id="uint16, required"
    component_tag="uint8, required"
    module_id="uint16, required"/>

  <!-- link_destination_type = 0x04 -->
  <Content
    original_network_id="uint16, required"
    transport_stream_id="uint16, required"
    service_id="uint16, required"
    content_id="uint16, required"/>

  <!-- link_destination_type = 0x05 -->
  <ContentModule
    original_network_id="uint16, required"
    transport_stream_id="uint16, required"
    service_id="uint16, required"
    content_id="uint16, required"
    component_tag="uint8, required"
    module_id="uint16, required"/>

  <!-- link_destination_type = 0x06 -->
  <ERTNode
    information_provider_id="uint16, required"
    event_relation_id="uint16, required"
    node_id="uint16, required"/>

  <!-- link_destination_type = 0x07 -->
  <StoredContent uri="string, required"/>

  <private_data>
      Hexadecimal encoded private data
  </private_data>

</ISDB_hyperlink_descriptor>
----

==== ISDB_LDT_linkage_descriptor

Defined by ARIB in <<ARIB-B10J>>.

[source,xml]
----
<ISDB_LDT_linkage_descriptor
   original_service_id="uint16, required"
   transport_stream_id="uint16, required"
   original_network_id="uint16, required">

  <Description
    id="uint16, required"
    type="uint4, required"
    user_defined="uint8, required"/>

</ISDB_LDT_linkage_descriptor>
----

==== ISDB_network_identifier_descriptor

Defined by ARIB in <<ARIB-B10J>>.

[source,xml]
----
<ISDB_network_identifier_descriptor
    country_code="char3, required"
    media_type="AB|AC|BS|CB|TB, required"
    network_id="uint16, required">

  <private_data>
    Hexadecimal content
  </private_data>

</ISDB_network_identifier_descriptor>
----

==== ISDB_target_region_descriptor

Defined by ARIB in <<ARIB-B10J>>.

[source,xml]
----
<ISDB_target_region_descriptor
    region_spec_type="uint8, required"
    regions_mask="string, optional"/>
----

==== ISDB_terrestrial_delivery_system_descriptor

Defined by ARIB in <<ARIB-B10J>>.

[source,xml]
----
<ISDB_terrestrial_delivery_system_descriptor
    area_code="uint12, required"
    guard_interval="1/32|1/16|1/8|1/4, required"
    transmission_mode="2k|4k|8k|mode1|mode2|mode3, required">

  <!-- More than one frequency in case of MFN -->
  <frequency value="FrequencyHz, required"/>

</ISDB_terrestrial_delivery_system_descriptor>
----

==== logo_transmission_descriptor

Defined by ARIB in <<ARIB-B10J>>.

[source,xml]
----
<logo_transmission_descriptor
    logo_transmission_type="uint8, required"
    logo_id="uint9, optional"
    logo_version="uint12, optional"
    download_data_id="uint16, optional"
    logo_char="string, optional">

  <reserved_future_use>
    Hexadecimal content
  </reserved_future_use>

</logo_transmission_descriptor>
----

Note: the presence of the various attributes depends on the value of `logo_transmission_type` (see <<ARIB-B10J>>).

==== network_download_content_descriptor

Defined by ARIB in <<ARIB-B21>>.

[source,xml]
----
<network_download_content_descriptor
    reboot="bool, required"
    add_on="bool, required"
    component_size="uint32, required"
    session_protocol_number="uint8, required"
    session_id="uint32, required"
    retry="uint8, required"
    connect_timer="uint24, required">

  <!-- Exactly one of ipv4, ipv6, url -->
  <ipv4 address="IPv4 address, required" port="uint16, required"/>
  <ipv6 address="IPv6 address, required" port="uint16, required"/>
  <url url="string, required"/>

  <!-- At most one compatibility_descriptor -->
  <compatibility_descriptor>

    <!-- Any number of descriptors -->
    <descriptor
        descriptor_type="uint8, required"
        specifier_type="uint8, required"
        specifier_data="uint24, required"
        model="uint16, required"
        version="uint16, required">

      <!-- Any number of subdescriptors -->
      <subdescriptor type="uint8, required">
        Hexadecimal content
      </subdescriptor>
    </descriptor>

  </compatibility_descriptor>

  <!-- At most one -->
  <private_data>
    Hexadecimal content
  </private_data>

  <!-- At most one -->
  <text_info ISO_639_language_code="char3, required" text="string, required"/>

</network_download_content_descriptor>
----

==== node_relation_descriptor

Defined by ARIB in <<ARIB-B10J>>.

[source,xml]
----
<node_relation_descriptor
    reference_type="uint4, default=0"
    information_provider_id="uint16, optional"
    event_relation_id="uint16, optional"
    reference_node_id="uint16, required"
    reference_number="uint8, required"/>
----

==== partial_reception_descriptor

Defined by ARIB in <<ARIB-B10J>>.

[source,xml]
----
<partial_reception_descriptor>
  <service id="uint16, required"/>
</partial_reception_descriptor>
----

==== partialTS_time_descriptor

Defined by ARIB in <<ARIB-B21>>.

[source,xml]
----
<partialTS_time_descriptor
    event_version_number="uint8, required"
    event_start_time="YYYY-MM-DD hh:mm:ss, optional"
    duration="hh:mm:ss, optional"
    offset="hh:mm:ss, optional"
    offset_flag="uint1, default=0"
    other_descriptor_status="bool, default=false"
    JST_time="YYYY-MM-DD hh:mm:ss, optional"/>
----

==== reference_descriptor

Defined by ARIB in <<ARIB-B10J>>.

[source,xml]
----
<reference_descriptor
    information_provider_id="uint16, required"
    event_relation_id="uint16, required">

  <!-- One per reference -->
  <reference
      reference_node_id="uint16, required"
      reference_number="uint8, required"
      last_reference_number="uint8, required"/>

</reference_descriptor>
----

==== satellite_delivery_system_descriptor

Defined by DVB in <<ETSI-300-468>>.

Redefined in a slightly different way by ARIB in <<ARIB-B10J>>.
See xref:sat-del-desc[xrefstyle=short].

==== series_descriptor

Defined by ARIB in <<ARIB-B10J>>.

[source,xml]
----
<series_descriptor
    series_id="uint16, required"
    repeat_label="uint4, required"
    program_pattern="uint3, required"
    expire_date="YYYY-MM-DD, optional"
    episode_number="uint12, required"
    last_episode_number="uint12, required"
    series_name="string, optional"/>
----

==== service_group_descriptor

Defined by ARIB in <<ARIB-B10J>>.

[source,xml]
----
<service_group_descriptor service_group_type="uint4, required">

  <!-- One per service when service_group_type == 1 -->
  <service primary_service_id="uint16, required"
           secondary_service_id="uint16, required"/>

  <!-- Optional private data for other group types -->
  <private_data>
    Hexadecimal content
  </private_data>

</service_group_descriptor>
----

==== short_node_information_descriptor

Defined by ARIB in <<ARIB-B10J>>.

[source,xml]
----
<short_node_information_descriptor
    ISO_639_language_code="char3, required"
    node_name="string, optional"
    text="string, optional"/>
----

==== SI_parameter_descriptor

Defined by ARIB in <<ARIB-B10J>>.

[source,xml]
----
<SI_parameter_descriptor
    parameter_version="uint8, required"
    update_time="YYYY-MM-DD, required">

  <!-- One per SI table -->
  <table id="uint8, required">
    Hexadecimal content (table description bytes)
  </table>

</SI_parameter_descriptor>
----

==== SI_prime_TS_descriptor

Defined by ARIB in <<ARIB-B10J>>.

[source,xml]
----
<SI_prime_TS_descriptor
    parameter_version="uint8, required"
    update_time="YYYY-MM-DD, required"
    SI_prime_TS_network_id="uint16, required"
    SI_prime_transport_stream_id="uint16, required">

  <!-- One per SI table -->
  <table id="uint8, required">
    Hexadecimal content (table description bytes)
  </table>

</SI_prime_TS_descriptor>
----

==== STC_reference_descriptor

Defined by ARIB in <<ARIB-B10J>>.

[source,xml]
----
<STC_reference_descriptor
    STC_reference_mode="uint4, required"
    external_event_id="uint16, optional"
    external_service_id="uint16, optional"
    external_network_id="uint16, optional"
    NPT_reference="uint33, optional"
    STC_reference="uint33, optional"
    time_reference="hh:mm:ss, optional"
    time_reference_extension="mmm, optional">

  <reserved_data>
    Hexadecimal content
  </reserved_data>

</STC_reference_descriptor>
----

==== system_management_descriptor

Defined by ARIB in <<ARIB-B10J>>.

[source,xml]
----
<system_management_descriptor
    broadcasting_flag="uint2, required"
    broadcasting_identifier="uint6, required"
    additional_broadcasting_identification="uint8, required">

  <additional_identification_info>
    Hexadecimal content
  </additional_identification_info>

</system_management_descriptor>
----

==== TS_information_descriptor

Defined by ARIB in <<ARIB-B10J>>.

[source,xml]
----
<TS_information_descriptor
    remote_control_key_id="uint8, required"
    ts_name="string, required">

  <!-- Up to 3 transmission types -->
  <transmission_type transmission_type_info="uint8, required">
    <service id="uint16, required"/>
  </transmission_type>

  <reserved_future_use>
    Hexadecimal content
  </reserved_future_use>

</TS_information_descriptor>
----

==== video_decode_control_descriptor

Defined by ARIB in <<ARIB-B10J>>.

[source,xml]
----
<video_decode_control_descriptor
    still_picture="bool, required"
    sequence_end_code="bool, required"
    video_encode_format="uint4, required"
    reserved_future_use="uint2, default=3"/>
----
