//----------------------------------------------------------------------------
//
// TSDuck - The MPEG Transport Stream Toolkit
// Copyright (c) 2005-2024, Thierry Lelegard
// BSD-2-Clause license, see LICENSE.txt file or https://tsduck.io/license
//
//----------------------------------------------------------------------------

=== ISDB-defined tables

==== Broadcaster Information Table (BIT)

Defined by ARIB in <<ARIB-B10>>.

[source,xml]
----
<BIT version="uint5, default=0"
     current="bool, default=true"
     original_network_id="uint16, required"
     broadcast_view_propriety="bool, required">

  <!-- Common descriptors loop -->
  <DESCRIPTOR_LIST>

  <!-- One per broadcaster -->
  <broadcaster broadcaster_id="uint8, required">
    <DESCRIPTOR_LIST>
  </broadcaster>

</BIT>
----

==== Common Data Table (CDT)

Defined by ARIB in <<ARIB-B21>>.

[source,xml]
----
<CDT version="uint5, default=0"
     current="bool, default=true"
     download_data_id="uint16, required"
     original_network_id="uint16, required"
     data_type="uint8, required">

  <!-- Common descriptors loop -->
  <DESCRIPTOR_LIST>

  <data_module>
    Hexadecimal content
  </data_module>

</CDT>
----

==== Event Relation Table (ERT)

Defined by ARIB in <<ARIB-B10>>.

[source,xml]
----
<ERT version="uint5, default=0"
     current="bool, default=true"
     event_relation_id="uint16, required"
     information_provider_id="uint16, required"
     relation_type="uint4, required">

  <!-- One per event relation -->
  <relation
      node_id="uint16, required"
      collection_mode="uint4, required"
      parent_node_id="uint16, required"
      reference_number="uint8, required">
    <DESCRIPTOR_LIST>
  </relation>

</ERT>
----

==== Index Transmission information Table (ITT)

Defined by ARIB in <<ARIB-B10>>.

[source,xml]
----
<ITT version="uint5, default=0"
     current="bool, default=true"
     event_id="uint16, required">

  <DESCRIPTOR_LIST>

</ITT>
----

==== Linked Description Table (LDT)

Defined by ARIB in <<ARIB-B10>>.

[source,xml]
----
<LDT version="uint5, default=0"
     current="bool, default=true"
     original_service_id="uint16, required"
     transport_stream_id="uint16, required"
     original_network_id="uint16, required">

  <!-- One per description -->
  <description description_id="uint16, required">
    <DESCRIPTOR_LIST>
  </description>

</LDT>
----

==== Local event Information Table (LIT)

Defined by ARIB in <<ARIB-B10>>.

[source,xml]
----
<LIT version="uint5, default=0"
     current="bool, default=true"
     event_id="uint16, required"
     service_id="uint16, required"
     transport_stream_id="uint16, required"
     original_network_id="uint16, required">

  <!-- One per local event -->
  <event local_event_id="uint16, required">
    <DESCRIPTOR_LIST>
  </event>

</LIT>
----

==== Network Board Information Table (NBIT)

Defined by ARIB in <<ARIB-B10>>.

[source,xml]
----
<NBIT version="uint5, default=0"
      current="bool, default=true"
      original_network_id="uint16, required"
      body="bool, default=true">

  <!-- One per information set -->
  <information
      information_id="uint16, required"
      information_type="uint4, required"
      description_body_location="uint2, required"
      user_defined="uint8, default=0xFF">

    <!-- One per key_id entry -->
    <key id="uint16, required"/>
    <DESCRIPTOR_LIST>

  </information>

</NBIT>
----

The attribute `body` indicates if the NBIT carries actual information body (table id 0xC5 when true)
or reference to information (table id 0xC6 when false).

==== Partial Content Announcement Table (PCAT)

Defined by ARIB in <<ARIB-B10>>.

[source,xml]
----
<PCAT version="uint5, default=0"
      current="bool, default=true"
      service_id="uint16, required"
      transport_stream_id="uint16, required"
      original_network_id="uint16, required"
      content_id="uint32, required">

  <!-- One per content version -->
  <version content_version="uint16, required"
           content_minor_version="uint16, required"
           version_indicator="uint2, required">

    <!-- One per schedule entry -->
    <schedule start_time="YYYY-MM-DD hh:mm:ss, required"
              duration="hh:mm:ss, required"/>

    <DESCRIPTOR_LIST>

  </version>

</PCAT>
----

==== Software Download Trigger Table (SDTT)

Defined by ARIB in <<ARIB-B21>>.

[source,xml]
----
<SDTT version="uint5, default=0"
      current="bool, default=true"
      table_id_ext="uint16, required"
      transport_stream_id="uint16, required"
      original_network_id="uint16, required"
      service_id="uint16, required">

  <!-- One per download content -->
  <content
      group="uint4, required"
      target_version="uint12, required"
      new_version="uint12, required"
      download_level="uint2, required"
      version_indicator="uint2, required"
      schedule_timeshift_information="uint4, required">

    <!-- One per schedule period -->
    <schedule
        start_time="YYYY-MM-DD hh:mm:ss, required"
        duration="hh:mm:ss, required"/>

    <DESCRIPTOR_LIST>

  </content>

</SDTT>
----
