//----------------------------------------------------------------------------
//
// TSDuck - The MPEG Transport Stream Toolkit
// Copyright (c) 2005-2024, Thierry Lelegard
// BSD-2-Clause license, see LICENSE.txt file or https://tsduck.io/license
//
//----------------------------------------------------------------------------

=== SCTE-defined descriptors

==== cue_identifier_descriptor

Defined by ANSI/SCTE in <<SCTE-35>>.

[source,xml]
----
<cue_identifier_descriptor
     cue_stream_type="insert_null_schedule|all|segmentation|tiered_splicing|
                      tiered_segmentation|uint8, required">	
  <!-- Defined by SCTE 35 for use in PMT -->
</cue_identifier_descriptor>
----

==== EAS_audio_file_descriptor

Defined by ANSI/SCTE in <<SCTE-18>>.
Must be in a Cable Emergency Alert Table (table id 0xD8).

[source,xml]
----
<EAS_audio_file_descriptor>
  <!-- One entry per audio file -->
  <file audio_format="uint7, required"
        file_name="string, optional"
        audio_source="uint8, required"
        program_number="uint16, optional"
        carousel_id="uint32, optional"
        application_id="uint16, optional"
        download_id="uint32, optional"
        module_id="uint32, optional"/>
</EAS_audio_file_descriptor>
----

==== EAS_inband_details_channel_descriptor

Defined by ANSI/SCTE in <<SCTE-18>>.
Must be in a Cable Emergency Alert Table (table id 0xD8).

[source,xml]
----
<EAS_inband_details_channel_descriptor
    details_RF_channel="uint8, required"
    details_program_number="uint16, required"/>
----

==== EAS_inband_exception_channels_descriptor

Defined by ANSI/SCTE in <<SCTE-18>>.
Must be in a Cable Emergency Alert Table (table id 0xD8).

[source,xml]
----
<EAS_inband_exception_channels_descriptor>
  <!-- One entry per exception channel -->
  <exception RF_channel="uint8, required" program_number="uint16, required"/>
</EAS_inband_exception_channels_descriptor>
----

==== EAS_metadata_descriptor

Defined by ANSI/SCTE in <<SCTE-164>>.
Must be in a Cable Emergency Alert Table (table id 0xD8).

[source,xml]
----
<EAS_metadata_descriptor fragment_number="uint8, default=1">
  <!-- The text inside this element is an XML fragment -->
</EAS_metadata_descriptor>
----

==== splice_avail_descriptor

Defined by ANSI/SCTE in <<SCTE-35>>. Must be in a Splice Information Table (table id 0xFC).

[source,xml]
----
<splice_avail_descriptor
    identifier="uint32, default=0x43554549"
    provider_avail_id="uint32, required"/>
----

==== splice_DTMF_descriptor

Defined by ANSI/SCTE in <<SCTE-35>>. Must be in a Splice Information Table (table id 0xFC).

[source,xml]
----
<splice_DTMF_descriptor
    identifier="uint32, default=0x43554549"
    preroll="uint8, required"
    DTMF="string, required"/>
----

==== splice_segmentation_descriptor

Defined by ANSI/SCTE in <<SCTE-35>>.
Must be in a Splice Information Table (table id 0xFC).

[source,xml]
----
<splice_segmentation_descriptor
    identifier="uint32, default=0x43554549"
    segmentation_event_id="uint32, required"
    segmentation_event_cancel="bool, default=false"
    web_delivery_allowed="bool, default=true"
    no_regional_blackout="bool, default=true"
    archive_allowed="bool, default=true"
    device_restrictions="uint2, default=3"
    segmentation_duration="uint40, optional"
    segmentation_type_id="uint8, required"
    segment_num="uint8, required"
    segments_expected="uint8, required"
    sub_segment_num="uint8, required when segmentation_type_id == 0x34 or 0x36"
    sub_segments_expected="uint8, required when segmentation_type_id == 0x34 or 0x36">

  <segmentation_upid type="uint8, required">
    Hexadecimal content
  </segmentation_upid>

  <!-- One per component when program_segmentation_flag is to be set to 0 -->
  <component component_tag="uint8, required" pts_offset="uint33, required"/>

</splice_segmentation_descriptor>
----

==== splice_time_descriptor

Defined by ANSI/SCTE in <<SCTE-35>>.
Must be in a Splice Information Table (table id 0xFC).

[source,xml]
----
<splice_time_descriptor
    identifier="uint32, default=0x43554549"
    TAI_seconds="uint48, required"
    TAI_ns="uint32, required"
    UTC_offset="uint16, required"/>
----
