//----------------------------------------------------------------------------
//
// TSDuck - The MPEG Transport Stream Toolkit
// Copyright (c) 2005-2026, Thierry Lelegard
// BSD-2-Clause license, see LICENSE.txt file or https://tsduck.io/license
//
//----------------------------------------------------------------------------

[#chap-preface]
[preface]
== Preface

TSDuck is a free and open-source toolkit to manipulate MPEG Transport Streams.
It contains a set of simple but flexible command-line utilities that run on Linux, Windows, macOS and BSD systems.
These commands are designed for scripting and automation in lab or production environments.

Through `tsp`, the _transport stream processor_, many types of analysis and
transformation can be applied on live or recorded transport streams.
This utility can be extended through _plugins_.
Existing plugins can be enhanced, and new plugins can be developed using a library of {cpp} classes.

This document is the user guide for TSDuck.
It explains the basic concepts of TSDuck and contains reference sections for all commands and plugins.

Structure of this guide:

* The xref:chap-overview[xrefstyle=short] provides an overview of TSDuck and
  how to install it on the various operating systems.
* The xref:chap-data[xrefstyle=short] describes the data formats
  (transport stream, binary sections files, character sets, XML and JSON files).
* The xref:chap-security[xrefstyle=short] provides some information on how TSDuck addresses cybersecurity.
* The xref:chap-commands[xrefstyle=short] describes all TSDuck commands.
* The xref:chap-plugins[xrefstyle=short] describes all `tsp` plugins.
* The xref:chap-examples[xrefstyle=short] provides some concrete examples of TSDuck usage.
* The xref:chap-troubleshooting[xrefstyle=short] provides some troubleshooting guidelines
  when encountering problems when using TSDuck.
* The xref:chap-hardware[xrefstyle=short] describes the level of test and support for some hardware devices,
  mainly DVB receivers and Dektec, HiDes or AstroMeta (formerly VATek) devices.

The world of Digital Television is built on top of a set of robust standards from various bodies.
Understanding these standards and how they interact is essential to use TSDuck.
The relationships between these standards are explained in xref:compat-standards[xrefstyle=short].

A bibliography of the main standard documents, as well as other useful links,
is provided in the xref:bibliography[xrefstyle=short] at the very end of this guide.
Each time it is necessary to refer to a standard document, a link similar to this one is present: <<ISO-13818-1>>.
Just follow the link to have the complete description of the document in the bibliography.

Like any technical field, Digital Television uses a lot of acronyms.
A list of them is provided in xref:acronyms[xrefstyle=short].

include::{includedir}/common-intro.adoc[]
