//----------------------------------------------------------------------------
//
// TSDuck - The MPEG Transport Stream Toolkit
// Copyright (c) 2005-2024, Thierry Lelegard
// BSD-2-Clause license, see LICENSE.txt file or https://tsduck.io/license
//
//----------------------------------------------------------------------------

[#chap-sixmlref]
[appendix]
== PSI/SI XML Reference Model

This appendix describes the XML reference format for all tables and descriptors.

=== PSI/SI file format

The format which is used here is informal.
See xref:xml-models[xrefstyle=short] about XML model files.

Additionally:

* Hexadecimal content is a suite of hexadecimal digits.
  Spaces are ignored.
  Note that the name _hexadecimal content_ is used for data blocks, usually private ones, of arbitrary length.
  This is different from integer values in attributes which can be represented as hexadecimal using the prefix `0x`.
  In _hexadecimal content_ blocks, there is no `0x` prefix, everything is hexadecimal.
* The pseudo-node `<DESCRIPTOR_LIST>` is a place-holder for a sequence a descriptor nodes.
* Unsupported tables and descriptors can still be used.
  Their payloads must be specified as hexadecimal content.
  See tags `<generic_short_table>`, `<generic_long_table>` and `<generic_descriptor>` in xref:xml-generic[xrefstyle=short].

==== XML file structure

The `<tsduck>` root node contains any number of tables:

[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<tsduck>
  <!-- any number of table structures -->
</tsduck>
----

The table structures are documented in the following sections.
Descriptors are documented right after.
Tables and descriptors are grouped by standard bodies or private parties which defined them.

When a table or structure is not supported by TSDuck, it is still possible to represent it using
the generic structures `<generic_short_table>`, `<generic_long_table>` and `<generic_descriptor>`
(see xref:xml-generic[xrefstyle=short]).

==== Table metadata

Although not documented in the following reference sections and not actually part of the binary table,
each table structure accepts the following metadata information.

This information is optional and typically generated by tools and plugins which extract tables from a stream.
They are informational only.
The `<metadata>` structure is ignored when an XML file is read.

[source,xml]
----
<metadata PID="uint13, optional"
          time="YYYY-MM-DD hh:mm:ss, optional"
          first_ts_packet="uint64, optional"
          last_ts_packet="uint64, optional">
  <section>
    Hexadecimal content.
  </section>
</metadata>
----

The `<section>` structures are used to propagate a copy of the entire binary sections of the original table.
There is one `<section>` structure per binary section.
These structures are generated by the command `tstables` and the plugin `tables` only when the
option `--meta-sections` is supplied.

include::si-xml/mpeg/tables.adoc[]
include::si-xml/dvb/tables.adoc[]
include::si-xml/scte/tables.adoc[]
include::si-xml/atsc/tables.adoc[]
include::si-xml/isdb/tables.adoc[]
include::si-xml/mpeg/descriptors.adoc[]
include::si-xml/dvb/descriptors.adoc[]
include::si-xml/dtg/descriptors.adoc[]
include::si-xml/eacem/descriptors.adoc[]
include::si-xml/eutelsat/descriptors.adoc[]
include::si-xml/nordig/descriptors.adoc[]
include::si-xml/sky/descriptors.adoc[]
include::si-xml/australia/descriptors.adoc[]
include::si-xml/avs/descriptors.adoc[]
include::si-xml/aom/descriptors.adoc[]
include::si-xml/uwa/descriptors.adoc[]
include::si-xml/scte/descriptors.adoc[]
include::si-xml/atsc/descriptors.adoc[]
include::si-xml/isdb/descriptors.adoc[]

[#xml-generic]
=== Generic format for unsupported tables and descriptors

Unsupported tables and descriptors can be represented using generic XML tags.

==== Generic short table

[source,xml]
----
<generic_short_table table_id="uint8, required" private="bool, default=true">

  Generic table with binary payload of one short section, to be used when a
  specific table is not yet implemented. The body of this element shall contain
  an even number of hexadecimal digits, the payload of the short section.

  The private indicator shall be false on MPEG-defined sections and preferably
  true on DVB-defined and user-defined sections.

</generic_short_table>
----

==== Generic long table

[source,xml]
----
<generic_long_table
    table_id="uint8, required"
    table_id_ext="uint16, default=0xFFFF"
    version="uint5, default=0"
    current="bool, default=true"
    private="bool, default=true">

  Generic table with binary payload of long sections, to be used when a specific
  table is not yet implemented.

  The private indicator shall be false on MPEG-defined sections and preferably
  true on DVB-defined and user-defined sections.

  <!-- One per section -->
  <section>
    The body of the section elements shall contain an even number of hexadecimal
    digits, the payload of the long section. The CRC32 field is not part of this
    payload, it will be recomputed.
  </section>

</generic_long_table>
----

==== Generic descriptor

[source,xml]
----
<generic_descriptor tag="uint8, required">

  Generic descriptor with binary payload, to be used when a specific descriptor
  is not yet implemented. The body of this element shall contain an even number
  of hexadecimal digits.

</generic_descriptor>
----
