//----------------------------------------------------------------------------
//
// TSDuck - The MPEG Transport Stream Toolkit
// Copyright (c) 2005-2025, Thierry Lelegard
// BSD-2-Clause license, see LICENSE.txt file or https://tsduck.io/license
//
//----------------------------------------------------------------------------

<<<
=== influx

[.cmd-header]
Send live metrics to InfluxDB, a data source for Grafana

By default, the plugin sends the global transport stream bitrate only.
Using options, other bitrate information are sent: by PID, by type of PID (audio, video, etc.), by service.

It is also possible to send most error counters which are defined in <<ETSI-101-290>>.

Be careful to send the required information for your graph only.
Sending bitrate information for all PID's, all types of PID's, and all services,
every second, may overload the InfluxDB database. Do some benchmarking first.

[.usage]
Usage

[source,shell]
----
$ tsp -P influx [options]
----

[.usage]
Timing options

[.opt]
*-i* _seconds_ +
*--interval* _seconds_

[.optdoc]
Interval in seconds between metrics reports to InfluxDB.

[.optdoc]
The default is 5 seconds. This is usually the minimal update interval in Grafana.

[.opt]
*--local-time*

[.optdoc]
Transmit timestamps as local time, based on the current system configuration.

[.optdoc]
By default, timestamps are transmitted as UTC time.

[.opt]
*--pcr-based*

[.optdoc]
Use playout time based on PCR values.
By default, the time is based on the wall-clock time (real time).

[.opt]
*--start-time* _year/month/day:hour:minute:second_

[.optdoc]
With `--pcr-based` or `--timestamp-based`, specify the initial date and time reference.

[.optdoc]
By default, with `--pcr-based` or `--timestamp-based`, the activity starts at the first UTC time which is found in a DVB TDT or ATSC STT.

[.opt]
*--timestamp-based*

[.optdoc]
Use playout time based on timestamp values from the input plugin.
When input timestamps are not available or not monotonic, fallback to `--pcr-based`.
By default, the time is based on the wall-clock time (real time).

[.usage]
Monitored information options

[.opt]
*-a* +
*--all-pids*

[.optdoc]
Send bitrate monitoring data for all PID's.
Equivalent to `--pid 0-8191`.

[.opt]
*--max-severity* _value_

[.optdoc]
With `--tr-101-290`, specify the maximum severity of error counters to send.
<<ETSI-101-290>> defines severity from 1 (most severe) to 3 (less severe).
TSDuck adds informational counters at severity 4.

[.optdoc]
By default, all error counters are sent.

[.opt]
*-n* +
*--names*

[.optdoc]
With `--services`, the services are identified in InfluxDB by their name, when available.
Services without name are identified by their id in decimal.

[.opt]
*-p* _pid1[-pid2]_ +
*--pid* _pid1[-pid2]_

[.optdoc]
Send bitrate monitoring data for the specified PID's.
The PID's are identified in InfluxDB by their value in decimal.

[.optdoc]
Several `--pid` options may be specified.
To save bandwidth and database space, PID's with no packets during an interval are not reported for that interval.

[.opt]
*-s* +
*--services*

[.optdoc]
Send bitrate monitoring data for services.
The services are identified in InfluxDB by their id in decimal.

[.opt]
*--tr-101-290*

[.optdoc]
Send error counters as defined in <<ETSI-101-290>>.
This plugin can detect a subset of ETSI TR 101 290 only:
all transport stream logical checks are performed but physical checks on modulation cannot be reported.
See more details below.

[.opt]
*--type*

[.optdoc]
Send bitrate monitoring by type of PID's (audio, video, subtitles, PSI, etc.)
See more details below.

include::{docdir}/opt/group-influx.adoc[tags=!*]

[.usage]
Tuning options

[.opt]
*--max-metrics* _count_

[.optdoc]
Terminate `tsp` after sending the specified number of metrics.
This is a test option. The processing is never stopped by default.

[.opt]
*--queue-size* _count_

[.optdoc]
Maximum number of queued metrics between the plugin thread and the communication thread with InfluxDB.

[.optdoc]
Sending metrics data to the InfluxDB server means calling the Web API of the server and posting data through HTTP.
Depending on the response time of the server, this may introduce some delay in real-time streams.
To avoid this, the communication with the InfluxDB server is asynchronously performed in an independent thread.
The metrics data are queued between the plugin thread and the communication thread, without delaying the plugin thread.
The number of messages in that queue is limited to avoid memory exhaustion in case of communication problem.
When the queue becomes full, additional metrics are dropped.

[.optdoc]
On real-time streams, where metrics data are sent every few seconds, there is never more than one message in that queue.
However, with `--pcr-based` or `--timestamp-based`, on off-line streams which are processed at high speed (files for instance),
the metrics may be generated faster than they can be sent and the queue may grow.
Increase the queue size if some metrics are lost.

[.optdoc]
The default queue size is 10 messages.

include::{docdir}/opt/group-common-plugins.adoc[tags=!*]

==== Building Flux queries for Grafana

This plugin sends metrics data to InfluxDB.
On top of that, the user has to build Flux queries in Grafana to extract the appropriate data to visualize.
This section describes the precise metrics which are sent to InfluxDB.
The provided information shall be used to build Flux queries.

At each specified interval (option `--interval`), this plugin sends a list of metrics entries.

A time stamp is always provided with each data entry.
Depending on the plugin options, this can be a local time or a UTC time,
a wall-clock time or a time which is extracted from the stream.

In each data entry, the `_measurement` is the either the string `bitrate` or the string `counter`.
The field `_value` is either a bitrate in bits/second or a number of errors (with `counter`).
The `_value` type is `float` (in practice, an integer value is provided).

===== Bitrate metrics

In each bitrate entry, the field `_measurement` is `bitrate` and the tag `scope` indicate the type of entry.
Depending on the value value of `scope`, a second tag is provided.

The following table lists the possible `scope` values and the corresponding second tag.

.InfluxDB bitrate metrics
[cols="<1m,<1m,<1,<1",stripes=none,options="autowidth"]
|===
|`scope` |Tag 2 |Tag 2 value |Bitrate value

|ts
|tsid
|TS id in decimal.
|Full TS bitrate.

|pid
|pid
|PID in decimal.
|With `--pid`, bitrate of that PID.

|service
|service
|Service id in decimal, or service name, or `global` for all global PID's.
|With `--service`, cumulated bitrate of all PID's of that service.

|type
|type
|One of `audio`, `data`, `ecm`, `emm`, `pcr`, `psi`, `stuffing`, `subtitles`, `undefined`, `video`.
|With `--type`, cumulated bitrate of all PID's of that type.

|===

Note that if a PID is shared between several services,
its bitrate is included in the bitrate of all services it belongs to.
In that case, the sum of the bitrate of all services is greater than the global TS bitrate.

To reduce the amount of logged data, bitrates with value zero are not sent.
For instance, using option `--all-pids`, a `pid` record is sent only for PID's with a non-zero bitrate during that interval.

[.usage]
Examples

By default, InfluxDB receives the following data:

[source,text]
----
bitrate,scope=ts,tsid=4 value=22936796 1548161530912
----

With option `--type` on a clear stream, InfluxDB receives the following data:

[source,text]
----
bitrate,scope=ts,tsid=4 value=22936796 1548161530912
bitrate,scope=type,type=psi value=231915 1548161530912
bitrate,scope=type,type=video value=20195737 1548161530912
bitrate,scope=type,type=audio value=2207176 1548161530912
bitrate,scope=type,type=subtitles value=102425 1548161530912
bitrate,scope=type,type=data value=199543 1548161530912
----

With options `--services --names`, InfluxDB receives the following data:

[source,text]
----
bitrate,scope=ts,tsid=4 value=22936796 1548161530912
bitrate,scope=service,service=M6 value=3874631 1548161530912
bitrate,scope=service,service=W9 value=5054905 1548161530912
bitrate,scope=service,service=Arte value=4344830 1548161530912
bitrate,scope=service,service=France\ 5 value=3736119 1548161530912
bitrate,scope=service,service=6ter value=5694397 1548161530912
bitrate,scope=service,service=global value=231915 1548161530912
----

===== ETSI TR 101 290 error counter metrics

With option `--tr-101-290`, each metrics entry contains one error counter for the last measurement interval.

Each entry contains the following information:

[.compact-list]
* Field `_measurement`: `counter`.
* Tag `name`: name of the error counter, as defined in <<ETSI-101-290>>, lowercase.
* Tag `severity`: an integer value from 1 to 4, defining the severity of the error.
  The severity 1 (most severe) to 3 (less severe) are defined by <<ETSI-101-290>>
  in sections 5.2.1 to 5.2.3. The severity 4 (informational) is added by TSDuck.

The following table lists all rules which are implemented in this plugin and which
error counter is incremented. The reference "x.y" is the rule number in <<ETSI-101-290>> section 5.2.
In "x.y/z", "z" is a sequence number when the same rule includes distinct checks.
In "x.y/zU", "U" means unreferenced in <<ETSI-101-290>>, a new rule which seems necessary.

The first colum of the table indicates which rules are implemented (X) and which are not (-).
The severity is the first digit "x" in "x.y/z".
The descriptions of the rule are directly copied from <<ETSI-101-290>>.

.InfluxDB ETSI TR 101 290 error counter metrics
[cols="^1,<1,<1m,<1",stripes=none,options="autowidth"]
|===
|Imp. |Ref. |`name` |Description

|X
|1.1
|TS_sync_loss
|Loss of synchronization with consideration of hysteresis parameters.

|X
|1.2
|Sync_byte_error
|Sync_byte not equal 0x47.

|X
|1.3/1
|PAT_error
|PID 0x0000 does not occur at least every 0,5 s.

|X
|1.3/2
|PAT_error
|a PID 0x0000 does not contain a table_id 0x00 (i.e. a PAT).

|X
|1.3/3
|PAT_error
|Scrambling_control_field is not 00 for PID 0x0000

|X
|1.3.a/1
|PAT_error_2
|Sections with table_id 0x00 do not occur at least every 0,5 s on PID 0x0000.

|X
|1.3.a/2
|PAT_error_2
|Section with table_id other than 0x00 found on PID 0x0000.

|X
|1.3.a/3
|PAT_error_2
|Scrambling_control_field is not 00 for PID 0x0000.

|X
|1.3.a/4U
|PAT_error_2
|A PAT section is present on PID other than 0x0000.

|X
|1.3.a/5U
|PAT_error_2
|A PAT table is syntactically incorrect.

|X
|1.4
|Continuity_count_error
|Incorrect packet order, a packet occurs more than twice, lost packet.

|X
|1.5/1
|PMT_error
|Sections with table_id 0x02, (i.e. a PMT), do not occur at least every 0,5 s on the PID which is referred to in the PAT.

|X
|1.5/2
|PMT_error
|Scrambling_control_field is not 00 for all PIDs containing sections with table_id 0x02 (i.e. a PMT).

|X
|1.5.a/1
|PMT_error_2
|Sections with table_id 0x02, (i.e. a PMT), do not occur at least every 0,5 s
 on each program_map_PID which is referred to in the PAT.

|X
|1.5.a/2
|PMT_error_2
|Scrambling_control_field is not 00 for all packets containing information of sections with
 table_id 0x02 (i.e. a PMT) on each program_map_PID which is referred to in the PAT.

|X
|1.5.a/3U
|PMT_error_2
|A PMT table is syntactically incorrect.

|X
|1.6
|PID_error
|Referred PID does not occur for a user specified period.

|X
|2.1
|Transport_error
|Transport_error_indicator in the TS-Header is set to "1".

|X
|2.2/1
|CRC_error
|CRC error occurred in CAT, PAT, PMT, NIT, EIT, BAT, SDT or TOT table.

|X
|2.2/2U
|CRC_error_2
|CRC error occurred in other table id than specified in CRC_error.

|X
|2.3/1
|PCR_error
|PCR discontinuity of more than 100 ms occurring without specific indication.

|X
|2.3/2
|PCR_error
|Time interval between two consecutive PCR values more than 100 ms.

|X
|2.3.a
|PCR_repetition_error
|Time interval between two consecutive PCR values more than 100 ms.

|X
|2.3.b
|PCR_discontinuity_indicator_error
|The difference between two consecutive PCR values (PCRi+1 – PCRi) is outside the range
 of 0...100 ms without the discontinuity_indicator set.

|-
|2.4
|PCR_accuracy_error
|PCR accuracy of selected programme is not within +/- 500 ns.

|X
|2.5
|PTS_error
|PTS repetition period more than 700 ms.

|X
|2.6/1
|CAT_error
|Packets with transport_scrambling_control not 00 present, but no section with table_id = 0x01 (i.e. a CAT) present.

|X
|2.6/2
|CAT_error
|Section with table_id other than 0x01 (i.e. not a CAT) found on PID 0x0001.

|X
|2.6/3U
|CAT_error
|A CAT section is present on PID other than 0x0001.

|X
|2.6/4U
|CAT_error
|A CAT table is syntactically incorrect.

|X
|3.1/1
|NIT_error
|Section with table_id other than 0x40 or 0x41 or 0x72 (i. e. not an NIT or ST) found on PID 0x0010.

|X
|3.1/2
|NIT_error
|No section with table_id 0x40 or 0x41 (i.e. an NIT) in PID value 0x0010 for more than 10 s.

|X
|3.1.a/1
|NIT_actual_error
|Section with table_id other than 0x40 or 0x41 or 0x72 (i.e. not an NIT or ST) found on PID 0x0010.

|X
|3.1.a/2
|NIT_actual_error
|No section with table_id 0x40 (i.e. an NIT_actual) in PID value 0x0010 for more than 10 s.

|X
|3.1.a/3
|NIT_actual_error
|Any two sections with table_id = 0x40 (NIT_actual) occur on PID 0x0010 within a specified value (25 ms or lower).

|X
|3.1.a/4U
|NIT_actual_error
|A NIT_actual section is present on PID other than 0x0010.

|X
|3.1.b/1
|NIT_other_error
|Interval between sections with the same section_number and table_id = 0x41 (NIT_other)
 on PID 0x0010 longer than a specified value (10 s or higher).

|X
|3.1.b/2U
|NIT_other_error
|A NIT_other section is present on PID other than 0x0010.

|X
|3.2/1
|SI_repetition_error
|Repetition rate of SI tables outside of specified limits.

|X
|3.2/2U
|SI_PID_error
|A SI sections is present on PID other than its allocated PID.

|-
|3.3/1
|Buffer_error
|TB_buffering_error: overflow of transport buffer (TBn).

|-
|3.3/2
|Buffer_error
|TBsys_buffering_error: overflow of transport buffer for system information (Tbsys).

|-
|3.3/3
|Buffer_error
|MB_buffering_error: overflow of multiplexing buffer (MBn) or if the vbv_delay method is used: underflow of multiplexing buffer (Mbn).

|-
|3.3/4
|Buffer_error
|EB_buffering_error: overflow of elementary stream buffer (EBn) or if the leak method is used:
 underflow of elementary stream buffer (EBn) though low_delay_flag and DSM_trick_mode_flag are
 set to 0 else (vbv_delay method) underflow of elementary stream buffer (EBn).

|-
|3.3/5
|Buffer_error
|B_buffering_error: overflow or underflow of main buffer (Bn).

|-
|3.3/6
|Buffer_error
|Bsys_buffering_error: overflow of PSI input buffer (Bsys).

|X
|3.4
|Unreferenced_PID
|PID (other than PAT, CAT, CAT_PIDs, PMT_PIDs, NIT_PID, SDT_PID, TDT_PID, EIT_PID, RST_PID,
 reserved_for_future_use PIDs, or PIDs user defined as private data streams) not referred to
 by a PMT within 0,5 s.

|X
|3.4.a
|Unreferenced_PID
|PID (other than PMT_PIDs, PIDs with numbers between 0x00 and 0x1F or PIDs user defined as private data streams)
 not referred to by a PMT or a CAT within 0,5 s.

|X
|3.5/1
|SDT_error
|Sections with table_id = 0x42 (SDT, actual TS) not present on PID 0x0011 for more than 2 s.

|X
|3.5/2
|SDT_error
|Sections with table_ids other than 0x42, 0x46, 0x4A or 0x72 found on PID 0x0011.

|X
|3.5.a/1
|SDT_actual_error
|Sections with table_id = 0x42 (SDT, actual TS) not present on PID 0x0011 for more than 2 s.

|X
|3.5.a/2
|SDT_actual_error
|Sections with table_ids other than 0x42, 0x46, 0x4A or 0x72 found on PID 0x0011.

|X
|3.5.a/3
|SDT_actual_error
|Any two sections  table_id = 0x42 (SDT_actual) occur on PID 0x0011 within a specified value (25 ms or lower).

|X
|3.5.a/4U
|SDT_actual_error
|A SDT_actual section is present on PID other than 0x0011.

|X
|3.5.b/1
|SDT_other_error
|Interval between sections with the same section_number and table_id = 0x46 (SDT, other TS)
 on PID 0x0011 longer than a specified value (10s or higher).

|X
|3.5.b/2U
|SDT_other_error
|A SDT_other section is present on PID other than 0x0011.

|X
|3.6/1
|EIT_error
|Sections with table_id = 0x4E (EIT-P/F, actual TS) not present on PID 0x0012 for more than 2 s.

|X
|3.6/2
|EIT_error
|Sections with table_ids other than in the range 0x4E - 0x6F or 0x72 found on PID 0x0012.

|X
|3.6/3U
|EIT_error
|An EIT section is present on PID other than 0x0012.

|X
|3.6.a/1
|EIT_actual_error
|Section '0' with table_id = 0x4E (EIT-P, actual TS) not present on PID 0x0012 for more than 2 s.

|X
|3.6.a/2
|EIT_actual_error
|Section '1' with table_id = 0x4E (EIT-F, actual TS) not present on PID 0x0012 for more than 2 s.

|X
|3.6.a/3
|EIT_actual_error
|Sections with table_ids other than in the range 0x4E - 0x6F or 0x72 found on PID 0x0012.

|X
|3.6.a/4
|EIT_actual_error
|Any two sections with table_id = 0x4E (EIT-P/F, actual TS) occur on PID 0x0012 within a specified value (25 ms or lower).

|X
|3.6.b/1
|EIT_other_error
|Interval between sections '0' with table_id = 0x4F (EIT-P, other TS) on PID 0x0012 longer than a specified value (10 s or higher).

|X
|3.6.b/2
|EIT_other_error
|Interval between sections '1' with table_id = 0x4F (EIT-F, other TS) on PID 0x0012 longer than a specified value (10 s or higher).

|X
|3.6.c/1
|EIT_PF_error
|If either section ('0' or '1') of each EIT P/F sub table is present both should exist.

|X
|3.6.c/2U
|EIT_PF_error
|An EIT P/F section has section number greater that 1.

|X
|3.7/1
|RST_error
|Sections with table_id other than 0x71 or 0x72 found on PID 0x0013.

|X
|3.7/2
|RST_error
|Any two sections with table_id = 0x71 (RST) occur on PID 0x0013 within a specified value (25 ms or lower).

|X
|3.7/3U
|RST_error
|A RST section is present on PID other than 0x0013.

|X
|3.8/1
|TDT_error
|Sections with table_id = 0x70 (TDT) not present on PID 0x0014 for more than 30 s.

|X
|3.8/2
|TDT_error
|Sections with table_id other than 0x70, 0x72 (ST) or 0x73 (TOT) found on PID 0x0014.

|X
|3.8/3
|TDT_error
|Any two sections with table_id = 0x70 (TDT) occur on PID 0x0014 within a specified value (25 ms or lower).

|X
|3.8/4U
|TDT_error
|A TDT section is present on PID other than 0x0014.

|-
|3.9
|Empty_buffer_error
|Transport buffer (TBn) not empty at least once per second or transport buffer for system information
 (TBsys) not empty at least once per second or if the leak method is used multiplexing buffer (MBn)
 not empty at least once per second.

|-
|3.10/1
|Data_delay_error
|Delay of data (except still picture video data) through the TSTD buffers superior to 1 second.

|-
|3.10/2
|Data_delay_error
|Delay of still picture video data through the TSTD buffers superior to 60 s.

|X
|4
|packet_count
|Number of TS packets during that interval of analysis.

|X
|4
|error_count
|Number of errors during that interval of analysis. This is not exactly the same as
 the sum of all error counters in that interval because <<ETSI-101-290>> sometimes
 includes the same check in distinct counters.

|===

[.usage]
Examples

With option `--tr-101-290`, InfluxDB receives the following data:

[source,text]
----
bitrate,scope=ts,tsid=4 value=22936796 1548161530912
counter,name=ts_sync_loss,severity=1 value=0 1548161530912
counter,name=sync_byte_error,severity=1 value=0 1548161530912
counter,name=pat_error,severity=1 value=0 1548161530912
counter,name=pat_error_2,severity=1 value=0 1548161530912
counter,name=continuity_count_error,severity=1 value=220 1548161530912
counter,name=pmt_error,severity=1 value=0 1548161530912
counter,name=pmt_error_2,severity=1 value=0 1548161530912
counter,name=pid_error,severity=1 value=0 1548161530912
counter,name=transport_error,severity=2 value=0 1548161530912
counter,name=crc_error,severity=2 value=0 1548161530912
counter,name=crc_error_2,severity=2 value=0 1548161530912
counter,name=pcr_error,severity=2 value=0 1548161530912
counter,name=pcr_repetition_error,severity=2 value=0 1548161530912
counter,name=pcr_discontinuity_indicator_error,severity=2 value=0 1548161530912
counter,name=pcr_accuracy_error,severity=2 value=0 1548161530912
counter,name=pts_error,severity=2 value=10 1548161530912
counter,name=cat_error,severity=2 value=0 1548161530912
counter,name=nit_error,severity=3 value=0 1548161530912
counter,name=nit_actual_error,severity=3 value=0 1548161530912
counter,name=nit_other_error,severity=3 value=0 1548161530912
counter,name=si_repetition_error,severity=3 value=0 1548161530912
counter,name=si_pid_error,severity=3 value=0 1548161530912
counter,name=buffer_error,severity=3 value=0 1548161530912
counter,name=unreferenced_pid,severity=3 value=0 1548161530912
counter,name=sdt_error,severity=3 value=0 1548161530912
counter,name=sdt_actual_error,severity=3 value=0 1548161530912
counter,name=sdt_other_error,severity=3 value=0 1548161530912
counter,name=eit_error,severity=3 value=0 1548161530912
counter,name=eit_actual_error,severity=3 value=0 1548161530912
counter,name=eit_other_error,severity=3 value=1 1548161530912
counter,name=eit_pf_error,severity=3 value=31 1548161530912
counter,name=rst_error,severity=3 value=0 1548161530912
counter,name=tdt_error,severity=3 value=0 1548161530912
counter,name=empty_buffer_error,severity=3 value=0 1548161530912
counter,name=data_delay_error,severity=3 value=0 1548161530912
counter,name=packet_count,severity=4 value=43220 1548161530912
counter,name=error_count,severity=4 value=262 1548161530912
----
