//----------------------------------------------------------------------------
//
// TSDuck - The MPEG Transport Stream Toolkit
// Copyright (c) 2005-2025, Thierry Lelegard
// BSD-2-Clause license, see LICENSE.txt file or https://tsduck.io/license
//
//----------------------------------------------------------------------------

<<<
=== influx

[.cmd-header]
Send live bitrate metrics to InfluxDB, a data source for Grafana

By default, the plugin sends the global transport stream bitrate only.
Using options, other bitrate information are sent: by PID, by type of PID
(audio, video, etc.), by service.

Be careful to send the required information for your graph only.
Sending bitrate information for all PID's, all types of PID's, and all services,
every second, may overload the InfluxDB database. Do some benchmarking first.

[.usage]
Usage

[source,shell]
----
$ tsp -P influx [options]
----

[.usage]
Timing options

[.opt]
*-i* _seconds_ +
*--interval* _seconds_

[.optdoc]
Interval in seconds between metrics reports to InfluxDB.

[.optdoc]
The default is 5 seconds. This is usually the minimal update interval in Grafana.

[.opt]
*--local-time*

[.optdoc]
Transmit timestamps as local time, based on the current system configuration.

[.optdoc]
By default, timestamps are transmitted as UTC time.

[.opt]
*--pcr-based*

[.optdoc]
Use playout time based on PCR values.

[.optdoc]
By default, the time is based on the wall-clock time (real time).

[.opt]
*--start-time* _year/month/day:hour:minute:second_

[.optdoc]
With `--pcr-based`, specify the initial date and time reference.

[.optdoc]
By default, with `--pcr-based`, the activity starts at the first UTC time which is found in a DVB TDT or ATSC STT.

[.usage]
Monitored information options

[.opt]
*-a* +
*--all-pids*

[.optdoc]
Send bitrate monitoring data for all PID's.
Equivalent to `--pid 0-8191`.

[.opt]
*-n* +
*--names*

[.optdoc]
With `--services`, the services are identified in InfluxDB by their name, when available.
Services without name are identified by their id in decimal.

[.opt]
*-p* _pid1[-pid2]_ +
*--pid* _pid1[-pid2]_

[.optdoc]
Send bitrate monitoring data for the specified PID's.
The PID's are identified in InfluxDB by their value in decimal.

[.optdoc]
Several `--pid` options may be specified.
To save bandwidth and database space, PID's with no packets during an interval are not reported for that interval.

[.opt]
*-s* +
*--services*

[.optdoc]
Send bitrate monitoring data for services.
The services are identified in InfluxDB by their id in decimal.

[.opt]
*--type*

[.optdoc]
Send bitrate monitoring by type of PID's (audio, video, subtitles, PSI, etc.)
See more details below.

include::{docdir}/opt/group-influx.adoc[tags=!*]

[.usage]
Tuning options

[.opt]
*--max-metrics* _count_

[.optdoc]
Terminate `tsp` after sending the specified number of metrics.
This is a test option. The processing is never stopped by default.

[.opt]
*--queue-size* _count_

[.optdoc]
Maximum number of queued metrics between the plugin thread and the communication thread with InfluxDB.

[.optdoc]
Sending metrics data to the InfluxDB server means calling the Web API of the server and posting data through HTTP.
Depending on the response time of the server, this may introduce some delay in real-time streams.
To avoid this, the communication with the InfluxDB server is asynchronously performed in an independent thread.
The metrics data are queued between the plugin thread and the communication thread, without delaying the plugin thread.
The number of messages in that queue is limited to avoid memory exhaustion in case of communication problem.
When the queue becomes full, additional metrics are dropped.

[.optdoc]
On real-time streams, where metrics data are sent every few seconds, there is never more than one message in that queue.
However, with `--pcr-based`, on off-line streams which are processed at high speed (files for instance),
the metrics may be generated faster than they can be sent and the queue may grow.
Increase the queue size if some metrics are lost.

[.optdoc]
The default queue size is 10 messages.

include::{docdir}/opt/group-common-plugins.adoc[tags=!*]

[.usage]
Building Flux queries for Grafana

This plugin sends bitrate data to InfluxDB.
On top of that, the user has to build Flux requests in Grafana to extract the appropriate data to visualize.

In each data entry, the `_measurement` is the string `bitrate` and the `_value` is a bitrate in bits/second
of type `float` (in practice, an integer value is provided).

A time stamp is always provided with each entry.
Depending on the plugin options, this can be a local time or a UTC time,
a wall-clock time or a time which is extracted from the stream.

In each data entry, the tag `scope` indicate the type of entry.
Depending on its value, a second tag is provided.
The following table lists the possible `scope` values and the corresponding second tag.

.InfluxDB received data
[cols="<1m,<1m,<1,<1",stripes=none,options="autowidth"]
|===
|`scope` |Tag 2 |Tag 2 value |Bitrate value

|ts
|tsid
|TS id in decimal.
|Full TS bitrate.

|pid
|pid
|PID in decimal.
|With `--pid`, bitrate of that PID.

|service
|service
|Service id in decimal, or service name, or `global` for all global PID's.
|With `--service`, cumulated bitrate of all PID's of that service.

|type
|type
|One of `audio`, `data`, `ecm`, `emm`, `pcr`, `psi`, `stuffing`, `subtitles`, `undefined`, `video`.
|With `--type`, cumulated bitrate of all PID's of that type.

|===

Note that if a PID is shared between several services,
its bitrate is included in the bitrate of all services it belongs to.
In that case, the sum of the bitrate of all services is greater than the global TS bitrate.

To reduce the amount of logged data, bitrates with value zero are not sent.
For instance, using option `--all-pids`, a `pid` record is sent only for PID's with a non-zero bitrate during that interval.
