//----------------------------------------------------------------------------
//
// TSDuck - The MPEG Transport Stream Toolkit
// Copyright (c) 2005-2026, Thierry Lelegard
// BSD-2-Clause license, see LICENSE.txt file or https://tsduck.io/license
//
//----------------------------------------------------------------------------

<<<
=== slice

[.cmd-header]
Pass or drop packets based on packet numbers

This plugin passes or drops packets based on packet numbers or relative transport stream time.
It can be used to extract selected portions of a TS and group them into one single output.

[.usage]
Usage

[source,shell]
----
$ tsp -P slice [options]
----

[.usage]
Options

[.opt]
*-d* _value_ +
*--drop* _value_

[.optdoc]
All packets are dropped after the specified packet number.

[.optdoc]
Several `--drop` options may be specified.

[.opt]
*-i* +
*--ignore-pcr*

[.optdoc]
When `--seconds` or `--milli-seconds` is used, do not use PCR's to compute time values.
Only rely on bitrate as determined by previous plugins in the chain.

[.opt]
*-m* +
*--milli-seconds*

[.optdoc]
With options `--drop`, `--null`, `--pass` and `--stop`, interpret the integer values as milli-seconds from the beginning, not as packet numbers.
Time is measured based on bitrate and packet count, not on real time.

[.opt]
*-n* _value_ +
*--null* _value_

[.optdoc]
All packets are replaced by null packets after the specified packet number.
Several --null options may be specified.

[.opt]
*-p* _value_ +
*--pass* _value_

[.optdoc]
All packets are passed unmodified after the specified packet number.

[.optdoc]
Several `--pass` options may be specified.
This is the default for the initial packets.

[.opt]
*--preserve-units*

[.optdoc]
Preserve payload unit boundaries (PUSI) when starting to pass or starting to drop packets.
When transitioning from passing to dropping packets, continue to pass each PID until the next payload unit boundary.
When transitioning from dropping to passing packets, start to pass each PID at the next payload unit boundary.

[.optdoc]
By default, the transport stream is abruptly cut at transition points.

[.opt]
*--seconds*

[.optdoc]
With options `--drop`, `--null`, `--pass` and `--stop`, interpret the integer values as seconds from the beginning, not as packet numbers.
Time is measured based on bitrate and packet count, not on real time.

[.opt]
*--silent-after* _value_

[.optdoc]
With option `--preserve-unit`, specify the maximum number of packets after which a PID is considered as silent during a transition period.

[.optdoc]
The default is 5000 packets (7.3 Mbits).

[.opt]
*-s* _value_ +
*--stop* _value_

[.optdoc]
Packet transmission stops after the specified packet number and `tsp` terminates.

[.opt]
*--stuffing*

[.optdoc]
With option `--preserve-unit`, maintain the global bitrate of the transport stream during transition periods
by replacing dropped packets with null packets.

[.optdoc]
By default, during transition periods, the bitrate is gradually decreasing or increasing.

include::{docdir}/opt/group-common-plugins.adoc[tags=!*]
