//----------------------------------------------------------------------------
//
// TSDuck - The MPEG Transport Stream Toolkit
// Copyright (c) 2005-2025, Thierry Lelegard
// BSD-2-Clause license, see LICENSE.txt file or https://tsduck.io/license
//
//----------------------------------------------------------------------------

<<<
=== splicemonitor

[.cmd-header]
Monitor SCTE 35 splice information

This plugin monitors splice information sections, as defined by the <<SCTE-35>> standard.
The event reference, the number of occurrences of each command and the time between the command
and the event itself (sometimes called _pre-roll time_) are displayed.

[.usage]
Usage

[source,shell]
----
$ tsp -P splicemonitor [options]
----

[.usage]
General options

[.opt]
*--alarm-command* _"command"_

[.optdoc]
Command to run when a splice event is outside the nominal range as specified by other `--min` and `--max` options.

[.optdoc]
The command receives seven additional parameters:

[.optdoc]
[.compact-list]
1. A human-readable message, the same as logged by the plugin.
2. The PID of the splice command.
3. The event id.
4. The string `in` or `out` for splice in / splice out command.
5. The adjusted PTS value in the splice command.
6. Pre-roll time in milliseconds. This is the time between the first occurrence of a splice command and the corresponding event.
7. Number of occurences of the command before the event.

[.optdoc]
These parameters can be used or ignored by the alarm command.

[.opt]
*-a* +
*--all-commands*

[.optdoc]
Same as `--display-commands` but display all SCTE-35 splice information commands.
This is equivalent to `--select-commands 0-255`.

[.optdoc]
By default, only display splice insert commands.

[.opt]
*-d* +
*--display-commands*

[.optdoc]
Display the content of SCTE-35 splice insert commands.

[.optdoc]
By default, only log a short event description.

[.opt]
*--max-pre-roll-time* _value_

[.optdoc]
Specify a maximum pre-roll time in milliseconds for splice commands.

[.optdoc]
See option `--alarm-command` for the processing of non-nominal cases.

[.opt]
*--max-repetition* _value_

[.optdoc]
Specify a maximum number of repetitions for each splice command.

[.optdoc]
See option `--alarm-command` for the processing of non-nominal cases.

[.opt]
*--meta-sections*

[.optdoc]
Add an hexadecimal dump of each section in the XML and JSON metadata.

[.opt]
*--min-pre-roll-time* _value_

[.optdoc]
Specify a minimum pre-roll time in milliseconds for splice commands.

[.optdoc]
See option `--alarm-command` for the processing of non-nominal cases.

[.opt]
*--min-repetition* _value_

[.optdoc]
Specify a minimum number of repetitions for each splice command.

[.optdoc]
See option `--alarm-command` for the processing of non-nominal cases.

[.opt]
*-n* +
*--no-adjustment*

[.optdoc]
When computing the anticipated pre-roll time at reception of a splice command,
do not try to adjust the time using the distance between the last PTS and the splice command.

[.optdoc]
By default, use the bitrate to adjust the supposed PTS of the splice command itself.

[.opt]
*-o* _file-name_ +
*--output-file* _file-name_

[.optdoc]
Specify an output text file.
With `--json`, this will be a JSON file.

[.optdoc]
By default, use the message logging system for short messages and the standard output with `--display-commands`.

[.opt]
*-i* +
*--packet-index*

[.optdoc]
Display the current TS packet index for each message or event.

[.opt]
*--select-commands* _value1[-value2]_

[.optdoc]
Same as `--display-commands` but display the specified SCTE-35 command types only.

[.optdoc]
By default, only display splice insert commands.

[.optdoc]
Several `--select-commands` can be specified.

[.opt]
*-s* _value_ +
*--splice-pid* _value_

[.optdoc]
Specify one single PID carrying SCTE-35 sections to monitor.

[.optdoc]
By default, all SCTE-35 PID's are monitored, based in their signalization in the PMT's.

[.opt]
*--tag* _'string'_

[.optdoc]
Leading tag to be displayed with each message.
Useful when the plugin is used several times in the same process.

[.opt]
*-t* _value_ +
*--time-pid* _value_

[.optdoc]
Specify one video or audio PID containing PTS timestamps to link with SCTE-35 sections to monitor.

[.optdoc]
By default, the PMT's are used to link between PTS PID's and SCTE-35 PID's.

[.opt]
*--timestamp*

[.optdoc]
Add a timestamp (current local time) inside each JSON structure (tables and events).

[.usage]
JSON logging options

[.opt]
*-j* +
*--json*

[.optdoc]
Build a JSON description of the splice event (see option `--output-file`).

[.optdoc]
When `--all-commands` is specified, each SCTE-35 table is initially formatted as XML and an automated XML-to-JSON conversion is applied.
See xref:xml-json-conv[xrefstyle=short] for more details on XML-to-JSON conversion.

include::{docdir}/opt/group-json-output.adoc[tags=!*;notitle]

[.usage]
InfluxDB options

[.opt]
*--influx* _value_

[.optdoc]
When this option is specified, all splice events of the specified types are sent to an InfluxDB server.
Sending to an InfluxDB server can be used in monitoring or alerting systems, such as Grafana.
See also other `--influx-*` options below for more details on InfluxDB.

[.optdoc]
The _value_ must be one of `immediate`, `signalled`, `cancelled`, `occurred`, `all`, or `none`.
The default is `none`, meaning no connection to an InfluxDB server.
Use `all` to specify all types of events.
Several options `--influx` are allowed.

[.usage]
InfluxDB information

The plugin `influx` describes the interactions with InfluxDB in more details (see xref:_influx[xrefstyle=short]).
However, the two plugins have distinct dynamics.
The plugin `influx` sends various metrics at regular intervals.
The plugin `splicemonitor` sends information only, and immediately, when a splice event is encountered.

A message is sent to InfluxDB for any type of event which is selected by the option `--influx`.
Each message contains exactly one entry, with the following information:

[.compact-list]
* Field `_measurement`: `splice`.
* All the following tags are always present:
** Tag `pid`: This is the PID carrying the splice section, as an integer.
** Tag `event`: This is the event id, as an integer.
** Tag `direction`: Either `out` or `in`, indicating if the event is out of network (start of an event)
   or back in network (end of the event).
** Tag `state`: One of `immediate`, `signalled`, `cancelled`, `occurred`, see option `--influx`.
* Several value fields can be provided, depending on the event. The field `start` is always present.
  All other fields are optional, subject to availability.
** Field `start`: This is the estimated start time of the event, as an integer, in milliseconds
   since the UNIX Epoch. Note that actual SCTE-35 splice events use PTS values, not actual times.
   The provided value is an estimation of the actual time which corresponds to the PTS of the event.
   The time is UTC by default, or local time if option `--influx-local-time` is used.
** Field `duration`: This is the announced duration of the event, in milliseconds.
** Field `preroll`: This is the preroll time of the event, in milliseconds.
   This value is present only for events of type `occurred`.
** Field `count`: This is the number of times the event was signalled so far.
   This is the number of times a splice command is repeated.

Sample entry:

[source,text]
----
splice,pid=1055,event=18,direction=out,state=occurred
   start=1515756561249,duration=75000,preroll=9557,count=3 1515756561249
----

include::{docdir}/opt/group-influx.adoc[tags=!*;prefix]

:opt-clock-prefix: influx
:opt-clock-context: for InfluxDB connections
include::{docdir}/opt/group-clock.adoc[tags=!*;prefix;context]

include::{docdir}/opt/group-common-plugins.adoc[tags=!*]
