//----------------------------------------------------------------------------
//
// TSDuck - The MPEG Transport Stream Toolkit
// Copyright (c) 2005-2025, Thierry Lelegard
// BSD-2-Clause license, see LICENSE.txt file or https://tsduck.io/license
//
//----------------------------------------------------------------------------

<<<
=== tspcontrol

[.cmd-header]
Send control commands to a running tsp process

This utility controls the execution of a running `tsp` process.
The target `tsp` command shall listen to control commands using the option `--control`
(see the documentation of `tsp`).

[.usage]
Usage

[source,shell]
----
$ tspcontrol [options] command ...
----

[.usage]
Parameters

[.opt]
_command ..._

[.optdoc]
The control command to send to the target `tsp` process.
See the list of control commands below.

[.optdoc]
Note that everything after the control command name is considered as options and parameters of this control command.
The options of `tspcontrol` must be placed before the control command name.

[.usage]
Options

[.opt]
*--insecure*

[.optdoc]
With `--tls`, do not verify the TLS server's certificate in the `tsp` process.
See xref:opt-tls[xrefstyle=short] for more details.

[.opt]
*--tls*

[.optdoc]
Connect to the `tsp` process using SSL/TLS.
By default, use unencrypted communications.
See xref:opt-tls[xrefstyle=short] for more details.

[.opt]
*--token* _'string'_

[.optdoc]
With `--tls`, optional authentication token which is sent to the `tsp` process.
See xref:opt-tls[xrefstyle=short] for more details.

[.opt]
*-t* [_address:]port_ +
*--tsp* [_address:]port_

[.optdoc]
Specify the IP address (or host name) and port where the target `tsp` process expects control commands
(`tsp` option `--control`).
If the IP address is omitted, the local host is used.

[.optdoc]
This is a required parameter, there is no default.

include::{docdir}/opt/group-common-commands.adoc[tags=!*]

==== List of control commands

[cols="<10m,<12,<78",frame=none,grid=none,stripes=none,options="noheader"]
|===
|*exit*
2+|Terminate the tsp process.

|
|Usage:
m|*tspcontrol exit* _[options]_

|
m|*--abort*
|Specify to immediately abort the tsp process. By default, this command notifies each plugin to terminate and let the processing continue until the process naturally exits.

|*list*
2+|List all running plugins. The listed plugin indexes can be used with other control commands
   such as `suspend`, `resume` or `restart`.

|
|Usage:
m|*tspcontrol list* [options]

|
m|*-v* +
  *--verbose*
|Produce verbose output.

|*restart*
2+|Restart a plugin with different parameters.

|
|Usage:
m|*tspcontrol restart* _[options] index [plugin-options ...]_

|
|Parameters:
|Index of the plugin to restart, followed by the new plugin parameters to use.

|
m|*-s* +
  *--same*
|Restart the plugin with the same options and parameters as the current ones.
 By default, when no plugin options are specified, restart with no option at all.

|
m|*-v* +
  *--verbose*
|Produce verbose output.

|*resume*
2+|Resume a suspended plugin.

|
|Usage:
m|*tspcontrol resume* _[options] index_

|
|Parameter:
|Index of the plugin to resume.

|
m|*-v* +
  *--verbose*
|Produce verbose output.

|*set-log*
2+|Change the log level in the `tsp` process.

|
|Usage:
m|*tspcontrol set-log* _level_

|
|Parameter:
|Specify a new logging level for the `tsp` process. It can be one of
 `fatal`, `severe`, `error`, `warning`, `info`, `verbose`, `debug` or a
 positive value for higher debug levels.

|*suspend*
2+|Suspend a plugin.
   When a packet processing plugin is suspended, the TS packets are directly passed from the previous to the next plugin,
   without going through the suspended one.
   When the output plugin is suspended, the output packets are dropped.
   The input plugin cannot be suspended.

|
|Usage:
m|*tspcontrol suspend* _[options] index_

|
|Parameters:
|Index of the plugin to suspend.

|
m|*-v* +
  *--verbose*
|Produce verbose output.

|===

[#tspcontrol-protocol]
==== Protocol description

By default, the communication between `tspcontrol` and `tsp` uses unencrypted communications.
The protocol is based on Telnet, text lines using CR-LF as end-of-line marker.

The command is sent and the response is read on the same channel, as in a good old Telnet session.

Consider the following basic `tsp` command.
The process accepts control commands on TCP port 5555.

[source,shell]
----
$ tsp --control 5555 -b 1,000,000 -I null -P regulate -O drop
----

The following two commands list the plugins in the `tsp` process,
once using `tspcontrol`, once using `telnet`.

[source,shell]
----
$ tspcontrol --tsp 5555 list
 0: -I null
 1: -P regulate
 2: -O drop
$
$ telnet localhost 5555
Trying ::1...
Connected to localhost.
Escape character is '^]'.
list
 0: -I null
 1: -P regulate
 2: -O drop
Connection closed by foreign host.
$
----

With option `--tls`, the communication uses an HTTP Web API in an encrypted SSL/TLS connection
with an optional authorization token.
The HTTP method shall be `POST` and the control command is passed as request data.
The output of the command is returned as the response of the HTTP request.

See xref:secure-control[xrefstyle=short] for more details.

Consider the modified `tsp` which follows.
It uses the TLS method and requires an authorization token to execute the command.
Note that the appropriate environment variables were previously set to specify
the server's private key and certificate.

[source,shell]
----
$ tsp --control 5555 --control-tls --control-token My-Token -b 1,000,000 -I null -P regulate -O drop
----

The `tspcontrol` command now requires to specify `--tls` and the correct authorization token.
We can see that the next command, using an incorrect authorization token, receives an error status from `tsp`.

The same result can be achieved, in a more complicated way, using the `curl` command
to post the request.

[source,shell]
----
$ tspcontrol --tsp 5555 --tls --insecure --token My-Token list
 0: -I null
 1: -P regulate
 2: -O drop
$
$ tspcontrol --tsp 5555 --tls --insecure --token Wrong-Token list
Unauthorized
$
$ curl -s -S -k -H 'Authorization: Token My-Token' https://localhost:5555/ -d 'list'
 0: -I null
 1: -P regulate
 2: -O drop
$ 
----

Note that the option `--insecure` is required when `tsp` uses a self-signed certificate.
Such a certificate is considered invalid and this option bypasses its verification.
Similarly, the `curl` option `-k` means `--insecure`.

To be clear, the option `--insecure` only bypasses the security checks on the TLS server.
The authorization checks based on the token remain.
