//----------------------------------------------------------------------------
//
// TSDuck - The MPEG Transport Stream Toolkit
// Copyright (c) 2005-2024, Thierry Lelegard
// BSD-2-Clause license, see LICENSE.txt file or https://tsduck.io/license
//
//----------------------------------------------------------------------------

=== DVB-defined descriptors

Note that a few descriptors are allowed in specific tables only since they reuse tag values which are
otherwise MPEG-reserved <<ISO-13818-1>>.
They cannot be used elsewhere.
These restrictions, when applicable, are documented in XML comments for the table-specific descriptor.
Such descriptors exist for the AIT <<ETSI-102-809>>, the UNT <<ETSI-102-006>> and the INT <<ETSI-301-192>>.

==== AAC_descriptor

Defined by DVB in <<ETSI-300-468>>.

[source,xml]
----
<AAC_descriptor
    profile_and_level="uint8, required"
    SAOC_DE="bool, default=false"
    AAC_type="uint8, optional">
  <additional_info>
    Hexadecimal content, optional
  </additional_info>
</AAC_descriptor>
----

==== AC3_descriptor

Defined by DVB in <<ETSI-300-468>>.

Because of the presence of an ATSC version of the `AC3_descriptor`,
the XML name for the DVB version is `<DVB_AC3_descriptor>`.
For compatibility, `<AC3_descriptor>` is still accepted.

[source,xml]
----
<DVB_AC3_descriptor
    component_type="uint8, optional"
    bsid="uint8, optional"
    mainid="uint8, optional"
    asvc="uint8, optional">
  <additional_info>
    Hexadecimal content, optional
  </additional_info>
</DVB_AC3_descriptor>
----

==== AC4_descriptor

Defined by DVB in <<ETSI-300-468>>.

Because of the possible introduction of an ATSC version of the `AC4_descriptor`,
the XML name for the DVB version is `<DVB_AC4_descriptor>`.
For compatibility, `<AC4_descriptor>` is still accepted.

[source,xml]
----
<DVB_AC4_descriptor
    ac4_dialog_enhancement_enabled="bool, optional"
    ac4_channel_mode="uint2, optional">
  <ac4_dsi_toc>
    Hexadecimal content, optional
  </ac4_dsi_toc>
  <additional_info>
    Hexadecimal content, optional
  </additional_info>
</DVB_AC4_descriptor>
----

==== adaptation_field_data_descriptor

Defined by DVB in <<ETSI-300-468>>.

[source,xml]
----
<adaptation_field_data_descriptor adaptation_field_data_identifier="uint8, required"/>
----

==== ancillary_data_descriptor

Defined by DVB in <<ETSI-300-468>>.

[source,xml]
----
<ancillary_data_descriptor ancillary_data_identifier="uint8, required"/>
----

==== announcement_support_descriptor

Defined by DVB in <<ETSI-300-468>>.

Note that the 16-bit field named `announcement_support_indicator` is automatically built as
a bit-mask from all `announcement_type` values.

[source,xml]
----
<announcement_support_descriptor>
  <!-- One per announcement type -->
  <announcement
      announcement_type="uint4, required"
      reference_type="uint3, required"
      original_network_id="uint16, optional"
      transport_stream_id="uint16, optional"
      service_id="uint16, optional"
      component_tag="uint8, optional"/>
</announcement_support_descriptor>
----

==== application_descriptor

Defined by DVB in <<ETSI-102-809>>.
Must be in an AIT (table id 0x74).

[source,xml]
----
<application_descriptor
    service_bound="bool, required"
    visibility="uint2, required"
    application_priority="uint8, required">
  <!-- One per profile -->
  <profile
      application_profile="uint16, required"
      version="string 'major.minor.micro', required"/>
  <!-- One per transport_protocol_label -->
  <transport_protocol label="uint8, required"/>
</application_descriptor>
----

==== application_icons_descriptor

Defined by DVB in <<ETSI-102-809>>.
Must be in an AIT (table id 0x74).

[source,xml]
----
<application_icons_descriptor
    icon_locator="string, required"
    icon_flags="uint16, required">
  <reserved_future_use>
    Hexadecimal content
  </reserved_future_use>
</application_icons_descriptor>
----

==== application_name_descriptor

Defined by DVB in <<ETSI-102-809>> and <<ETSI-101-812>>.
Must be in an AIT (table id 0x74).

[source,xml]
----
<application_name_descriptor>
  <!-- One per language -->
  <language code="char3, required" application_name="string, required"/>
</application_name_descriptor>
----

==== application_recording_descriptor

Defined by DVB in <<ETSI-102-809>>.
Must be in an AIT (table id 0x74).

[source,xml]
----
<application_recording_descriptor
    scheduled_recording="bool, required"
    trick_mode_aware="bool, required"
    time_shift="bool, required"
    dynamic="bool, required"
    av_synced="bool, required"
    initiating_replay="bool, required">
  <!-- One per label -->
  <label label="string, required" storage_properties="uint2, required"/>
  <!-- One per component tag -->
  <component tag="uint8, required"/>
  <private>
    Hexadecimal content
  </private>
  <reserved_future_use>
    Hexadecimal content
  </reserved_future_use>
</application_recording_descriptor>
----

==== application_signalling_descriptor

Defined by DVB in <<ETSI-102-809>>.

[source,xml]
----
<application_signalling_descriptor>
  <!-- One per application -->
  <application application_type="uint15, required"
               AIT_version_number="uint5, required"/>
</application_signalling_descriptor>
----

==== application_storage_descriptor

Defined by DVB in <<ETSI-102-809>>.
Must be in an AIT (table id 0x74).

[source,xml]
----
<application_storage_descriptor
    storage_property="uint8, required"
    not_launchable_from_broadcast="bool, required"
    launchable_completely_from_cache="bool, required"
    is_launchable_with_older_version="bool, required"
    version="uint31, required"
    priority="uint8, required"/>
----

==== application_usage_descriptor

Defined by DVB in <<ETSI-102-809>>.
Must be in an AIT (table id 0x74).

[source,xml]
----
<application_usage_descriptor usage_type="uint8, required"/>
----

==== audio_preselection_descriptor

Defined by DVB in <<ETSI-300-468>>.

[source,xml]
----
<audio_preselection_descriptor>
  <!-- One entry per preselection, up to 31 preselections -->
  <preselection
      preselection_id="uint5, required"
      audio_rendering_indication="uint3, required"
      audio_description="bool, default=false"
      spoken_subtitles="bool, default=false"
      dialogue_enhancement="bool, default=false"
      interactivity_enabled="bool, default=false"
      ISO_639_language_code="char3, optional"
      message_id="uint8, optional">
    <multi_stream_info>
      <!-- One per auxiliary component, up to 7 components -->
      <component tag="uint8, required"/>
    </multi_stream_info>
    <future_extension>
      Hexadecimal content
    </future_extension>
  </preselection>
</audio_preselection_descriptor>
----

==== bouquet_name_descriptor

Defined by DVB in <<ETSI-300-468>>.

[source,xml]
----
<bouquet_name_descriptor bouquet_name="string, required"/>
----

==== C2_bundle_delivery_system_descriptor

Defined by DVB in <<ETSI-300-468>>.

[source,xml]
----
<C2_bundle_delivery_system_descriptor>
  <!-- One per PLP -->
  <plp plp_id="uint8, required"
       data_slice_id="uint8, required"
       C2_system_tuning_frequency="FrequencyHz, required"
       C2_system_tuning_frequency_type="uint2, required"
       active_OFDM_symbol_duration="uint3, required"
       guard_interval="1/128|1/64|uint3, required"
       master_channel="bool, required"/>
</C2_bundle_delivery_system_descriptor>
----

==== C2_delivery_system_descriptor

Defined by DVB in <<ETSI-300-468>>.

[source,xml]
----
<C2_delivery_system_descriptor
    plp_id="uint8, required"
    data_slice_id="uint8, required"
    C2_system_tuning_frequency="FrequencyHz, required"
    C2_system_tuning_frequency_type="uint2, required"
    active_OFDM_symbol_duration="uint3, required"
    guard_interval="1/128|1/64|uint3, required"/>
----

==== CA_identifier_descriptor

Defined by DVB in <<ETSI-300-468>>.

[source,xml]
----
<CA_identifier_descriptor>
  <!-- One per CAS -->
  <CA_system_id value="uint16, required"/>
</CA_identifier_descriptor>
----

==== cable_delivery_system_descriptor

Defined by DVB in <<ETSI-300-468>>.

[source,xml]
----
<cable_delivery_system_descriptor
    frequency="FrequencyHz, required"
    FEC_outer="undefined|none|RS, default=RS"
    modulation="auto|16-QAM|32-QAM|64-QAM|128-QAM|256-QAM, default=16-QAM"
    symbol_rate="SymbolsPerSecond, required"
    FEC_inner="undefined|1/2|2/3|3/4|5/6|7/8|8/9|3/5|4/5|9/10|none, required"/>
----

==== cell_frequency_link_descriptor

Defined by DVB in <<ETSI-300-468>>.

[source,xml]
----
<cell_frequency_link_descriptor>

  <!-- One per cell -->
  <cell cell_id="uint16, required" frequency="FrequencyHz, required">
    <!-- One per subcell -->
    <subcell cell_id_extension="uint8, required"
             transposer_frequency="FrequencyHz, required"/>
  </cell>

</cell_frequency_link_descriptor>
----

==== cell_list_descriptor

Defined by DVB in <<ETSI-300-468>>.

[source,xml]
----
<cell_list_descriptor>

  <!-- One per cell -->
  <cell cell_id="uint16, required"
        cell_latitude="int16, required"
        cell_longitude="int16, required"
        cell_extent_of_latitude="uint12, required"
        cell_extent_of_longitude="uint12, required">

    <!-- One per subcell -->
    <subcell cell_id_extension="uint8, required"
             subcell_latitude="int16, required"
             subcell_longitude="int16, required"
             subcell_extent_of_latitude="uint12, required"
             subcell_extent_of_longitude="uint12, required"/>
  </cell>

</cell_list_descriptor>
----

==== CI_ancillary_data_descriptor

Defined by DVB in <<ETSI-300-468>>.

[source,xml]
----
<CI_ancillary_data_descriptor>
  <ancillary_data>
    Hexadecimal content
  </ancillary_data>
</CI_ancillary_data_descriptor>
----

==== component_descriptor

Defined by DVB in <<ETSI-300-468>>.

[source,xml]
----
<component_descriptor
    stream_content="uint4, required"
    stream_content_ext="uint4, default=0xF"
    component_type="uint8, required"
    component_tag="uint8, default=0"
    language_code="char3, required"
    text="string, optional"/>
----

==== content_descriptor

Defined by DVB in <<ETSI-300-468>>.

[source,xml]
----
<content_descriptor>

  <!-- One per classification -->
  <content content_nibble_level_1="uint4, required"
           content_nibble_level_2="uint4, required"
           user_byte="uint8, required"/>

</content_descriptor>
----

==== content_identifier_descriptor

Defined by DVB in <<ETSI-102-323>>.

[source,xml]
----
<content_identifier_descriptor>

  <!-- One per CRID -->
  <crid crid_type="uint6, required"
        crid_location="uint2, required"
        crid_ref="uint16, optional"
        crid="string, optional"/>

</content_identifier_descriptor>
----

==== country_availability_descriptor

Defined by DVB in <<ETSI-300-468>>.

[source,xml]
----
<country_availability_descriptor country_availability="bool, required">

  <!-- One per country -->
  <country country_code="char3, required"/>

</country_availability_descriptor>
----

==== CP_descriptor

Defined by DVB in <<ETSI-300-468>>.

[source,xml]
----
<CP_descriptor CP_system_id="uint16, required" CP_PID="uint13, required">
  <private_data>
    Hexadecimal content
  </private_data>
</CP_descriptor>
----

==== CP_identifier_descriptor

Defined by DVB in <<ETSI-300-468>>.

[source,xml]
----
<CP_identifier_descriptor>
  <!-- One per CP system -->
  <CP_system_id value="uint16, required"/>
</CP_identifier_descriptor>
----

==== cpcm_delivery_signalling_descriptor

Defined by DVB in <<ETSI-102-825-4>> and <<ETSI-102-825-9>>.

[source,xml]
----
<cpcm_delivery_signalling_descriptor cpcm_version="uint8, required">

  <cpcm_v1_delivery_signalling
      copy_control="uint3, required"
      do_not_cpcm_scramble="bool, required"
      viewable="bool, required"
      move_local="bool, required"
      move_and_copy_propagation_information="uint2, required"
      view_propagation_information="uint2, required"
      remote_access_record_flag="bool, required"
      export_beyond_trust="bool, required"
      disable_analogue_sd_export="bool, required"
      disable_analogue_sd_consumption="bool, required"
      disable_analogue_hd_export="bool, required"
      disable_analogue_hd_consumption="bool, required"
      image_constraint="bool, required"
      view_window_start="YYYY-MM-DD hh:mm:ss, optional"
      view_window_end="YYYY-MM-DD hh:mm:ss, optional"
      view_period_from_first_playback="uint16, optional"
      simultaneous_view_count="uint8, optional"
      remote_access_delay="uint16, optional"
      remote_access_date="YYYY-MM-DD hh:mm:ss, optional">

    <cps C_and_R_regime_mask="uint8, required">
      Hexadecimal Content
    </cps>

  </cpcm_v1_delivery_signalling>

</cpcm_delivery_signalling_descriptor>
----

==== data_broadcast_descriptor

Defined by DVB in <<ETSI-300-468>>.

[source,xml]
----
<data_broadcast_descriptor
    data_broadcast_id="uint16, required"
    component_tag="uint8, required"
    language_code="char3, required">
  <selector_bytes>Hexadecimal content</selector_bytes>
  <text>String</text>
</data_broadcast_descriptor>
----

==== data_broadcast_id_descriptor

Defined by DVB in <<ETSI-300-468>>.

[source,xml]
----
<data_broadcast_id_descriptor data_broadcast_id="uint16, required">
  <selector_bytes>Hexadecimal content</selector_bytes>
</data_broadcast_id_descriptor>
----

==== default_authority_descriptor

Defined by DVB in <<ETSI-102-323>>.

[source,xml]
----
<default_authority_descriptor fqdn="string, required"/>
----

==== DII_location_descriptor

Defined by DVB in <<ETSI-101-812>>.
Must be in an AIT (table id 0x74).

[source,xml]
----
<DII_location_descriptor transport_protocol_label="uint8, required">
  <!-- One per module -->
  <module DII_identification="uint15, required" association_tag="uint16, required"/>
</DII_location_descriptor>
----

==== DSNG_descriptor

Defined by DVB in <<ETSI-300-468>> and <<ETSI-301-210>>.

[source,xml]
----
<DSNG_descriptor station_identification="string, required"/>
----

==== DTS_descriptor

Defined by DVB in <<ETSI-300-468>>.

[source,xml]
----
<DTS_descriptor
    sample_rate_code="uint4, required"
    bit_rate_code="uint6, required"
    nblks="uint7, 0x05 to 0x1F, required"
    fsize="uint14, 0x005F to 0x2000, required"
    surround_mode="uint6, required"
    lfe="bool, default=false"
    extended_surround="uint2, default=0">
  <additional_info>
    Hexadecimal content
  </additional_info>
</DTS_descriptor>
----

==== DTS_HD_descriptor

Defined by DVB in <<ETSI-300-468>>.

[source,xml]
----
<DTS_HD_descriptor>

  <!-- Each substructure is optional and may appear at most once -->

  <substream_core
      channel_count="uint5, required"
      LFE="bool, required"
      sampling_frequency="uint4, required"
      sample_resolution="bool, required">
    <!-- From 1 to 8 asset_info -->
    <asset_info
        asset_construction="uint5, required"
        vbr="bool, required"
        post_encode_br_scaling="bool, required"
        bit_rate="uint13, required"
        component_type="uint8, optional"
        ISO_639_language_code="char3, optional"/>
  </substream_core>

  <substream_0
      channel_count="uint5, required"
      LFE="bool, required"
      sampling_frequency="uint4, required"
      sample_resolution="bool, required">
    <!-- From 1 to 8 asset_info -->
    <asset_info
        asset_construction="uint5, required"
        vbr="bool, required"
        post_encode_br_scaling="bool, required"
        bit_rate="uint13, required"
        component_type="uint8, optional"
        ISO_639_language_code="char3, optional"/>
  </substream_0>

  <substream_1
      channel_count="uint5, required"
      LFE="bool, required"
      sampling_frequency="uint4, required"
      sample_resolution="bool, required">
    <!-- From 1 to 8 asset_info -->
    <asset_info
        asset_construction="uint5, required"
        vbr="bool, required"
        post_encode_br_scaling="bool, required"
        bit_rate="uint13, required"
        component_type="uint8, optional"
        ISO_639_language_code="char3, optional"/>
  </substream_1>

  <substream_2
      channel_count="uint5, required"
      LFE="bool, required"
      sampling_frequency="uint4, required"
      sample_resolution="bool, required">
    <!-- From 1 to 8 asset_info -->
    <asset_info
        asset_construction="uint5, required"
        vbr="bool, required"
        post_encode_br_scaling="bool, required"
        bit_rate="uint13, required"
        component_type="uint8, optional"
        ISO_639_language_code="char3, optional"/>
  </substream_2>

  <substream_3
      channel_count="uint5, required"
      LFE="bool, required"
      sampling_frequency="uint4, required"
      sample_resolution="bool, required">
    <!-- From 1 to 8 asset_info -->
    <asset_info
        asset_construction="uint5, required"
        vbr="bool, required"
        post_encode_br_scaling="bool, required"
        bit_rate="uint13, required"
        component_type="uint8, optional"
        ISO_639_language_code="char3, optional"/>
  </substream_3>

  <additional_info>
    Hexadecimal content
  </additional_info>

</DTS_HD_descriptor>
----

==== DTS_neural_descriptor

Defined by DVB in <<ETSI-300-468>>.

[source,xml]
----
<DTS_neural_descriptor config_id="uint8, required">
  <additional_info>
    Hexadecimal content
  </additional_info>
</DTS_neural_descriptor>
----

==== DTS_UHD_descriptor

Defined by DVB in <<ETSI-300-468>>.

[source,xml]
----
<DTS_UHD_descriptor
    DecoderProfileCode="uint6, required"
    FrameDurationCode="uint2, required"
    MaxPayloadCode="uint2, required"
    StreamIndex="uint3, required">

  <codec_selector>
    Hexadecimal Content
  </codec_selector>

</DTS_UHD_descriptor>
----

==== dvb_html_application_boundary_descriptor

Defined by DVB in <<ETSI-101-812>>.
Must be in an AIT (table id 0x74).

[source,xml]
----
<dvb_html_application_boundary_descriptor
    label="string, required"
    regular_expression="string, required"/>
----

==== dvb_html_application_descriptor

Defined by DVB in <<ETSI-101-812>>.
Must be in an AIT (table id 0x74).

[source,xml]
----
<dvb_html_application_descriptor parameter="string, optional">
  <!-- One per application id: -->
  <application id="uint16, required"/>
</dvb_html_application_descriptor>
----

==== dvb_html_application_location_descriptor

Defined by DVB in <<ETSI-101-812>>.
Must be in an AIT (table id 0x74).

[source,xml]
----
<dvb_html_application_location_descriptor
    physical_root="string, required"
    initial_path="string, required"/>
----

==== dvb_j_application_descriptor

Defined by DVB in <<ETSI-101-812>>.
Must be in an AIT (table id 0x74).

[source,xml]
----
<dvb_j_application_descriptor>
  <!-- One per parameter: -->
  <parameter value="string, required"/>
</dvb_j_application_descriptor>
----

==== dvb_j_application_location_descriptor

Defined by DVB in <<ETSI-101-812>>.
Must be in an AIT (table id 0x74).

[source,xml]
----
<dvb_j_application_location_descriptor
    base_directory="string, required"
    classpath_extension="string, required"
    initial_class="string, required"/>
----

==== ECM_repetition_rate_descriptor

Defined by DVB in <<ETSI-301-192>>.

[source,xml]
----
<ECM_repetition_rate_descriptor
    CA_system_id="uint16, required"
    ECM_repetition_rate="uint16, required">
  <private_data>
    Hexadecimal content
  </private_data>
</ECM_repetition_rate_descriptor>
----

==== enhanced_AC3_descriptor

Defined by DVB in <<ETSI-300-468>>.

Because of the presence of an ATSC version of the `enhanced_AC3_descriptor`,
the XML name for the DVB version is `<DVB_enhanced_AC3_descriptor>`.
For compatibility, the previous `<enhanced_AC3_descriptor>` is still accepted.

[source,xml]
----
<DVB_enhanced_AC3_descriptor
    mixinfoexists="bool, required"
    component_type="uint8, optional"
    bsid="uint8, optional"
    mainid="uint8, optional"
    asvc="uint8, optional"
    substream1="uint8, optional"
    substream2="uint8, optional"
    substream3="uint8, optional">
  <additional_info>
    Hexadecimal content
  </additional_info>
</DVB_enhanced_AC3_descriptor>
----

==== extended_event_descriptor

Defined by DVB in <<ETSI-300-468>>.

[source,xml]
----
<extended_event_descriptor
    descriptor_number="uint8, required"
    last_descriptor_number="uint8, required"
    language_code="char3, required">
  <text>String</text>
  <!-- One per item -->
  <item>
    <description>String</description>
    <name>String</name>
  </item>
</extended_event_descriptor>
----

==== external_application_authorization_descriptor

Defined by DVB in <<ETSI-102-809>>.
Must be in an AIT (table id 0x74).

[source,xml]
----
<external_application_authorization_descriptor>
  <!-- One per application -->
  <application
      organization_id="uint32, required"
      application_id="uint16, required"
      application_priority="uint8, required"/>
</external_application_authorization_descriptor>
----

==== frequency_list_descriptor

Defined by DVB in <<ETSI-300-468>>.

[source,xml]
----
<frequency_list_descriptor
    coding_type="undefined|satellite|cable|terrestrial|uint2, required">

  <!-- List of frequencies, one element per frequency -->
  <centre_frequency value="FrequencyHz, required"/>

</frequency_list_descriptor>
----

==== FTA_content_management_descriptor

Defined by DVB in <<ETSI-300-468>>.

[source,xml]
----
<FTA_content_management_descriptor
    user_defined="bool, required"
    do_not_scramble="bool, required"
    control_remote_access_over_internet="uint2, required"
    do_not_apply_revocation="bool, required"/>
----

==== graphics_constraints_descriptor

Defined by DVB in <<ETSI-102-809>>.
Must be in an AIT (table id 0x74).

[source,xml]
----
<graphics_constraints_descriptor
    can_run_without_visible_ui="bool, required"
    handles_configuration_changed="bool, required"
    handles_externally_controlled_video="bool, required">

  <graphics_configuration>
    Hexadecimal content
  </graphics_configuration>

</graphics_constraints_descriptor>
----

==== image_icon_descriptor

Defined by DVB in <<ETSI-300-468>>.

[source,xml]
----
<image_icon_descriptor
    descriptor_number="uint4, required"
    last_descriptor_number="uint4, required"
    icon_id="uint3, required"
    icon_transport_mode="uint2, optional"
    coordinate_system="uint3, optional"
    icon_horizontal_origin="uint12, optional"
    icon_vertical_origin="uint12, optional"
    icon_type="string, optional"
    url="string, optional">

  <icon_data>
    Hexadecimal content
  </icon_data>

</image_icon_descriptor>
----

==== IPMAC_generic_stream_location_descriptor

Defined by DVB in <<ETSI-301-192>>.
Must be in an INT (table id 0x4C).

[source,xml]
----
<IPMAC_generic_stream_location_descriptor
    interactive_network_id="uint16, required"
    modulation_system_type="DVB-S2|DVB-T2|DVB-C2|DVB-NGH|uint8, required"
    modulation_system_id="uint16, default=0"
    PHY_stream_id="uint16, default=0">
  <selector_bytes>Hexadecimal content</selector_bytes>
</IPMAC_generic_stream_location_descriptor>
----

==== IPMAC_platform_name_descriptor

Defined by DVB in <<ETSI-301-192>>.
Must be in an INT (table id 0x4C).

[source,xml]
----
<IPMAC_platform_name_descriptor
    language_code="char3, required"
    text="string, required"/>
----

==== IPMAC_platform_provider_name_descriptor

Defined by DVB in <<ETSI-301-192>>.
Must be in an INT (table id 0x4C).

[source,xml]
----
<IPMAC_platform_provider_name_descriptor
    language_code="char3, required"
    text="string, required"/>
----

==== IPMAC_stream_location_descriptor

Defined by DVB in <<ETSI-301-192>>.
Must be in an INT (table id 0x4C).

[source,xml]
----
<IPMAC_stream_location_descriptor
    network_id="uint16, required"
    original_network_id="uint16, required"
    transport_stream_id="uint16, required"
    service_id="uint16, required"
    component_tag="uint8, required"/>
----

==== ip_signalling_descriptor

Defined by DVB in <<ETSI-101-812>>.
Must be in an INT (table id 0x4C).

[source,xml]
----
<ip_signalling_descriptor platform_id="uint24, required"/>
----

==== ISP_access_mode_descriptor

Defined by DVB in <<ETSI-301-192>>.
Must be in an INT (table id 0x4C).

[source,xml]
----
<ISP_access_mode_descriptor access_mode="unused|dialup|uint8, required"/>
----

==== linkage_descriptor

Defined by DVB in <<ETSI-300-468>>.

[source,xml]
----
<linkage_descriptor
    transport_stream_id="uint16, required"
    original_network_id="uint16, required"
    service_id="uint16, required"
    linkage_type="uint8, required">
  <!-- if linkage_type == 0x08 -->
  <mobile_handover_info
      handover_type="uint4, required"
      origin_type="NIT|SDT, required"
      network_id="uint16, required if hand-over_type is 0x01, 0x02, 0x03"
      initial_service_id="uint16, required if origin_type is NIT"/>
  <!-- else if linkage_type == 0x0D -->
  <event_linkage_info
      target_event_id="uint16, required"
      target_listed="bool, required"
      event_simulcast="bool, required"/>
  <!-- else if linkage_type >= 0x0E && linkage_type <= 0x1F -->
  <extended_event_linkage_info>	
    <!-- For each event -->
    <event	
        target_event_id="uint16, required"
        target_listed="bool, required"
        event_simulcast="bool, required"
        link_type="uint2, required"
        target_id_type="uint2, required"
        user_defined_id="uint16, required if target_id_type == 3"
        target_transport_stream_id="uint16, required if target_id_type == 1"
        target_original_network_id="uint16, optional"
        target_service_id="uint16, optional"/>
  </extended_event_linkage_info>
  <private_data>
    Hexadecimal content
  </private_data>
</linkage_descriptor>
----

==== local_time_offset_descriptor

Defined by DVB in <<ETSI-300-468>>.

[source,xml]
----
<local_time_offset_descriptor>
  <!-- One per region -->
  <region country_code="char3, required"
          country_region_id="uint6, required"
          local_time_offset="int, required"
          time_of_change="YYYY-MM-DD hh:mm:ss, required"
          next_time_offset="int, required"/>
  <!-- local_time_offset and next_time_offset: -->
  <!-- -780 to +780 minutes (-13 to +13 hours) -->
</local_time_offset_descriptor>
----

==== message_descriptor

Defined by DVB in <<ETSI-300-468>>.

[source,xml]
----
<message_descriptor message_id="uint8, required" language_code="char3, required">
  <text>String</text>
</message_descriptor>
----

==== mosaic_descriptor

Defined by DVB in <<ETSI-300-468>>.

[source,xml]
----
<mosaic_descriptor
    mosaic_entry_point="bool, required"
    number_of_horizontal_elementary_cells="uint3, required"
    number_of_vertical_elementary_cells="uint3, required">

  <!-- One per cell in the mosaic -->
  <cell logical_cell_id="uint6, required"
        logical_cell_presentation_info="uint3, required"
        cell_linkage_info="uint8, required"
        bouquet_id="uint16, optional"
        original_network_id="uint16, optional"
        transport_stream_id="uint16, optional"
        service_id="uint16, optional"
        event_id="uint16, optional">

    <!-- One per elementary cell -->
    <elementary_cell id="uint6, required"/>

  </cell>

</mosaic_descriptor>
----

==== multilingual_bouquet_name_descriptor

Defined by DVB in <<ETSI-300-468>>.

[source,xml]
----
<multilingual_bouquet_name_descriptor>
  <!-- One per language -->
  <language code="char3, required" bouquet_name="string, required"/>
</multilingual_bouquet_name_descriptor>
----

==== multilingual_component_descriptor

Defined by DVB in <<ETSI-300-468>>.

[source,xml]
----
<multilingual_component_descriptor component_tag="uint8, required">
  <!-- One per language -->
  <language code="char3, required" description="string, required"/>
</multilingual_component_descriptor>
----

==== multilingual_network_name_descriptor

Defined by DVB in <<ETSI-300-468>>.

[source,xml]
----
<multilingual_network_name_descriptor>
  <!-- One per language -->
  <language code="char3, required" network_name="string, required"/>
</multilingual_network_name_descriptor>
----

==== multilingual_service_name_descriptor

Defined by DVB in <<ETSI-300-468>>.

[source,xml]
----
<multilingual_service_name_descriptor>
  <!-- One per language -->
  <language code="char3, required"
            service_provider_name="string, required"
            service_name="string, required"/>
</multilingual_service_name_descriptor>
----

==== network_change_notify_descriptor

Defined by DVB in <<ETSI-300-468>>.

[source,xml]
----
<network_change_notify_descriptor>
  <!-- One per cell -->
  <cell cell_id="uint16, required">
    <!-- One per network change -->
    <change network_change_id="uint8, required"
            network_change_version="uint8, required"
            start_time_of_change="YYYY-MM-DD hh:mm:ss, required"
            change_duration="hh:mm:ss, required"
            receiver_category="uint3, required"
            change_type="uint4, required"
            message_id="uint8, required"
            invariant_ts_tsid="uint16, optional"
            invariant_ts_onid="uint16, optional"/>
  </cell>
</network_change_notify_descriptor>
----

==== network_name_descriptor

Defined by DVB in <<ETSI-300-468>>.

[source,xml]
----
<network_name_descriptor network_name="string, required"/>
----

==== NVOD_reference_descriptor

Defined by DVB in <<ETSI-300-468>>.

[source,xml]
----
<NVOD_reference_descriptor>
  <!-- One per service -->
  <service transport_stream_id="uint16, required"
           original_network_id="uint16, required"
           service_id="uint16, required"/>
</NVOD_reference_descriptor>
----

==== parental_rating_descriptor

Defined by DVB in <<ETSI-300-468>>.

[source,xml]
----
<parental_rating_descriptor>
  <!-- One per country -->
  <country country_code="char3, required" rating="uint8, required"/>
</parental_rating_descriptor>
----

==== partial_transport_stream_descriptor

Defined by DVB in <<ETSI-300-468>>.

[source,xml]
----
<partial_transport_stream_descriptor
    peak_rate="uint22, required"
    minimum_overall_smoothing_rate="uint22, default=0x3FFFFF"
    maximum_overall_smoothing_buffer="uint14, default=0x3FFF"/>
----

==== PDC_descriptor

Defined by DVB in <<ETSI-300-468>>.

[source,xml]
----
<PDC_descriptor programme_identification_label="MM-DD hh:mm, required"/>
----

==== prefetch_descriptor

Defined by DVB in <<ETSI-101-812>>.
Must be in an AIT (table id 0x74).

[source,xml]
----
<prefetch_descriptor transport_protocol_label="uint8, required">
  <!-- One per module -->
  <module label="string, required" prefetch_priority="int, 1 to 100, required"/>
</prefetch_descriptor>
----

==== private_data_specifier_descriptor

Defined by DVB in <<ETSI-300-468>>.

[source,xml]
----
<private_data_specifier_descriptor private_data_specifier="uint32|name, required"/>
----

The value of the attribute is either a 32-bit private data specifier value or
a predefined name as used in option `--default-pds`.
See xref:opt-default-std[xrefstyle=short] for more details.

==== protection_message_descriptor

Defined by DVB in <<ETSI-102-809>>.

[source,xml]
----
<protection_message_descriptor>
  <!-- One per component, up to 15 components -->
  <component tag="uint8, required"/>
</protection_message_descriptor>
----

==== RAR_over_DVB_stream_descriptor

Defined by DVB in <<ETSI-102-323>>.
Must be in a RNT (table id 0x79).

[source,xml]
----
<RAR_over_DVB_stream_descriptor
  first_valid_date="YYYY-MM-DD hh:mm:ss, required"
  last_valid_date="YYYY-MM-DD hh:mm:ss, required"
  weighting="uint6, required"
  complete_flag="bool, required"
  transport_stream_id="uint16, required"
  original_network_id="uint16, required"
  service_id="uint16, required"
  component_tag="uint8, required"
  download_start_time="YYYY-MM-DD hh:mm:ss,
      optional group with download_period_duration and download_cycle_time"
  download_period_duration="uint8,
      optional group with download_start_time and download_cycle_time"
  download_cycle_time="uint8,
      optional group with download_start_time and download_period_duration"/>
----

==== RAR_over_IP_descriptor

Defined by DVB in <<ETSI-102-323>>.
Must be in a RNT (table id 0x79).

[source,xml]
----
<RAR_over_IP_descriptor
  first_valid_date="YYYY-MM-DD hh:mm:ss, required"
  last_valid_date="YYYY-MM-DD hh:mm:ss, required"
  weighting="uint6, required"
  complete_flag="bool, required"
  url="string, required"/>
----

==== related_content_descriptor

Defined by DVB in <<ETSI-102-323>>.

[source,xml]
----
<related_content_descriptor/>
----

==== RNT_scan_descriptor	

Defined by DVB in <<ETSI-102-323>>.
Must be in a RNT (table id 0x79).

[source,xml]
----
<RNT_scan_descriptor>

  <RNT_reference
    transport_stream_id="uint16, required"
    original_network_id="uint16, required"
    scan_weighting="uint8, required"/>

</RNT_scan_descriptor>
----

==== S2_satellite_delivery_system_descriptor

Defined by DVB in <<ETSI-300-468>>.

[source,xml]
----
<S2_satellite_delivery_system_descriptor
    backwards_compatibility="bool, default=false"
    TS_GS_mode="uint2, default=3"
    scrambling_sequence_index="uint18, optional"
    input_stream_identifier="uint8, optional"
    timeslice_number="uint8, optional"/>
----

==== S2X_satellite_delivery_system_descriptor

Defined by DVB in <<ETSI-300-468>>.

[source,xml]
----
<S2X_satellite_delivery_system_descriptor
    receiver_profiles="uint5, required"
    S2X_mode="uint2, required"
    TS_GS_S2X_mode="uint2, required"
    scrambling_sequence_index="uint18, optional"
    timeslice_number="uint8, required for S2X_mode==2">

  <!-- Master channel is required -->
  <master_channel
      frequency="SatelliteFrequencyHz, required"
      orbital_position="SatelliteOrbitalPosition, eg. 19.2, required"
      west_east_flag="east|west, required"
      polarization="horizontal|vertical|left|right, required"
      roll_off="0.35|0.25|0.20|0.15|0.10|0.05|uint3, required"
      symbol_rate="SatelliteSymbolRate, required"
      input_stream_identifier="uint8, optional"/>

  <!-- When S2X_mode==3, there must be exactly 1 or 2 channel_bond -->
  <channel_bond
      frequency="SatelliteFrequencyHz, required"
      orbital_position="SatelliteOrbitalPosition, eg. 19.2, required"
      west_east_flag="east|west, required"
      polarization="horizontal|vertical|left|right, required"
      roll_off="0.35|0.25|0.20|0.15|0.10|0.05|uint3, required"
      symbol_rate="SatelliteSymbolRate, required"
      input_stream_identifier="uint8, optional"/>

  <reserved_future_use>
    Hexadecimal content
  </reserved_future_use>

</S2X_satellite_delivery_system_descriptor>
----

==== S2Xv2_satellite_delivery_system_descriptor

Defined by DVB in <<ETSI-300-468>>.

[source,xml]
----
<S2Xv2_satellite_delivery_system_descriptor
    delivery_system_id="uint32, required"
    S2Xv2_mode="1|2|4|5|uint4, required"
    roll_off="0.35|0.25|0.20|0.15|0.10|0.05|uint3, required"
    NCR_reference="uint1, required"
    NCR_version="uint1, required"
    channel_bond="uint2, required"
    polarization="horizontal|vertical|left|right, required"
    TS_GS_S2X_mode="uint2, required"
    receiver_profiles="uint5, required"
    satellite_id="uint24, required"
    frequency="SatelliteFrequencyHz, required"
    symbol_rate="SatelliteSymbolRate, required"
    input_stream_identifier="uint8, optional"
    scrambling_sequence_index="uint18, required for S2Xv2_mode==2 or S2Xv2_mode==5"
    timeslice_number="uint8, required for S2Xv2_mode==2 or S2Xv2_mode==5">

  <!-- one or two secondary delivery systems to be included if channel_bond==1 -->
  <secondary_delivery_system
      id="uint32, required"/>

  <!-- required if S2Xv2_mode==4 or S2Xv2_mode==5 -->
  <superframe
      SOSF_WH_sequence_number="uint8, required"
      reference_scrambling_index="uint20, required"
      SFFI="uint4, optional"
      payload_scrambling_index="uint20, required"
      beamhopping_time_plan_id="uint32, optional"
      superframe_pilots_WH_sequence_number="uint5, required"
      postamble_PLI="uint3, required"/>

  <reserved_future_use>
    Hexadecimal content
  </reserved_future_use>

</S2Xv2_satellite_delivery_system_descriptor>
----

[#sat-del-desc]
==== satellite_delivery_system_descriptor

Defined by DVB in <<ETSI-300-468>>.
Redefined in a slightly different way by ARIB (ISDB) in <<ARIB-B10>>.

When this descriptor is extracted from a binary stream to be decompiled in XML format,
there is no way to check if this is a DVB or ISDB descriptor without knowing the context.
If the command line specifies an option such as `--isdb` or `--japan`,
or if an ISDB-specific table was previously encountered,
then the stream is assumed to be an ISDB one and the ISDB format of this descriptor is used.
Otherwise, the original DVB format is assumed.

[source,xml]
----
<satellite_delivery_system_descriptor
    frequency="SatelliteFrequencyHz, required"
    orbital_position="SatelliteOrbitalPosition, eg. 19.2, required"
    west_east_flag="east|west, required"
    polarization="horizontal|vertical|left|right, required"
    roll_off="0.35|0.25|0.20|reserved, default=0.35"
    modulation_system="DVB-S|DVB-S2|ISDB-S, required"
    modulation_type="auto|QPSK|8PSK|16-QAM|ISDB-S|2.6GHzMobile|AdvancedCS,
                     default=QPSK|ISDB-S"
    symbol_rate="SymbolsPerSecond, required"
    FEC_inner="undefined|1/2|2/3|3/4|5/6|7/8|8/9|3/5|4/5|9/10|
               ISDB-S|2.6GHzMobile|AdvancedCS|none, required"/>
----

The attribute `roll_off` is used only when `modulation_system` is `DVB-S2`.

The list of allowed values for `modulation_type` and `FEC_inner` depends on the value of `modulation_system`.

==== scheduling_descriptor

Defined by DVB in <<ETSI-102-006>>.
Must be in a UNT (table id 0x4B).

[source,xml]
----
<scheduling_descriptor
    start_date_time="YYYY-MM-DD hh:mm:ss, required"
    end_date_time="YYYY-MM-DD hh:mm:ss, required"
    final_availability="bool, required"
    periodicity="bool, required"
    period_unit="second|minute|hour|day|uint2, required"
    duration_unit="second|minute|hour|day|uint2, required"
    estimated_cycle_time_unit="second|minute|hour|day|uint2, required"
    period="uint8, required"
    duration="uint8, required"
    estimated_cycle_time="uint8, required">

  <private_data>
    Hexadecimal content
  </private_data>

</scheduling_descriptor>
----

==== scrambling_descriptor

Defined by DVB in <<ETSI-300-468>>.

[source,xml]
----
<scrambling_descriptor scrambling_mode="uint8, required"/>
----

==== service_descriptor

Defined by DVB in <<ETSI-300-468>>.

[source,xml]
----
<service_descriptor
    service_type="uint8, required"
    service_provider_name="string, required"
    service_name="string, required"/>
----

==== service_availability_descriptor

Defined by DVB in <<ETSI-300-468>>.

[source,xml]
----
<service_availability_descriptor availability="bool, required">
  <!-- One per cell -->
  <cell id="uint16, required"/>
</service_availability_descriptor>
----

==== service_identifier_descriptor

Defined by DVB in <<ETSI-300-468>>.

[source,xml]
----
<service_identifier_descriptor service_identifier="string, required"/>
----

==== service_list_descriptor

Defined by DVB in <<ETSI-300-468>>.

[source,xml]
----
<service_list_descriptor>
  <!-- One per service -->
  <service service_id="uint16, required" service_type="uint8, required"/>
</service_list_descriptor>
----

==== service_move_descriptor

Defined by DVB in <<ETSI-300-468>>.

[source,xml]
----
<service_move_descriptor
    new_original_network_id="uint16, required"
    new_transport_stream_id="uint16, required"
    new_service_id="uint16, required"/>
----

==== service_prominence_descriptor

Defined by DVB in <<ETSI-300-468>>.

[source,xml]
----
<service_prominence_descriptor>

  <sogi
      SOGI_flag="bool, required"
      SOGI_priority="uint12, required"
      service_id="uint16, optional">

    <target_region
        country_code="string, optional"
        primary_region_code="uint8, optional"
        secondary_region_code="uint8, optional"
        tertiary_region_code="uint8, optional"/>

  </sogi>

  <private_data>
    Hexadecimal Content
  </private_data>

</service_prominence_descriptor>
----

==== service_relocated_descriptor

Defined by DVB in <<ETSI-300-468>>.

[source,xml]
----
<service_relocated_descriptor
    old_original_network_id="uint16, required"
    old_transport_stream_id="uint16, required"
    old_service_id="uint16, required"/>
----

==== SH_delivery_system_descriptor

Defined by DVB in <<ETSI-300-468>>.

[source,xml]
----
<SH_delivery_system_descriptor diversity_mode="uint4, required">

  <!-- Number of modulations depends on the SH config, e.g. 1 in SFN, 2 in non-SFN -->
  <modulation>

    <!-- Modulation type: exactly one of TDM or OFDM must be present -->
    <TDM
        polarization="horizontal|vertical|left|right, required"
        roll_off="0.35|0.25|0.15|reserved, required"
        modulation_mode="QPSK|8PSK|16APSK|reserved, required"
        code_rate="uint4, required"
        symbol_rate="uint5, required"/>
    <OFDM
        bandwidth="8MHz|7MHz|6MHz|5MHz|1.7MHz|uint3, required"
        priority="uint1, required"
        constellation_and_hierarchy="uint3, required"
        code_rate="uint4, required"
        guard_interval="1/32|1/16|1/8|1/4|uint2, required"
        transmission_mode="1k|2k|4k|8k|uint2, required"
        common_frequency="bool, required"/>

    <!-- At most one interleaver, optional fields must be all absent or all present -->
    <interleaver
        common_multiplier="uint6, required"
        nof_late_taps="uint6, optional"
        nof_slices="uint6, optional"
        slice_distance="uint8, optional"
        non_late_increments="uint6, optional"/>
  </modulation>

</SH_delivery_system_descriptor>
----

==== short_event_descriptor

Defined by DVB in <<ETSI-300-468>>.

[source,xml]
----
<short_event_descriptor language_code="char3, required">
  <event_name>String</event_name>
  <text>String</text>
</short_event_descriptor>
----

==== short_smoothing_buffer_descriptor

Defined by DVB in <<ETSI-300-468>>.

[source,xml]
----
<short_smoothing_buffer_descriptor
    sb_size="uint2, required"
    sb_leak_rate="uint6, required">

  Hexadecimal content (optional DVB-reserved data)

</short_smoothing_buffer_descriptor>
----

==== simple_application_boundary_descriptor

Defined by DVB in <<ETSI-102-809>>.
Must be in an AIT (table id 0x74).

[source,xml]
----
<simple_application_boundary_descriptor>
  <!-- One per prefix: -->
  <prefix boundary_extension="string, required"/>
</simple_application_boundary_descriptor>
----

==== simple_application_location_descriptor

Defined by DVB in <<ETSI-102-809>>.
Must be in an AIT (table id 0x74).

[source,xml]
----
<simple_application_location_descriptor initial_path="string, required"/>
----

==== SSU_enhanced_message_descriptor

Defined by DVB in <<ETSI-102-006>>.
Must be in a UNT (table id 0x4B).

[source,xml]
----
<SSU_enhanced_message_descriptor
    descriptor_number="uint4, required"
    last_descriptor_number="uint4, required"
    ISO_639_language_code="char3, required"
    message_index="uint5, required">

  <text>String</text>

</SSU_enhanced_message_descriptor>
----

==== SSU_event_name_descriptor

Defined by DVB in <<ETSI-102-006>>.
Must be in a UNT (table id 0x4B).

[source,xml]
----
<SSU_event_name_descriptor ISO_639_language_code="char3, required"
  <name>String</name>
  <text>String</text>
</SSU_event_name_descriptor>
----

==== SSU_location_descriptor

Defined by DVB in <<ETSI-102-006>>.
Must be in a UNT (table id 0x4B).

[source,xml]
----
<SSU_location_descriptor
    data_broadcast_id="uint16, required"
    association_tag="uint16, optional">

  <private_data>
    Hexadecimal content
  </private_data>

</SSU_location_descriptor>
----

==== SSU_message_descriptor

Defined by DVB in <<ETSI-102-006>>.
Must be in a UNT (table id 0x4B).

[source,xml]
----
<SSU_message_descriptor
    descriptor_number="uint4, required"
    last_descriptor_number="uint4, required"
    ISO_639_language_code="char3, required">

  <text>String</text>

</SSU_message_descriptor>
----

==== SSU_subgroup_association_descriptor

Defined by DVB in <<ETSI-102-006>>.
Must be in a UNT (table id 0x4B).

[source,xml]
----
<SSU_subgroup_association_descriptor subgroup_tag="uint40, required"/>
----

==== SSU_uri_descriptor

Defined by DVB in <<ETSI-102-006>>.
Must be in a UNT (table id 0x4B).

[source,xml]
----
<SSU_uri_descriptor
    max_holdoff_time="uint8, required"
    min_polling_interval="uint8, required"
    uri="string, required"/>
----

Warning: As defined in <<ETSI-102-006>>,
`max_holdoff_time` is a number of minutes and `min_polling_interval` is a number of hours.

==== stream_identifier_descriptor

Defined by DVB in <<ETSI-300-468>>.

[source,xml]
----
<stream_identifier_descriptor component_tag="uint8, required"/>
----

==== stuffing_descriptor

Defined by DVB in <<ETSI-300-468>>.

Because of the presence of an ATSC version of the `stuffing_descriptor`,
the XML name for the DVB version is `<DVB_stuffing_descriptor>`.
For compatibility, `<stuffing_descriptor>` is still accepted.

[source,xml]
----
<DVB_stuffing_descriptor>
  Hexadecimal content
</DVB_stuffing_descriptor>
----

==== subtitling_descriptor

Defined by DVB in <<ETSI-300-468>>.

[source,xml]
----
<subtitling_descriptor>
  <!-- One per subtitle -->
  <subtitling language_code="char3, required"
              subtitling_type="uint8, required"
              composition_page_id="uint16, required"
              ancillary_page_id="uint16, required"/>
</subtitling_descriptor>
----

==== supplementary_audio_descriptor

Defined by DVB in <<ETSI-300-468>>.

[source,xml]
----
<supplementary_audio_descriptor
    mix_type="uint1, required"
    editorial_classification="uint5, required"
    language_code="char3, optional">
  <private_data>
    Hexadecimal content
  </private_data>
</supplementary_audio_descriptor>
----

==== T2_delivery_system_descriptor

Defined by DVB in <<ETSI-300-468>>.

[source,xml]
----
<T2_delivery_system_descriptor
    plp_id="uint8, required"
    T2_system_id="uint16, required">

  <!-- Optional extension -->
  <extension
      SISO_MISO="SISO|MISO|uint2, required"
      bandwidth="8MHz|7MHz|6MHz|5MHz|10MHz|1.712MHz|uint4, required"
      guard_interval="1/32|1/16|1/8|1/4|1/128|19/128|19/256|uint3, required"
      transmission_mode="2k|8k|4k|1k|16k|32k|uint3, required"
      other_frequency="bool, required"
      tfs="bool, required">

    <!-- One per cell -->
    <cell cell_id="uint16, required">
      <!-- Only one if tfs is false, any number if tfs is true -->
      <centre_frequency value="FrequencyHz, required"/>
      <!-- One per subcell -->
      <subcell cell_id_extension="uint8, required"
               transposer_frequency="FrequencyHz, required"/>
    </cell>

  </extension>

</T2_delivery_system_descriptor>
----

==== T2MI_descriptor

Defined by DVB in <<ETSI-300-468>>.

[source,xml]
----
<T2MI_descriptor
    t2mi_stream_id="uint3, required"
    num_t2mi_streams_minus_one="uint3, default=0"
    pcr_iscr_common_clock_flag="bool, default=false">
  <reserved>
    Hexadecimal content
  </reserved>
</T2MI_descriptor>
----

==== target_IP_address_descriptor

Defined by DVB in <<ETSI-301-192>> and <<ETSI-102-006>>.
Must be in a UNT (table id 0x4B) or INT (table id 0x4C).

[source,xml]
----
<target_IP_address_descriptor IPv4_addr_mask="IPv4 address, required">
  <!-- One per IPv4 address: -->
  <address IPv4_addr="IPv4 address, required"/>
</target_IP_address_descriptor>	
----

==== target_IP_slash_descriptor

Defined by DVB in <<ETSI-301-192>>.
Must be in an INT (table id 0x4C).

[source,xml]
----
<target_IP_slash_descriptor>
  <!-- One per IPv4 address: -->	
  <address
      IPv4_addr="IPv4 address, required"
      IPv4_slash_mask="uint8, required"/>
</target_IP_slash_descriptor>
----

==== target_IP_source_slash_descriptor

Defined by DVB in <<ETSI-301-192>>.
Must be in an INT (table id 0x4C).

[source,xml]
----
<target_IP_source_slash_descriptor>
  <!-- One per pair of IPv4 address: -->
  <address
      IPv4_source_addr="IPv4 address, required"
      IPv4_source_slash_mask="uint8, required"
      IPv4_dest_addr="IPv4 address, required"
      IPv4_dest_slash_mask="uint8, required"/>
</target_IP_source_slash_descriptor>
----

==== target_IPv6_address_descriptor

Defined by DVB in <<ETSI-301-192>> and <<ETSI-102-006>>.
Must be in a UNT (table id 0x4B) or INT (table id 0x4C).

[source,xml]
----
<target_IPv6_address_descriptor IPv6_addr_mask="IPv6 address, required">
  <!-- One per IPv6 address: -->
  <address IPv6_addr="IPv6 address, required"/>
</target_IPv6_address_descriptor>
----

==== target_IPv6_slash_descriptor

Defined by DVB in <<ETSI-301-192>>.
Must be in an INT (table id 0x4C).

[source,xml]
----
<target_IPv6_slash_descriptor>
  <!-- One per IPv6 address: -->
  <address
      IPv6_addr="IPv6 address, required"
      IPv6_slash_mask="uint8, required"/>
</target_IPv6_slash_descriptor>
----

==== target_IPv6_source_slash_descriptor

Defined by DVB in <<ETSI-301-192>>.
Must be in an INT (table id 0x4C).

[source,xml]
----
<target_IPv6_source_slash_descriptor>
  <!-- One per pair of IPv6 address: -->
  <address
      IPv6_source_addr="IPv6 address, required"
      IPv6_source_slash_mask="uint8, required"
      IPv6_dest_addr="IPv6 address, required"
      IPv6_dest_slash_mask="uint8, required"/>
</target_IPv6_source_slash_descriptor>
----

==== target_MAC_address_descriptor

Defined by DVB in <<ETSI-301-192>> and <<ETSI-102-006>>.
Must be in a UNT (table id 0x4B) or INT (table id 0x4C).

[source,xml]
----
<target_MAC_address_descriptor MAC_addr_mask="MAC address, required">
  <!-- One per MAC address: -->
  <address MAC_addr="MAC address, required"/>
</target_MAC_address_descriptor>
----

==== target_MAC_address_range_descriptor

Defined by DVB in <<ETSI-301-192>>.
Must be in an INT (table id 0x4C).

[source,xml]
----
<target_MAC_address_range_descriptor>
  <!-- One per MAC address range: -->
  <range MAC_addr_low="MAC address, required"
         MAC_addr_high="MAC address, required"/>
</target_MAC_address_range_descriptor>
----

==== target_region_descriptor

Defined by DVB in <<ETSI-300-468>>.

[source,xml]
----
<target_region_descriptor country_code="char3, required">
  <!-- One per region -->
  <region country_code="char3, optional"
          primary_region_code="uint8, optional"
          secondary_region_code="uint8, optional"
          tertiary_region_code="uint16, optional"/>
</target_region_descriptor>
----

==== target_region_name_descriptor

Defined by DVB in <<ETSI-300-468>>.

[source,xml]
----
<target_region_name_descriptor
    country_code="char3, required"
    ISO_639_language_code="char3, required">

  <!-- One per region -->
  <region region_name="string, required"
          primary_region_code="uint8, required"
          secondary_region_code="uint8, optional"
          tertiary_region_code="uint16, optional"/>

</target_region_name_descriptor>
----

==== target_serial_number_descriptor

Defined by DVB in <<ETSI-301-192>> and <<ETSI-102-006>>.
Must be in a UNT (table id 0x4B) or INT (table id 0x4C).

[source,xml]
----
<target_serial_number_descriptor>
  <!-- Serial data bytes -->
  Hexadecimal content
</target_serial_number_descriptor>
----

==== target_smartcard_descriptor

Defined by DVB in <<ETSI-301-192>> and <<ETSI-102-006>>.
Must be in a UNT (table id 0x4B) or INT (table id 0x4C).

[source,xml]
----
<target_smartcard_descriptor super_CA_system_id="uint32, required">
  <!-- Private data bytes -->
  Hexadecimal content
</target_smartcard_descriptor>
----

==== telephone_descriptor

Defined by DVB in <<ETSI-300-468>>.

[source,xml]
----
<telephone_descriptor
    foreign_availability="bool, required"
    connection_type="uint5, required"
    country_prefix="string, 3 chars max, optional"
    international_area_code="string, 7 chars max, optional"
    operator_code="string, 3 chars max, optional"
    national_area_code="string, 7 chars max, optional"
    core_number="string, 15 chars max, optional"/>
----

==== teletext_descriptor

Defined by DVB in <<ETSI-300-468>>.

[source,xml]
----
<teletext_descriptor>
  <!-- One per page -->
  <teletext language_code="char3, required"
            teletext_type="uint5, required"
            page_number="uint16, required"/>
</teletext_descriptor>
----

==== terrestrial_delivery_system_descriptor

Defined by DVB in <<ETSI-300-468>>.

[source,xml]
----
<terrestrial_delivery_system_descriptor
    centre_frequency="FrequencyHz, required"
    bandwidth="8MHz|7MHz|6MHz|5MHz, required"
    priority="HP|LP, required"	
    no_time_slicing="bool, required"
    no_MPE_FEC="bool, required"
    constellation="QPSK|16-QAM|64-QAM, required"
    hierarchy_information="uint3, required"
    code_rate_HP_stream="1/2|2/3|3/4|5/6|7/8, required"
    code_rate_LP_stream="1/2|2/3|3/4|5/6|7/8, required"
    guard_interval="1/32|1/16|1/8|1/4, required"
    transmission_mode="2k|8k|4k, required"
    other_frequency="bool, required"/>
----

==== time_shifted_event_descriptor

Defined by DVB in <<ETSI-300-468>>.

[source,xml]
----
<time_shifted_event_descriptor
    reference_service_id="uint16, required"
    reference_event_id="uint16, required"/>
----

==== time_shifted_service_descriptor

Defined by DVB in <<ETSI-300-468>>.

Because of the presence of an ATSC version of the `time_shifted_service_descriptor`,
the XML name for the DVB version is `<DVB_time_shifted_service_descriptor>`.
For compatibility, `<time_shifted_service_descriptor>` is still accepted.

[source,xml]
----
<DVB_time_shifted_service_descriptor reference_service_id="uint16, required"/>
----

==== time_slice_fec_identifier_descriptor

Defined by DVB in <<ETSI-301-192>>.

[source,xml]
----
<time_slice_fec_identifier_descriptor
    time_slicing="bool, required"
    mpe_fec="uint2, required"
    frame_size="uint3, required"
    max_burst_duration="uint8, required"
    max_average_rate="uint4, required"
    time_slice_fec_id="uint4, default=0">
  <id_selector_bytes>Hexadecimal content</id_selector_bytes>
</time_slice_fec_identifier_descriptor>
----

==== transport_protocol_descriptor

Defined by DVB in <<ETSI-101-812>>.
Must be in an AIT (table id 0x74).

[source,xml]
----
<transport_protocol_descriptor transport_protocol_label="uint8, required">

  <!-- Only one of the following shall be present -->
  <!-- For protocol id 1: -->
  <object_carousel
      original_network_id="uint16, optional"
      transport_stream_id="uint16, optional"
      service_id="uint16, optional"
      component_tag="uint8, required"/>

  <!-- For protocol id 2: -->
  <ip_mpe
      original_network_id="uint16, optional"
      transport_stream_id="uint16, optional"
      service_id="uint16, optional"
      alignment_indicator="bool, required">
    <!-- One per URL -->
    <url value="string, required"/>
  </ip_mpe>

  <!-- For protocol id 3: -->
  <http>
    <!-- One per URL -->
    <url base="string, required">
      <!-- One per URL extension -->
      <extension value="string, required"/>
    </url>
  </http>

  <!-- For other (unknown) protocol ids: -->
  <protocol id="uint16, required">
    Hexadecimal content.
  </protocol>

</transport_protocol_descriptor>
----

==== transport_stream_descriptor

Defined by DVB in <<ETSI-300-468>>.

[source,xml]
----
<transport_stream_descriptor compliance="string, required"/>
----

==== TTML_subtitling_descriptor

Defined by DVB in <<ETSI-303-560>>.

[source,xml]
----
<TTML_subtitling_descriptor
    ISO_639_language_code="char3, required"
    subtitle_purpose="uint6, required"
    TTS_suitability="uint2, required"
    qualifier="uint32, optional"
    service_name="string, optional"
    reserved_zero_future_count="uint8, default=0">

  <!-- one per dvb_ttml_profile value -->
  <dvb_ttml_profile value="uint8, required"/>

  <!-- one per font_id value -->
  <font_id value="uint7, required"/>

</TTML_subtitling_descriptor>
----

==== TVA_id_descriptor

Defined by DVB in <<ETSI-102-323>>.

[source,xml]
----
<TVA_id_descriptor>
  <TVA id="uint16, required" running_status="uint3, required"/>
</TVA_id_descriptor>
----

==== update_descriptor

Defined by DVB in <<ETSI-102-006>>.
Must be in a UNT (table id 0x4B).

[source,xml]
----
<update_descriptor
    update_flag="uint2, required"
    update_method="uint4, required"
    update_priority="uint2, required">

  <private_data>
    Hexadecimal content
  </private_data>

</update_descriptor>
----

==== URI_linkage_descriptor

Defined by DVB in <<ETSI-300-468>>.

[source,xml]
----
<URI_linkage_descriptor
    uri_linkage_type="uint8, required"
    uri="string, required"
    min_polling_interval="uint16, optional">

  <!-- When uri_linkage_type == 0x03 -->
  <DVB_I_linkage
      end_point_type="uint8, required"
      service_list_name="string, optional"
      service_list_provider_name="string, optional">
    <private_data>
      Hexadecimal content
    </private_data>
  </DVB_I_linkage>

  <private_data>
    Hexadecimal content
  </private_data>

</URI_linkage_descriptor>
----

==== VBI_data_descriptor

Defined by DVB in <<ETSI-300-468>>.

[source,xml]
----
<VBI_data_descriptor>
  <!-- One per VBI data service -->
  <service data_service_id="uint8, required">
    <!-- One per field in the service -->
    <field field_parity="bool, default=false" line_offset="uint5, default=0"/>
    <!-- Valid only when data_service_id is not any of 1, 2, 4, 5, 6, 7 -->
    <reserved>
      Hexadecimal content
    </reserved>
  </service>
</VBI_data_descriptor>
----

==== VBI_teletext_descriptor

Defined by DVB in <<ETSI-300-468>>.

[source,xml]
----
<VBI_teletext_descriptor>
  <!-- One per page -->
  <teletext language_code="char3, required"
            teletext_type="uint5, required"
            page_number="uint16, required"/>
</VBI_teletext_descriptor>
----

==== video_depth_range_descriptor

Defined by DVB in <<ETSI-300-468>>.

[source,xml]
----
<video_depth_range_descriptor>

  <!-- One per video range -->
  <range range_type="uint8, required"
         video_max_disparity_hint="int12, required when range_type == 0"
         video_min_disparity_hint="int12, required when range_type == 0">
    <range_selector>
      Hexadecimal content
    </range_selector>
  </range>

</video_depth_range_descriptor>
----

==== vvc_subpictures_descriptor

Defined by DVB in <<ETSI-300-468>>.

[source,xml]
----
<vvc_subpictures_descriptor
  default_service_mode="bool, required"
  processing_mode="uint3, required"
  service_description="string, optional">
  <subpicture
    component_tag="uint8, required"
    subpicture_id="uint8, required"/>
</vvc_subpictures_descriptor>
----
