//----------------------------------------------------------------------------
//
// TSDuck - The MPEG Transport Stream Toolkit
// Copyright (c) 2005-2024, Thierry Lelegard
// BSD-2-Clause license, see LICENSE.txt file or https://tsduck.io/license
//
//----------------------------------------------------------------------------

=== DVB-defined tables

==== Application Information Table (AIT)

Defined by DVB in <<ETSI-102-809>> and <<ETSI-101-812>>.

[source,xml]
----
<AIT version="uint5, default=0"
     current="bool, default=true"
     test_application_flag="bool, default=true"
     application_type="uint15, required">

  <!-- Common descriptors loop -->
  <DESCRIPTOR_LIST>

  <!-- One per application -->
  <application control_code="uint8, required">
    <application_identifier
         organization_id="uint32, required"
         application_id="uint16, required"/>
    <DESCRIPTOR_LIST>
  </application>

</AIT>
----

==== Bouquet Association Table (BAT)

Defined by DVB in <<ETSI-300-468>>.

The optional attribute `preferred_section` indicates in which section
the description of a transport stream should be preferably serialized.
When unspecified for a TS, the corresponding TS description is serialized in an arbitrary section.

[source,xml]
----
<BAT version="uint5, default=0"
     current="bool, default=true"
     bouquet_id="uint16, required">

  <!-- Bouquet-level descriptors -->
  <DESCRIPTOR_LIST>

  <!-- One per transport stream -->
  <transport_stream transport_stream_id="uint16, required"
                    original_network_id="uint16, required"
                    preferred_section="uint8, optional">
    <DESCRIPTOR_LIST>
  </transport_stream>

</BAT>
----

==== Content Identifier Table (CIT)

Defined by DVB in <<ETSI-102-323>>.

[source,xml]
----
<CIT version="uint5, default=0"
     current="bool, default=true"
     service_id="uint16, required"
     transport_stream_id="uint16, required"
     original_network_id="uint16, required">

  <!-- One per prepend string -->
  <prepend_string value="string, required"/>

  <!-- One per CRID (Content Reference Identifier) -->
  <crid crid_ref="uint16, required"
        prepend_string_index="uint8, optional"
        unique_string="string, required"/>

</CIT>
----

==== Discontinuity Information Table

Defined by DVB in <<ETSI-300-468>>.

[source,xml]
----
<discontinuity_information_table transition="bool, required"/>
----

==== Event Information Table (EIT)

Defined by DVB in <<ETSI-300-468>>.
This is the DVB version of an EIT.
ATSC uses a different structure for EIT.

If `type="pf"`, this is an EITp/f (present/following).

If `type` is a 4-bit integer, this is an EITs (schedule) with TID 0x50 + `type` (EITs Actual) or 0x60 + `type` (EITs Other),
depending on the `actual` attribute.

When an EIT is compiled by TSDuck (serialized as binary sections),
the events are sorted in ascending order of start time and spread over sections as described in <<ETSI-101-211>>.

The attribute `last_table_id` is optional.
By default, it is set to the same table id as the table.
Upon serialization, the DVB rules are enforced to bind its value within the DVB-specified limits.

When an EIT section is generated by the plugin `eitinject`, all these fields are automatically computed.

[source,xml]
----
<EIT type="pf|uint4, default=pf"
     version="uint5, default=0"
     current="bool, default=true"
     actual="bool, default=true"
     service_id="uint16, required"
     transport_stream_id="uint16, required"
     original_network_id="uint16, required"
     last_table_id="uint8, default=same as table id">

  <!-- One per event -->
  <event event_id="uint16, required"
         start_time="YYYY-MM-DD hh:mm:ss, required"
         duration="hh:mm:ss, required"	
         running_status="undefined|not-running|starting|pausing|running|off-air,
                         default=undefined"
         CA_mode="bool, default=false">
    <DESCRIPTOR_LIST>	
  </event>

</EIT>
----

==== IP/MAC Notification Table (INT)

Defined by DVB in <<ETSI-301-192>>.

[source,xml]
----
<INT version="uint5, default=0"
     current="bool, default=true"
     action_type="uint8, default=0x01"
     processing_order="uint8, default=0x00"
     platform_id="uint24, required">

  <!-- Plaform-level descriptors -->
  <DESCRIPTOR_LIST>	

  <!-- One per device -->
  <device>
    <target>
      <DESCRIPTOR_LIST>	
    </target>
    <operational>
      <DESCRIPTOR_LIST>	
    </operational>
  </device>

</INT>
----

==== Network Information Table (NIT)

Defined by DVB in <<ETSI-300-468>>.

The optional attribute `preferred_section` indicates in which section
the description of a transport stream should be preferably serialized.
When unspecified for a TS, the corresponding TS description is serialized in an arbitrary section.

[source,xml]
----
<NIT version="uint5, default=0"
     current="bool, default=true"
     network_id="uint16, required"
     actual="bool, default=true">

  <!-- Network-level descriptors -->
  <DESCRIPTOR_LIST>

  <!-- One per transport stream -->
  <transport_stream transport_stream_id="uint16, required"
                    original_network_id="uint16, required"
                    preferred_section="uint8, optional">
    <DESCRIPTOR_LIST>
  </transport_stream>

</NIT>
----

==== Related Content Table (RCT)

Defined by DVB in <<ETSI-102-323>>.

[source,xml]
----
<RCT version="uint5, default=0"
     current="bool, default=true"
     service_id="uint16, required"
     year_offset="uint16, required">

  <!-- One per link -->
  <link link_type="uint4, required"
        how_related_classification_scheme_id="uint6, required"
        term_id="uint12, required"
        group_id="uint4, required"
        precedence="uint4, required"
        media_uri="string, required when link_type == 0 or 2"
        default_icon_flag="bool, required"
        icon_id="uint3, required">

    <!-- If link_type == 1 or 2 -->
    <dvb_binary_locator
        identifier_type="uint2, required"
        scheduled_time_reliability="bool, required"
        inline_service="bool, required"
        start_date="uint9, required"
        dvb_service_triplet_id="uint10, required when inline_service == false"
        transport_stream_id="uint16, required when inline_service == true"
        original_network_id="uint16, required when inline_service == true"
        service_id="uint16, required when inline_service == true"
        start_time="uint16, required"
        duration="uint16, required"
        event_id="uint16, required when identifier_type == 1"
        TVA_id="uint16, required when identifier_type == 2 or 3"
        component_tag="uint8, required when identifier_type == 3"
        early_start_window="uint3, required when identifier_type == 0 and
                                   scheduled_time_reliability == true"
        late_end_window="uint5, required when identifier_type == 0 and
                                scheduled_time_reliability == true"/>

    <!-- One per text -->
    <promotional_text language_code="char3, required" text="string, required"/>

    <DESCRIPTOR_LIST>

  </link>

  <DESCRIPTOR_LIST>

</RCT>
----

==== Resolution provider Notification Table (RNT)

Defined by DVB in <<ETSI-102-323>>.

[source,xml]
----
<RNT version="uint5, default=0"
     current="bool, default=true"
     context_id="uint16, required"
     context_id_type="uint8, required">

  <DESCRIPTOR_LIST>

  <!-- One per resolution provider -->
  <resolution_provider name="string, required">

    <DESCRIPTOR_LIST>

    <!-- One per CRID authority -->
    <CRID_authority name="string, required" policy="uint2, required">
      <DESCRIPTOR_LIST>
    </CRID_authority>

  </resolution_provider>

</RNT>
----

==== Running Status Table (RST)

Defined by DVB in <<ETSI-300-468>>.

[source,xml]
----
<RST>
  <!-- One per event -->
  <event transport_stream_id="uint16, required"
         original_network_id="uint16, required"
         service_id="uint16, required"
         event_id="uint16, required"
         running_status="undefined|not-running|starting|pausing|running|off-air,
                         required"/>
</RST>
----

==== Satellite Information Table (SAT)

Defined by DVB in <<ETSI-300-468>>.

[source,xml]
----
<SAT version="uint5, default=0"
     current="bool, default=true"
     satellite_table_id="uint6, required"
     table_count="uint10, required">

  <!-- satellite_table_id=0 -> satellite_position_v2_info -->
  <satellite_position_v2_info>
    <!-- 1 or more satellite_position required -->
    <satellite_position satellite_id="uint24, required">
      <!-- position_system==0 -> geostationary -->
      <geostationary
          orbital_position="SatelliteOrbitalPosition, eg. 19.2, required"
          west_east_flag="east|west, required"/>
      <!-- position_system==1 -> earth_orbiting -->
      <earth_orbiting
          epoch_year="uint8, required"
          day_of_the_year="uint16, required"
          day_fraction="float, required"
          mean_motion_first_derivative="float, required"
          mean_motion_second_derivative="float, required"
          drag_term="float32, required"
          inclination="float32, required"
          right_ascension_of_the_ascending_node="float32, required"
          eccentricity="float32, required"
          argument_of_perigree="float32, required"
          mean_anomaly="float32, required"
          mean_motion="float32, required"/>
    </satellite_position>
  </satellite_position_v2_info>

  <!-- satellite_table_id=1 -> cell_fragment_info -->
  <cell_fragment_info>
    <!-- 1 or more cell_fragment required -->
    <cell_fragment
        cell_fragment_id="uint32, required"
        first_occurence="bool, required"
        last_occurence="bool, required"
        center_latitude="int18, optional"
        center_longitude="int19, optional"
        max_distance="uint24, optional">
      <!--
          center_latitude, center_longitude (tcimsbf) -
              two's complement integer, most significanr (sign) bit first
          center_latitude, center_longitude,
              max_distance only required when first_occurrence=true
      -->

      <!-- 0 or more delivery_system required -->
      <delivery_system id="uint32, required"/>

      <!-- 0 or more new_delivery_system required -->
      <new_delivery_system id="uint32, required">
        <time_of_application
            base="uint33, required"
            ext="uint9, required"/>
      </new_delivery_system>

      <!-- 0 or more obsolescent_delivery_system required -->
      <obsolescent_delivery_system id="uint32, required">
        <time_of_obsolescence
            base="uint33, required"
            ext="uint9, required"/>
      </obsolescent_delivery_system>

    </cell_fragment>
  </cell_fragment_info>

  <!-- satellite_table_id=2 -> time_association_info -->
  <time_association_info
      association_type="uint4, required"
      leap59="bool, optional"
      leap61="bool, optional"
      past_leap59="bool, optional"
      past_leap61="bool, optional"
      association_timestamp_seconds="uint64, required"
      association_timestamp_nanoseconds="uint32, required">
    <!--
        association_type==0:  UTC without leab second signalling
        association_type==1:  UTC with leab second signalling
        leap59, leap61, pastleap59, pastleap61 only required when association_type==1
    -->
    <ncr base="uint33, required"
         ext="uint9, required"/>
  </time_association_info>

  <!-- satellite_table_id=3 -> beamhopping_timeplan_info -->
  <beamhopping_timeplan_info>
    <beamhopping_timeplan id="uint32, required">

      <time_of_application
          base="uint33, required"
          ext="uint9, required"/>
      <cycle_duration
          base="uint33, required"
          ext="uint9, required"/>

      <time_plan_mode_0>
        <dwell_duration
            base="uint33, required"
            ext="uint9, required"/>
        <on_time
            base="uint33, required"
            ext="uint9, required"/>
      </time_plan_mode_0>

      <time_plan_mode_1 current_slot="uint15, required">
        <slot id="uint15, required" transmission_on="bool, required"/>
      </time_plan_mode_1>

      <time_plan_mode_2>
        <grid_size
            base="uint33, required"
            ext="uint9, required"/>
        <revisit_duration
            base="uint33, required"
            ext="uint9, required"/>
        <sleep_time
            base="uint33, required"
            ext="uint9, required"/>
        <sleep_duration
            base="uint33, required"
            ext="uint9, required"/>
      </time_plan_mode_2>

    </beamhopping_timeplan>
  </beamhopping_timeplan_info>

  <!-- satellite_table_id=4 -> satellite_position_v3_info -->
  <satellite_position_v3_info
      oem_version_major="uint4, required"
      oem_version_minor="uint4, required">

    <creation_date year="uint8, required" day="uint9, required" day_fraction="float32, required"/>

    <v3_satellite satellite_id="uint24, required"
        interpolation_type="Linear|Lagrange|Hermite, optional" interpolation_degree="uint3, optional">

      <total_start_time year="uint8, required" day="uint9, required" day_fraction="float32, required"/>
      <total_stop_time year="uint8, required" day="uint9, required" day_fraction="float32, required"/>

      <!-- usable start and stop time are optional but only used when total_start_time,
           total_stop_time, and the three interpolation values are given -->
      <usable_start_time year="uint8, required" day="uint9, required" day_fraction="float32, required"/>
      <usable_stop_time year="uint8, required" day="uint9, required" day_fraction="float32, required"/>

      <ephemeris_data
          ephemeris_x="float32, required"
          ephemeris_y="float32, required"
          ephemeris_z="float32, required"
          ephemeris_x_dot="float32, required"
          ephemeris_y_dot="float32, required"
          ephemeris_z_dot="float32, required"
          ephemeris_x_ddot="float32, optional"
          ephemeris_y_ddot="float32, optional"
          ephemeris_z_ddot="float32, optional">
        <epoch year="uint8, required" day="uint9, required" day_fraction="float32, required"/>
      </ephemeris_data>

      <covariance>
        <epoch year="uint8, required" day="uint9, required" day_fraction="float32, required"/>
        <element>float32</element>
      </covariance>

    </v3_satellite>

  </satellite_position_v3_info>

</SAT>
----

==== Selection Information Table (SIT)

Defined by DVB in <<ETSI-300-468>>.

[source,xml]
----
<selection_information_table version="uint5, default=0" current="bool, default=true">

  <!-- Common descriptors loop, for transmission parameters -->
  <DESCRIPTOR_LIST>

  <!-- One per service -->
  <service service_id="uint16, required"
           running_status="undefined|not-running|starting|pausing|running|off-air,
                           required">
    <DESCRIPTOR_LIST>
  </service>

</selection_information_table>
----

==== Service Description Table (SDT)

Defined by DVB in <<ETSI-300-468>>.

[source,xml]
----
<SDT version="uint5, default=0"
     current="bool, default=true"
     transport_stream_id="uint16, required"
     original_network_id="uint16, required"
     actual="bool, default=true">

  <!-- One per service -->
  <service service_id="uint16, required"
           EIT_schedule="bool, default=false"
           EIT_present_following="bool, default=false"
           running_status="undefined|not-running|starting|pausing|running|
                           off-air, default=undefined"
           CA_mode="bool, default=false">
    <DESCRIPTOR_LIST>
  </service>

</SDT>
----

==== Time and Date Table (TDT)

Defined by DVB in <<ETSI-300-468>>.

[source,xml]
----
<TDT UTC_time="YYYY-MM-DD hh:mm:ss, required"/>
----

==== Time Offset Table (TOT)

Defined by DVB in <<ETSI-300-468>>.

[source,xml]
----
<TOT UTC_time="YYYY-MM-DD hh:mm:ss, required">
  <DESCRIPTOR_LIST>
</TOT>
----

==== Update Notification Table (UNT)

Defined by DVB in <<ETSI-101-211>>.

[source,xml]
----
<UNT version="uint5, default=0"
     current="bool, default=true"
     action_type="uint8, default=0x01"
     OUI="uint24, required"
     processing_order="uint8, default=0x00">

  <!-- Common descriptors, apply to all SSU -->
  <DESCRIPTOR_LIST>

  <!-- One per set of devices -->
  <devices>

    <!-- More than one allowed, each one is an individual descriptor -->
    <!-- inside compatibilityDescriptor() -->
    <compatibilityDescriptor
        descriptorType="uint8, required"
        specifierType="uint8, default=0x01"
        specifierData="uint24, required"
        model="uint16, default=0x00"
        version="uint16, default=0x00">
      <!-- Several subdescriptors -->
      <subDescriptor subDescriptorType="uint8, required">
        Hexadecimal content
      </subDescriptor>
    </compatibilityDescriptor>

    <!-- One per platform -->
    <platform>
      <target>
        <DESCRIPTOR_LIST>
      </target>
      <operational>
        <DESCRIPTOR_LIST>
      </operational>
    </platform>
  </devices>

</UNT>
----
