//----------------------------------------------------------------------------
//
// TSDuck - The MPEG Transport Stream Toolkit
// Copyright (c) 2005-2026, Thierry Lelegard
// BSD-2-Clause license, see LICENSE.txt file or https://tsduck.io/license
//
//----------------------------------------------------------------------------

[#devplugin]
=== Developing a TSDuck plugin

[#pdevworkflow]
==== Plugin development workflow

When some new kind of transport stream processing is needed, several solutions are possible:

* First, check if an existing plugin or a combination of existing plugins can do the job.
* Check if an existing plugin can be extended (by adding new options for instance).
* As a last resort, develop a new plugin, which is relatively easy.

New plugins can be developed either as part of the TSDuck project or as independent third-party projects.

[#pdev3rdpary]
===== Developing independent third-party plugins

If you create your own third-party plugins (ie. if you are not a TSDuck maintainer),
it is recommended to develop your plugins outside the TSDuck project.

Do not modify your own copy of the TSDuck project with your private plugins.
This could create useless difficulties to upgrade with new versions of the project.

Consider developing your plugins in their own projects, outside TSDuck.
You do not even need to get the full source code of TSDuck.
It is sufficient to install the TSDuck development environment (see xref:usinglibrary[xrefstyle=short]).

An example of a third party plugin project is provided in the directory
{source}sample/sample-plugin[sample/sample-plugin].

[#pdevinternal]
===== Developing plugins for the TSDuck project

To develop a new plugin named `foo`, follow these steps:

* Create a source file named `tsplugin_foo.cpp` in the `tsplugins` subdirectory.
* On {unix}, this new source file will be automatically recognized
  by the Makefile and the new plugin will be built.
* On Windows systems, the plugin needs a "project file" for Visual Studio and MSBuild.
  This project file shall be referenced in the TSDuck "solution file".

The last step is automated using the Python script `scripts/build-project-files.py`.
This script explores the source files for all commands and plugins.
It automatically generates missing project files and references them in the solution file.

This script can be run on {unix} or Windows systems.
On Windows, it can be easier to launch the PowerShell script `scripts/build-project-files.ps1`,
which simply calls the Python script.

[#pdevguidelines]
==== Development guidelines

Don't write a plugin from scratch.
Use an existing plugin as code base (beware however of the pitfalls of careless copy / paste).
The simplest code bases can be found in the plugins `null` (input), `drop` (output) , `skip` (basic packet processing),
`nitscan` (reading content of PSI/SI), `svrename` (modifying PSI/SI on the fly).

Always create plugins which perform simple and elementary processing.
If your requirements can be divided into two independent processing, create two distinct plugins.
The strength of TSDuck is the flexibility,
that is to say the ability to combine elementary processing independently and in any order.

[#pdevclasses]
===== Class hierarchy

In the source file of the plugin, create a {cpp} class, derived from either
classref:InputPlugin[], classref:OutputPlugin[] or classref:ProcessorPlugin[].
If your plugin implements two capabilities (both input and output for instance),
implement the corresponding two classes in the same source file.

See the class diagram of classref:Plugin[] for a global view of the plugin classes.

Specialized plugins which manipulate exiting tables derive from classref:AbstractTablePlugin[].
Examples of such plugins are `pmt`, `pat`, `nit`, etc.
The actual plugin subclasses focus on the modification of the target table
while the superclass automatically handles demuxing, remuxing and creation of non-existing tables.

Specialized descrambling plugins derive from classref:AbstractDescrambler[].
This abstract class performs the generic functions of a descrambler:
service location, ECM collection, descrambling of elementary streams.
The concrete classes which derive from classref:AbstractDescrambler[] must perform CAS-specific operations:
ECM streams filtering, ECM deciphering, control words extraction.
Most of the time, these concrete classes must interact with a smartcard reader
containing a smartcard for the specific CAS.

[#pdevtsp]
===== Invoking tsp from a plugin, the ts::TSP callbacks

In its constructor, each plugin receives an associated classref:TSP[] object to communicate
with the `tsp` main executable.
This instance of classref:TSP[] is a protected field named `tsp`
which can be freely accessed by the code of the plugin.

A plugin shared library must exclusively use that `tsp` object for text display
and must never use `std::cout`, `printf` or the like.
The class classref:TSP[] is a subclass of classref:Report[] and supports all reporting methods
such as `info()`, `verbose()`, `error()`, `debug()`, etc.

When called in a multi-threaded context, the supplied `tsp` object is thread-safe and asynchronous
(the methods return to the caller without waiting for the message to be printed).

Note that the plugin instance is also a subclass of classref:Report[] and automatically redirects
all messages to its `tsp` field. Therefore, the code of the plugin can transparently use
its own methods `info()`, `error()`, etc. This is equivalent to calling its `tsp`.

[#pdevjtem]
===== Joint termination support

A plugin can decide to terminate `tsp` on its own (returning end of input, output error
or `ts::ProcessorPlugin::TSP_END`).
The termination is unconditional, regardless of the state of the other plugins.
Thus, if several plugins have termination conditions, `tsp` stops when the first plugin decides to terminate.
In other words, there is an "or" operator between the various termination conditions.

The idea behind joint termination is to terminate `tsp` when several plugins have jointly terminated their processing.
If several plugins have a "joint termination" condition,
`tsp` stops when the last plugin triggers the joint termination condition.
In other words, there is an "and" operator between the various joint termination conditions.

First, a plugin must decide to use joint termination.
This is usually done in method `ts::Plugin::start()`, using `ts::TSP::useJointTermination(bool)`
when the option `--joint-termination` is specified on the command line.

Then, when the plugin has completed its work, it reports this using `ts::TSP::jointTerminate()`.
After invoking this method, any packet which is processed by the plugin may be ignored by `tsp`.
