//----------------------------------------------------------------------------
//
// TSDuck - The MPEG Transport Stream Toolkit
// Copyright (c) 2005-2026, Thierry Lelegard
// BSD-2-Clause license, see LICENSE.txt file or https://tsduck.io/license
//
//----------------------------------------------------------------------------

[#libsoverview]
=== Overview of the TSDuck libraries

The TSDuck libraries contain general-purpose {cpp} classes and utilities to handle
MPEG transport streams.

For programming details, see the
{home}doxy/[programming reference documentation online] (doxygen-generated).

Roughly, the TSDuck libraries provide two categories of features:

* Operating system abstraction layer to make the application code fully portable between heterogeneous platforms.
  This is similar to frameworks such as Qt, but much more lightweight.
* Handling of MPEG transport streams and signalization, including DVB, ATSC and ISDB features.

NOTE: In early versions of TSDuck, the OS abstraction layer contained many more classes.
Starting with {cpp}11 and {cpp}20, the standard library of the language was enriched with many more system features.
Some low-level TSDuck classes became obsolete.
The code was migrated to use standard {cpp}20 features and the corresponding low-level classes were removed from TSDuck.

All {cpp} declarations are located inside the namespace `ts`, either directly within `ts` or inside inner namespaces.
All preprocessor's macros are named with prefix `TS_`.

[#cppfeatures]
==== {cpp} features

[#portability]
===== Portability issues

The file `tsPlatform.h` contains some very low level definitions such as macros defining the environment
(processor, compiler, operating system, endianness), byte and bit manipulation, etc.

[#cppstrings]
===== {cpp} strings

C and {cpp} strings are made of 8-bit characters which are notoriously unable to represent international character sets.
The usage of `std::string` with the TSDuck libraries is discouraged in favor of _Unicode strings_.

[#unicodestring]
===== Unicode strings

The class classref:UString[] implements Java-like Unicode strings.
Each character uses 16 bits of storage.
Formally, classref:UString[] uses UTF-16 representation.
This means that all characters from all modern languages can be represented as one single character.
Characters from archaic languages may need two UTF-16 values, called a "surrogate pair".

Technically, classref:UString[] is a subclass of `std::u16string`.
So any operation on standard {cpp} strings is also available to classref:UString[].
But many more operations have been added to manipulate Unicode strings.

For consistency, the type `ts::UChar` is an alias for `char16_t`.
The header file `tsUChar.h` defines some utility functions on `ts::UChar`.
It also defines constants for most Unicode characters like `ts::COLON` or more complex ones such as
`ts::LATIN_CAPITAL_LETTER_A_WITH_ACUTE`, among hundredths of others.

Some interesting features in class classref:UString[] are:

[.compact-list]
* Explicit and implicit conversions between UTF-8 and UTF-16.
* Including automatic conversion to UTF-8 when writing to text streams.
* Conversions with DVB and ARIB character sets.
* Conversions with HTML encoding.
* Management of "display width", that is to say the amount of space which is used when the string is displayed.
  This can be different from the string length in the presence of combining diacritical characters or surrogate pairs.
* String padding, trimming, truncation, justification, case conversions.
* Substring, prefix or suffix detection, removal or substitution.
* Splitting and joining strings based on separators or line widths.
* Reading or writing text lines from or to a text file.
* Data formatting using `format()`,  `Format()`, `Decimal()`, `Hexa()`, `Dump()`.
* Data scanning using `scan()`.

Unicode strings can be converted to and from DVB or ARIB (Japan) strings.
Most DVB-defined character sets are implemented (see the classes classref:Charset[] and classref:DVBCharset[])
and recognized when a string is read from a descriptor.
When a string is serialized into a binary descriptor, the most appropriate DVB character set is used.
In practice, a few known DVB character sets are used and, when the string cannot be encoded in any of them,
UTF-8 is used (UTF-8 is always a valid DVB character set).

[#bindata]
===== Binary data

The class classref:ByteBlock[] represents a raw block of bytes.
It is a subclass of `std::vector<uint8_t>` and consequently benefits from all standard vector operations.
It also adds useful methods for data serialization or deserialization in any byte order.

For data serialization or deserialization over arbitrary memory areas,
the header file `tsMemory.h` provides low-level functions to access integer values
of 8, 16, 24, 32, 40, 48 and 64 bits in any byte order.

The class classref:Buffer[] provides a higher-level abstraction layer over a memory area to parse or generate bitstreams.
It gives access to data of any bit-size at any bit position, any endianness,
either as a continuous stream or seeking at random bit positions.

The principles of the {cpp} class classref:Buffer[] were freely inspired by the Java class `java.nio.ByteBuffer`.
There are differences between the two but the main principles are similar.

Its subclass classref:PSIBuffer[] provides primitives to serialize and deserialize MPEG and DVB structures
such as list of descriptors, DVB, ARIB and ATSC strings or "Modified Julian Dates".

[#singletons]
===== Singletons and static data

The _singleton_ design pattern is simple in theory, but not so simple to implement correctly in practice.
The TSCore library encapsulates the implementation difficulties using the two macros `TS_SINGLETON()`
(in a header file) and `TS_DEFINE_SINGLETON()` (in the corresponding compilation unit).

In practice, the singleton design pattern is a specific case of _global static data_,
variables which are defined outside any function.
Using static data can be a nightmare because it is impossible to manage the initialization order of modules in {cpp}.

In the past, how to properly managed singletons and static data was quite difficult,
involving dangerous pointer and thread synchronization tricks.
This has been abundantly documented by Scott Meyers (see <<MEYERS-EFF>>).

In modern {cpp}, most of these difficulties have been solved in the language using _local static data_.
In practice, the same tricks are used but they are now hidden inside the compiler and the run-time library.
See xref:shareddata[xrefstyle=short] for programming guidelines.

[#errreport]
===== Error reporting

All TSDuck classes use a consistent error reporting mechanism through the classref:Report[] abstract class.

This interface defines several levels of severity in the type `ts::Severity`,
ranging from `ts::Severity::Debug` to `ts::Severity::Fatal`.
Each instance of classref:Report[] defines which levels of message are reported to the user.
This is usually triggered by command-line options such as `--verbose` or `--debug`.

Most classes or methods from the TSDuck libraries use a reference to an instance of classref:Report[] to report messages and errors.
The actual reporting object is often built at application level and then propagated to all layers of code.

Some interesting subclasses of classref:Report[] are:

[.compact-list]
* classref:CerrReport[], a singleton which reports errors to `std::cerr`.
  The macro `CERR` can be used as a shortcut to the instance of the singleton.
* classref:NullReport[], a singleton which drops all messages.
  The macro `NULLREP` can be used as a shortcut to the instance of the singleton.
* classref:ReportFile[] which logs messages in a file.
  It can be made thread-safe using a `ts::ThreadSafety` value as template argument.
* classref:ReportBuffer[] which logs messages in a memory buffer.
  It can be made thread-safe using a `ts::ThreadSafety` value as template argument.
* classref:Args[] (see xref:cmdargs[xrefstyle=short]) which defines the syntax and handling of command line arguments.
  This is the typical instance of classref:Report[] which is used at application-level.
* classref:Plugin[], the superclass of all `tsp` plugins.
  A plugin reports its messages directly in its own instance.
  Each `tsp` plugin executes in a separate thread and asynchronously logs messages without slowing down the plugin's thread.

[#except]
===== Exceptions

As a general rule, TSDuck prefers the usage of error reporting interface and error status over exceptions.
However, for a limited number of unrecoverable conditions which should never occur in practice, exceptions are used.

All TSDuck exceptions inherit from the superclass classref:Exception[].
An instance of this exception is able to embed an error message and an optional system error code.

Each specific exception should be a subclass of classref:Exception[].
Instead of rewriting the subclass code, applications should use the macro `TS_DECLARE_EXCEPTION()`.

[#enums]
===== Pseudo-enumeration data

An instance of the class classref:Enumeration[] associates a list of integer or `enum` values with strings.
It can be used to display meaningful strings instead of integer values.

It is even more useful to decode command line arguments.
When an option accepts a predefined list of values, the input string can be either an integer value or a name.
When it is a name, it can even be abbreviated as long as it is not ambiguous in the corresponding classref:Enumeration[].
This is transparent for the application which receives the corresponding integer value.

[#cmdargs]
===== Command-line arguments

The class classref:Args[] implements a generic handling of command line arguments.

Each application typically defines its own subclass of classref:Args[].
A plugin is always a subclass of classref:Args[], through the intermediate class classref:Plugin[].

A subclass of classref:Args[] defines the command line syntax and the corresponding help text.
The superclass classref:Args[] automatically parses the command line, reports errors and
handle common options such as `--help` or `--version`.

The value of command line options can be free strings, integer values or enumeration values.
Integer values are recognized in decimal or hexadecimal form (prefix `0x`) and
thousands separators ('`,`') which are present for clarity are ignored.
Enumeration values are handled through classref:Enumeration[].

[#xml]
===== XML data

The TSCore library embeds an XML parser and several classes to handle a DOM structure.

See the class classref:xml/Node[], the abstract base class of the DOM hierarchy.

[#json]
===== JSON data

The TSCore library embeds a JSON parser and several classes to handle JSON values.

See the class classref:json/Value[], the abstract base class of the JSON hierarchy.

[#crypto]
==== Cryptography

The TSDuck libraries contain a few cryptographic classes.
These libraries are *not* cryptographic libraries and will never be.
Cryptography is a serious matter which should be left to cryptographers.

Some transport stream processing operations require cryptographic operations, essentially block ciphers and hash functions.
The TSCore library proposes an homogeneous API over them.
Standard cryptographic primitives are implemented using the standard system libraries,
_OpenSSL_ on {unix}, _BCrypt_ on Windows.
Most standard chaining modes are also implemented in the standard system libraries.
The TSCore library implements more exotic chaining modes only.

Specific algorithms which are defined by Digital TV standard bodies (DVB, SCTE or IDSA) are implemented in the TSDuck library.
However, most of them are only specific modes over standard cryptographic primitives such as AES or DES.
The TSDuck library implements the specific modes but the primitives are used from the system cryptographic libraries,
except the very specific DVB-CSA2 algorithm which is directly implemented in the TSDuck library.

The abstract class classref:BlockCipher[] is the root of a hierarchy of symmetric cryptography classes,
including chaining modes.
The main block cipher classes are classref:AES128[], classref:AES256[], classref:TDES[] and classref:DES[].

CAUTION: DES is an obsolete and insecure algorithm. TDES (a.k.a. 3-DES or Triple DES) is also deprecated.
However, the two are still used in some legacy ATSC Digital TV systems.

Chaining modes are template classes which inherit from the abstract class classref:CipherChaining[].
The template parameter is a block cipher class.
The main chaining modes are classref:ECB[], classref:CBC[], various flavors of classref:CTSx[]
or more exotic modes from the DTV world such as classref:DVS042[].

Additionally, classref:CipherChaining[] is also a subclass of classref:BlockCipher[] because it remains a symmetric cipher.
So, ciphers like classref:AES[] or `ts::CBC<ts::AES>` can be used through the same classref:BlockCipher[] interface.

The class classref:Scrambling[] implements DVB-CSA-2, the Digital Video Broadcasting Common Scrambling Algorithm.
This implementation is older than the open-source https://www.videolan.org/developers/libdvbcsa.html[libdvbcsa library]
and is probably less efficient.

The abstract class classref:Hash[] is the root of a hierarchy of hash functions classes.
The main hash functions are classref:SHA1[], classref:SHA256[] or classref:SHA512[].

The abstract class classref:RandomGenerator[] is the root of pseudo-random generators.

The subclass classref:SystemRandomGenerator[] is a portable interface to the system-provided PRNG.
Usually, this is not the best PRNG on earth, but it is fine for most usages in TSDuck applications.
For more critical usages (such as encryption key generation), use classref:BetterSystemRandomGenerator[].
This PRNG class uses classref:SystemRandomGenerator[] with an additional security layer.

The class classref:Xoshiro256ss[] implements the Xoshiro256** PRNG.
It is a fast and deterministic PRNG, with a low level of security.
The same seed will always produce the same pseudo-random sequence.
It can be used in cases where many random numbers are required, without strong security criteria.
It is typically used in fuzzing tools.

[#osfeatures]
==== Operating system features

[#sysutils]
===== Miscelleaneous system utilities

The header files `tsSysUtils.h`, `tsFileUtils.h`, `tsEnvironment.h`,
declare utility functions on top of the operating system.

With the introduction of {cpp}20, many of these functions have been removed in favor of new standard functions.
However, a number of additional features manipulate:

[.compact-list]
* File paths.
* File attributes.
* Creating or deleting files and directories.
* Environment variables.
* Process identifiers.
* System error codes.

[#time]
===== Time

The class classref:Time[] is a portable implementation of time (both local and UTC time).

Many operations are provided, such as:

[.compact-list]
* Getting system time in various forms.
* Arithmetic operations on time.
* Analysing and building time values.
* Formatting time values as strings.

[#multithread]
===== Multithreading

TSDuck is heavily multi-threaded.
The abstract class classref:Thread[] manages a thread.
To define an actual thread, derive this class and implement the virtual method `main()`.

The class classref:ThreadAttributes[] contains all mandatory or optional attributes of a thead.
An application typically builds a classref:ThreadAttributes[] object and then creates threads using these attributes.

In earlier versions of TSDuck, synchronization primitives used to be implemented
through specific classes (`ts::Mutex`, `ts::Condition`).
They are now removed and new {cpp}11 classes such as `std::mutex` and `std::condition_variable` are used instead.

Note that the {cpp}11 class `std::thread` is not used.
Its API is too limited to be useable in complex environments:
it does not allow to customize the priority or the stack size _before_ the creation of the thread.
Therefore, TSDuck exclusively uses classref:Thread[] and classref:ThreadAttributes[] instead.

TSDuck relies on {cpp} mechanisms to track the usage of resources.
Standard classes such as `std::lock_guard` or `std::unique_lock` are used
to ensure that no dangling lock is lost through the _guard design pattern_.

In addition to multithreading, TSDuck also uses event dispatching.
See xref:reactorevents[xrefstyle=short] for more details.

[#virtmem]
===== Virtual memory

The class classref:ResidentBuffer[] implements a buffer which is locked in physical memory,
preventing paging or swapping on this buffer.
This is useful for large data buffers with high performance constraints.

This is a template class.
The template parameter is the type of the elementary data in the buffer.

The core data of the `tsp` processor is a `ts::ResidentBuffer<ts::TSPacket>`.
The incoming packets are directly written into this buffer by the input plugin.
Each packet processing plugin directly reads and writes the packets here.
And the output plugin reads the packet there, at the very same place they were written by the input plugin.
Given that this global buffer is locked in physical memory, the best performances are guaranteed.

Note however that most operating systems require that the application has privileges to lock physical memory.

[#processes]
===== Processes

To track potential memory leaks and the impact of the application on the system,
the class classref:SystemMonitor[] creates a background thread which
reports the process metrics of the application at regular intervals.

The class classref:ForkPipe[] is a portable and convenient way to create a process running a specific command
and creates an outgoing pipe from the calling application to the standard input of the created process,
or an incoming pipe from the standard output of the created process to the calling application, or both.
The pipes are open in binary mode (when it makes sense for the operating system)
and can be used to pass an entire transport stream when necessary.

[#networking]
===== Networking

The classes classref:IPAddress[] and classref:IPSocketAddress[] define an IP address and
a corresponding socket address (an IP address and a port number).
Host name resolution and multicast are supported.

The class classref:IPAddress[] can hold IPv4 and IPv6 addresses.
All network operations on name resolutions and TCP or UDP sockets
are transparently supported for IPv4 and IPv6 addresses.

The classes classref:TCPSocket[] and classref:UDPSocket[] implement TCP/IP and UDP/IP endpoints.

The class classref:UDPSocket[] can be used directly to send and receive datagrams.
Multicast is supported.

The class classref:TCPSocket[] can be used only through two subclasses.
The subclass classref:TCPConnection[] is a TCP/IP communication endpoint, either on client or server side.
It is used to send or receive data streams.
The subclass classref:TCPServer[] is used to implement a TCP server.
It accepts incoming client connections and initiates a classref:TCPConnection[] for each new connection.
On the client side, the class classref:TCPConnection[] is directly used to connect to the server.

Subclasses of classref:TCPConnection[] are used to implement specific protocols on top of TCP/IP.
Currently, the available subclasses are classref:TelnetConnection[] and classref:tlv/Connection[].
The latter is used to handle communications using the "DVB SimulCrypt head-end protocols".
See xref:dvbprotocols[xrefstyle=short] for more details.

The class classref:WebRequest[] performs simple Web requests using HTTP, HTTPS or FTP.
Using a URL, the result can be downloaded in memory or in a file.
Multiple redirections and SSL/TLS are automatically handled.
This class is built on top of native system libraries, _libcurl_ on {unix}, _WinInet_ on Windows.

In addition to straightforward communication classes using blocking I/O, TSDuck also uses event
dispatching on non-blocking or asynchronous I/O.
See xref:reactorevents[xrefstyle=short] for more details.

[#sharelibs]
===== Shared libraries

The TSCore library contains classes to load shared libraries
(`.dll` on Windows, `.so` on Linux and BSD, `.dylib` on macOS)
and lookup symbols inside them in a portable way.
These classes are typically used to load `tsp` plugins but can be used in any application.

The class classref:SharedLibrary[] manipulates any type of shared library.

The subclass classref:ApplicationSharedLibrary[] searches a shared library using TSDuck rules:
if the file is not found "as it is", an optional prefix and a list of directories are used.
This is how, on Windows for instance, searching the shared library named `zap` will end up loading the file `tsplugin_zap.dll`
in the same directory as the application executable file.

[#pcscinterface]
===== Smart-card interface

Applications which interact with smart-cards shall use the PC/SC interface.
PC/SC is a standard interface which was originally developped for Windows
but which is also available on Linux and macOS.

The TSDuck library does not embed or hide PC/SC but it provides a few utilities
like transmitting an APDU and read the response in one single function or
searching a smart-card with some characteristics in the ATR from all connected smart-cards.

All these utilities are grouped in the namespace classref:pcsc[].

[#wincom]
===== Windows specificities

The class classref:COM[] provides a portable and reliable way to make sure that the Common Object Model (COM)
is properly initialized and terminated on Windows systems.
This class is defined on all platforms but does nothing on non-Windows systems.
It is consequently safe to use it everywhere without tedious conditional compilation directives.

Other classes manipulate Windows-specific objects and are not available on non-Windows systems.

The template class classref:ComPtr[] is the equivalent of a smart pointer for COM objects.
The reference count of a COM object is properly incremented and decremented when
the COM object is manipulated through a classref:ComPtr[].
The COM object is automatically released when no more reference exists.

There is little advantage to develop an intrinsicly non-portable COM object class.
However, in order to access tuner devices, TSDuck needed a few custom internal COM classes
to interact with the DirectShow framework.
These internal classes needed some COM support functions which are available to applications (just in case...)

[#mpegfeatures]
==== MPEG features

[#tsclasses]
===== Transport streams

The class classref:TSPacket[] defines a transport stream packet.
It is in fact a flat structure which occupies exactly 188 bytes in memory.
It is safe to use arrays or vectors of classref:TSPacket[].
The packets are guaranteed to be contiguous in memory.

The class classref:TSPacket[] also adds many operations on the TS packet
to read or modify properties like the PID (type `ts::PID`),
the continuity counters or deeper structures like PCR, DTS or PTS.

The class classref:TransportStreamId[] contains the identification of an MPEG/DVB transport stream.

The class classref:Service[] contains all possible properties of a DVB service.
Not all properties need to be set at the same time.
Each property can be individually set, cleared or queried.

Transport stream files are implemented by classes classref:TSFileInput[] and classref:TSFileOutput[].
They respectively read and write transport stream files
with specific features such as repeating the reading of a part of the file.

The subclass classref:TSFileInputBuffered[] provides additional, but limited,
capabilities to seek forward and backward on non-seekable files such as pipes.

The subclass classref:TSFileOutputResync[] adds resynchronization capabilities on continuity counters and PID's.

The class classref:TSAnalyzer[] consumes all TS packets from a transport stream
and analyzes virtually everything from the stream.
This is the class which is used by the command `tsanalyze` and the plugin `analyze`
to collect the vast amount of information it reports.

The class classref:PCRAnalyzer[] is a useful tool to evaluate the bitrate of a transport stream.
It performs the analysis of the Program Clock Reference (PCR) which
are present in the transport stream in order to evaluate the bitrate of the stream.
If PCR are not found, the class can also use Decoding Time Stamps (DTS) to evaluate the bitrate.
This is less precise than PCR but can be used as a backup.

[#audiovideopes]
===== Audio, video and PES packets

The TSDuck library provides classes to manipulate PES packets and a few audio and video attributes.
These features are limited to the analysis of a transport stream.
There is no video or audio decoding features.
Specialized libraries exist for this and are out of scope for TSDuck.

The class classref:PESPacket[] implements a PES packet and can manipulate its attributes, header and payload.

The class classref:PESDemux[] extracts PES packets from a transport stream.
It can also notify the application of the changes in audio or video attributes.

The abstract class classref:AbstractAudioVideoAttributes[] is the root of a hierarchy of classes
which contains attributes for audio or video streams.
Currently, specialized classes exist for MPEG-2 video, AVC/H.264, HEVC/H.265, VVC/H.266 video,
MPEG-2 audio and AC-3 audio.

The class classref:AVCParser[] performs the parsing of an AVC, HEVC, or VVC bitstream.

[#siclasses]
==== Signalization

The MPEG signalization is built from sections, tables and descriptors.
All these concepts are implemented in the TSDuck library.

[#sigformats]
===== Binary, specialized and XML formats

Signalization objects, sections, tables and descriptors, can be manipulated in several formats:
binary objects, specialized classes and XML.

Tables in JSON format are also supported through automatic XML-to-JSON translation.

The classes classref:Section[], classref:BinaryTable[] and classref:Descriptor[]
implement binary forms of the signalization objects.

A binary table are made of a collection of sections.
A binary table is valid when all binary sections are present.
Each section contains its section number in the table and the total expected number of sections inside the table.

All sections and descriptors can be represented by the classes classref:Section[] and classref:Descriptor[].
They simply contain the complete binary content of the object and can manipulate the various components.
An instance of classref:Section[] stores the _table_id_ and manipulates the various components of the section header.
For long sections, the final CRC32 can be checked for consistency or recomputed after modification of the section content.

Tables can be stored in binary files.
The format of these files is quite simple.
They just contain raw binary sections, without any encapsulation.
Tables can also be stored in XML or JSON files.
The class classref:SectionFile[] reads and writes tables or section from files,
independently of the format, either a binary section file or an XML file.

Tables and descriptors can also be manipulated using specialized classes such as classref:PAT[] or classref:PMT[]
for tables and classref:ContentDescriptor[] or classref:ShortEventDescriptor[] for descriptors.

All specialized classes inherit from a common abstract root named classref:AbstractSignalization[].
All descriptors inherit from the intemediate class classref:AbstractDescriptor[].
All tables inherit from the intemediate class classref:AbstractTable[].
Tables with long sections inherit from classref:AbstractLongTable[].

Most tables and descriptors are implemented, from MPEG, DVB, ATSC, ISDB and a few private descriptors.
Unimplemented descriptors shall be manipulated in binary form (or be implemented...)

Binary tables or descriptors are converted from or to specialized classes using `serialize()` and `deserialize()` methods.
The validity of a binary or specialized object can be checked using the `isValid()` method.

Sample deserialization code:

[source,c++]
----
void someFunction(ts::DuckContext& duck, const ts::BinaryTable& table)
{
    ts::PMT pmt;
    if (table.isValid() && table.tableId() == ts::TID_PMT) {
        pmt.deserialize(duck, table);
        if (pmt.isValid()) {
            processPMT(pmt);
        }
    }
}
----

The deserialization can also be done in the constructor.
And the validity and _table_id_ checking is done anyway in the deserialization.
So, the previous code can be simplified as:

[source,c++]
----
void someFunction(ts::DuckContext& duck, const ts::BinaryTable& table)
{
    ts::PMT pmt(duck, table);
    if (pmt.isValid()) {
        processPMT(pmt);
    }
}
----

Sample serialization:

[source,c++]
----
ts::DuckContext duck;

ts::PMT pmt;
pmt.version = 12;
pmt.service_id = 0x1234;
// Declare one component, PID 0x345, carrying H.264/AVC video.
pmt.streams[0x345].stream_type = ts::ST_AVC_AUDIO;

ts::BinaryTable table;
pmt.serialize(duck, table);
----

Note that an instance of the class classref:DuckContext[] can store various information
about the way to interpret incorrect signalization or preferences.
Its default value is appropriate for a standard PSI/SI processing.

Each time the instance of classref:DuckContext[] is used, it accumulates information.
For instance, if it is used to deserialize an ATSC MGT table,
the information that the TS is an ATSC one is retained.
Later, if the same instance of classref:DuckContext[] is used to deserialize a descriptor
for which there is an ambiguity (the tag is used in two standards for instance),
the ATSC version of the descriptor will be used.

It is also possible to automatically define and load command line options to preset
the state of the instance of classref:DuckContext[].
See xref:duckcontext[xrefstyle=short] for more details.

Finally, specialized classes for tables and descriptors can be converted
to and from XML using the methods `toXML()` and `fromXML()`.

These methods are typically used by the class classref:SectionFile[] which represents
a file containing sections and tables in binary or XML format.
The class can be used to load a set of tables in XML format or to store table objects in XML format.

The class classref:SectionFile[] is the core of the `tstabcomp` utility, the tables compiler (or decompiler).

[#demux]
===== Demux and packetization

Signalization objects can be extracted from transport streams using the class classref:SectionDemux[]
and inserted back into transport streams using the class classref:Packetizer[].
These two classes also have specialized subclasses.

An instance of classref:SectionDemux[] can extract sections or complete tables in binary form.

Tables with long sections are usually cycled.
A given table with a given version number and a given _table id extension_ is reported only once,
after collecting all its sections.
The same table will be reported again only when its version number changes.

On the contrary, short tables are all reported since they do not implement versioning.

It is also possible to use a classref:SectionDemux[] to be notified of all individual sections.

[#duckcontext]
===== Application preferences contexts

The class classref:DuckContext[] carries various preferences about the standards or localizations.
Typically, each application has a given context.
Using `tsp`, each plugin has it own context.

The preferences which are carried by a context include the default standard
(DVB, ATSC, ISDB), the default character sets in PSI/SI, the default private
data specifier (for DVB private descriptors), the HF region (for terrestrial
or satellite frequency mapping)

The classref:DuckContext[] class can automatically define command-line arguments
to explicitly specify preferences (options `--atsc` or `--default-charset` for instance).
Thus, the preferences are setup from the beginning.

But preferences are also accumulated all along the execution.
For instance, as soon as an ATSC table is demuxed,
the fact that the transport stream contains ATSC data is stored in the context.
Later, when an MPEG table (a PMT for instance) contains an ambiguous descriptor tag which is used by DVB and ATSC,
then the ATSC alternative will be used.

[#dvbprotocols]
==== DVB SimulCrypt protocols

The communications inside a DVB SimulCrypt head-end is defined by
the standard ETSI TS 103 197, "Head-end implementation of DVB SimulCrypt".

Most of these protocols use the same principles.
They use binary TLV (Tag/Length/Value) messages, asynchronous communications,
concepts of _channels_, _streams_, status and error messages.

The generic handling of these messages is implemented by classes in the namespace `ts::tlv`.
All TLV messages inherit from classref:tlv/Message[].
Channel-level messages inherit from classref:tlv/ChannelMessage[] and
stream-level messages inherit from classref:tlv/StreamMessage[].

The syntax of a given protocol is defined by subclassing classref:tlv/Protocol[].

Currently, the TSDuck library implements the following protocols:

[.compact-list]
* ECMG{d-arrow}SCS in namespace `ts::ecmgscs`.
* EMMG/PDG{d-arrow}MUX in namespace `ts::emmgmux`.

[#cassupport]
==== Conditional access systems

The class classref:CASMapper[] analyzes the signalization of a transport stream,
locates ECM and EMM stream and associates each of them with a _CA_System_Id_.

An instance of classref:CASMapper[] can then be queried for ECM, EMM streams or CAS vendors.

[#otherdemux]
==== Other forms of demux

We have already mentioned the classes classref:SectionDemux[] and classref:PESDemux[].
Other specialized forms of demux can be implemented.

The class classref:T2MIDemux[] demuxes T2-MI (DVB-T2 Modulator Interface) packets
and extracts encapsulated transport streams.
Similarly, the class classref:TeletextDemux[] extracts Teletext subtitles from TS packets.

Since all forms of demux share a number of properties, they all inherit from
a root abstract class named classref:AbstractDemux[].

[#dvbtuners]
==== Digital TV tuners

The class classref:Tuner[] interfaces DVB/ATSC/ISDB tuner devices in a portable way.
This is quite a challenge since Linux and Windows use very different tuner frameworks.
Some very-specific features are available either only on Linux or Windows.

The abstract class classref:TunerParameters[] is the root of a hierarchy of classes containing tuning parameters.
Subclasses exist for DVB-S, DVB-T, DVB-C and ATSC.
ISDB-S and ISDB-T are currently unsupported.

The class classref:TSScanner[] reads a TS from a classref:Tuner[] until all scanning information is found,
typically until the PAT, NIT and SDT are received.
This is the basis for scanning a DTV network.

Note that tuner devices are supported on Linux and Windows only.
On macOS, the above classes are defined but return "unimplemented" errors when used.

[#dektecops]
==== Interface to Dektec devices

TSDuck can manipulate ASI and (de)modulator devices from Dektec.
The TSDuck library includes the DTAPI library, a proprietary {cpp} interface which is provided by Dektec.
The DTAPI is not available in source form and not part of the TSDuck source repository.
However, when TSDuck is built, the DTAPI is downloaded in binary from Dektec and included in the TSDuck library.

Such a packaging is authorized by the DTAPI license
(see the file `OTHERS.txt` in the TSDuck source repository or installation tree).

An application should not directly call the DTAPI.
In practice, this works on Linux but not on Windows.
So if you want portability, do not do this.
The reason is that the structure of Windows DLL's is such that exported code
from a DLL must be compiled using specific attributes.
But the DTAPI, as provided by Dektec, was not compiled with these attributes.
So, when the DTAPI is included in `tsduck.dll`, the DTAPI can be called from
inside `tsduck.dll` but is not accessible from the application.

This is why accessing the DTAPI from the application must be done through some TSDuck proxy class.
The classes classref:DektecControl[], classref:DektecInputPlugin[] and classref:DektecOutputPlugin[]
provide the features which are required by the utility `tsdektec` and the plugin `dektec`.
They can be used by third-party applications.

Note that Dektec devices are supported on Linux and Windows only.
On macOS, the above classes are defined but return "unimplemented" errors when used.
