//----------------------------------------------------------------------------
//
// TSDuck - The MPEG Transport Stream Toolkit
// Copyright (c) 2005-2026, Thierry Lelegard
// BSD-2-Clause license, see LICENSE.txt file or https://tsduck.io/license
//
//----------------------------------------------------------------------------

[#chap-application]
== Developing Applications with TSDuck

The TSDuck library is made of a large number of general-purpose {cpp} classes for Digital TV.
They can be used by any application to manipulate MPEG transport streams, the signalization,
and various data which are carried in MPEG-TS.

A subset of high-level features is also accessible from Java and Python applications.

This chapter describes how to use the TSDuck library in third-party applications.

It also describes how to develop TSDuck plugins and TSDuck extensions outside the TSDuck project.
Although we encourage open source contributions to enrich the project,
it can be useful to extend TSDuck in private applications to test proprietary features.

include::102-01-libraries.adoc[]
include::102-02-building.adoc[]
include::102-03-overview.adoc[]
include::102-04-reactor.adoc[]
include::102-05-jp-bindings.adoc[]
include::102-06-dev-plugin.adoc[]
include::102-07-dev-extension.adoc[]
