//----------------------------------------------------------------------------
//
// TSDuck - The MPEG Transport Stream Toolkit
// Copyright (c) 2005-2026, Thierry Lelegard
// BSD-2-Clause license, see LICENSE.txt file or https://tsduck.io/license
//
//----------------------------------------------------------------------------

[#automation]
=== Automation

TSDuck is a free open-source project which is maintained on spare time by very few developers
(only one at the time of this writing).
As a consequence, the maintenance of the project is driven by the lack of time and resource.
To face these constraints, automation is essential.

This is briefly explained in {home}docs/tsduck-project.pdf[this presentation].

For future maintainers or contributors, this section lists a few automation procedures which are used by the project.

[#auto_workflows]
==== GitHub workflows

Automation is provided through _GitHub Actions_, the CI/CD infrastructure which is hosted at GitHub.
This CI/CD infrastructure is provided for free by GitHub for open-source projects.
See <<GITHUB-CI>> for the complete documentation of GitHub Actions.

A project which is hosted at GitHub can define its own _workflows_.
A workflow is defined in a YAML file in the predefined subdirectory `.github/workflows`.

A workflow defines the conditions under which it is run:

[.compact-list]
* Automatically on events such as "push" or "pull requests".
* Automatically at scheduled times, for instance every day or every week.
* Manually from the GitHub web site.

TSDuck contains several GitHub workflows for automation.
The most significant ones are described in the following sections.

Most TSDuck workflows can be manually run in addition to some automatic condition.
To manually run a workflow, log in to GitHub, go to the project page, select the "Actions" tab,
click on the workflow name in the left pane.
Then, click on the "Run workflow" button on the right side.
If the workflow defines input parameters, a pane is opened with the possible options.
This feature is specifically useful with the "Release" workflow (see xref:auto_release[xrefstyle=short]).

[#auto_ci]
==== Continuous integration

Each time a commit or a pull request is pushed to GitHub, the workflow `continuous-integration.yml`
is automatically run to verify that the project can be built on most supported platforms and contains no regression.

* The workflow is run on Linux Ubuntu, macOS, and Windows (64 and 32 bits).
* The compilation is done using one or more revisions of the {cpp} language.
* On Linux, the builds are repeated using two compilers, `gcc` and `clang`.
* In each configuration of platform, compiler and language level:
** TSDuck is fully built.
** The unitary tests are run.
** The full test-suite is downloaded and run.
** The sample programs are built using a typical TSDuck installation of the binaries which were just built (Linux and macOS only).
* The documentation is rebuilt: user guide, developer guide, programming reference using doxygen.
  Missing documentation for new features can be found in the log. This is done on Ubuntu only.

Note that this workflow is quite stringent.
It fails on any compilation warning on any operating system or compiler.
It fails on the slightlest test failure in any configuration.
It fails if any documenation is missing in the code, such as an undocumented parameter in a function.

[#auto_nightly]
==== Nightly builds

Every night, if there were any modification in the TSDuck repo during the last day,
"nightly builds" are automatically produced and published on the {home}prerelease/[TSDuck web site].
No manual action is required, everything is automated.

The workflow `nightly-build.yml` is automatically run every day at 00:40 UTC.

* On Linux Ubuntu and Windows (64 bits only), the TSDuck binary packages are built
  for the current state of the master branch in the repository.
* The produced binaries are installed on the CI/CD system.
* The full test-suite is downloaded and run.
* The complete set of documentation (user guide, developer guide, programming reference)
  is built and packaged in an archive.
* The Linux Ubuntu binaries, the Windows binaries and the documentation package are
  published as "artefacts" of the workflow. They are publicly downloadable from
  {repo}actions/[GitHub].

At the end of the workflow `nightly-build.yml`, when all build jobs are completed,
the update job triggers a signal on the {home}[TSDuck web site].
A PHP script is automatically run on the web site to retrieve, download and publish the
latest {home}prerelease/[nighly binaries] and documentation.

[#auto_issues]
==== Cleanup of long-standing issues

The {repo}issues[issues area on GitHub] is used to report problems,
ask questions, and support any discussion about TSDuck.
When an issue is obviously completed, because a complete answer was provided or a fixed is pushed, the issue is closed.
Sometimes, a plausible response or fix is provided but some feedback is expected from the user to confirm this.
When a positive feedback is provided, the issue is closed.

However, some users never provide a feedback after their problem is solved.
In that case, the issue remains open forever.

To solve this, there is a label named "close pending".
When a plausible response, solution or fix is provided,
the maintainer of the project sets the "close pending" label on the issue.
It remains open.
However, if the issue is not updated in the next 150 days, it will be automatically closed.

This is achieved by the workflow `cleanup-issues.yml`.
This workflow is scheduled every week on Sunday at 02:00 UTC.
It runs the Python script `pkg/github/close-pending.py`
which automatically closes all issues with label "close pending" and no update within the last 150 days.
