#-----------------------------------------------------------------------------
#
#  TSDuck - The MPEG Transport Stream Toolkit
#  Copyright (c) 2005-2025, Thierry Lelegard
#  BSD-2-Clause license, see LICENSE.txt file or https://tsduck.io/license
#
#  GitHub Actions configuration file : Release subworkflow for Linux.
#  Build, install and test TSDuck in a Linux container (any distro).
#  Upload installation packages as workflow artifacts.
#  Do not start this workflow manually, this is a subworkflow of release.yml.
#
#-----------------------------------------------------------------------------

name: Release (Linux)

on:
  workflow_call:
    inputs:
      build:
        description: 'If false, do not build anything, skip that subworkflow'
        type: boolean
        required: false
        default: false
      tag:
        description: 'Tag to rebuild, empty to build latest commit'
        type: string
        required: false
        default: ''
      arch:
        description: 'One of x64, arm64'
        type: string
        required: true
      distro:
        description: 'One of ubuntu, debian, fedora, redhat'
        type: string
        required: true
      runner:
        description: 'GitHub runner, typically ubuntu on x64 or arm64'
        type: string
        required: true
      image:
        description: 'Container image to run'
        type: string
        required: true
      setup_command:
        description: 'Optional initial shell command to run, before getting the repo'
        type: string
        required: false
        default: ''
      package_options:
        description: 'Options to pass to package install command (apt or dnf)'
        type: string
        required: false
        default: ''
      command_list_artifact:
        description: 'If true, generate an artifact with command lists'
        type: boolean
        required: false
        default: false
      retention_days:
        description: 'Artifacts retention days'
        type: number
        required: false
        default: ${{ fromJSON(vars.ARTIFACT_RETENTION_DAYS || 5) }}

jobs:
  build:
    name: Build in container
    if: inputs.build
    runs-on: ${{ inputs.runner }}
    container: ${{ inputs.image }}
    defaults:
      run:
        # Currently, GitHub containers use "sh" as default shell.
        shell: bash
    steps:

    - name: Container setup
      if: inputs.setup_command != ''
      run: ${{ inputs.setup_command }}

    - name: Get TSDuck repo
      uses: actions/checkout@master
      with:
        # Checkout tag. If empty, use the default branch.
        ref: ${{ inputs.tag }}

    - name: Install prerequisites
      run: |
        scripts/install-prerequisites.sh ${{ inputs.package_options }}

    - name: Check compiler version
      run: |
        # Red Hat 9 has obsolete gcc 11. Enable at least gcc 13.
        ENABLE_SCRIPT=
        if [[ ${{ inputs.distro }} == redhat ]]; then
            GCC_MAJOR=$(gcc --version | sed -e '2,$d' -e 's/([^(]*)//g' -e 's/^[^0-9]*//' -e 's/[^0-9].*$//')
            if [[ -n $GCC_MAJOR && $GCC_MAJOR -lt 13 ]]; then
                ENABLE_SCRIPT=$(ls /opt/rh/gcc-*/enable 2>/dev/null | sort -d | grep -e -13/ -e -14/ -e -15/ | tail -1)
            fi
        fi
        if [[ -n $ENABLE_SCRIPT ]]; then
            echo "Using $ENABLE_SCRIPT"
            source "$ENABLE_SCRIPT"
            gcc --version
        fi
        echo "ENABLE_SCRIPT=$ENABLE_SCRIPT" >>$GITHUB_ENV

    - name: Build
      run: |
        [[ -n $ENABLE_SCRIPT ]] && source "$ENABLE_SCRIPT" || true
        make installer

    - name: List installers
      run: |
        # In ordered list in pkg/installers, the tools package comes first, then the dev package.
        ls -l pkg/installers
        PACKS=($(ls pkg/installers | sort -d | grep -v '\.src\.rpm' | grep -e '\.deb$' -e '\.rpm$'))
        echo ""
        echo "Tools package: ${PACKS[0]}"
        echo "Dev package: ${PACKS[1]}"
        echo "TSTOOLS=${PACKS[0]}" >>$GITHUB_ENV
        echo "TSDEV=${PACKS[1]}" >>$GITHUB_ENV

    - name: Install installers
      run: |
        [[ -n $ENABLE_SCRIPT ]] && source "$ENABLE_SCRIPT" || true
        make install-installer

    - name: Identify installed version
      run: |
        echo "==== TSDuck version"
        tsversion --version=all
        echo "==== TSDuck supported features"
        tsversion --support all
        echo "==== TSDuck plugins"
        tsp --list-plugins

    - name: Generate command lists
      if: inputs.command_list_artifact
      run: |
        tsp --version=short &>tsp.version.txt
        tsp --list=input &>tsp.input.txt
        tsp --list=output &>tsp.output.txt
        tsp --list=packet &>tsp.packet.txt
        for file in src/tstools/*.cpp; do
            name=$(basename $file .cpp)
            if [[ -n $(which $name) ]]; then
                echo -n $name:
                $name --help=description 2>&1
            fi
        done >tsduck.commands.txt
        zip -q9 tsduck.commands.zip tsp.version.txt tsp.input.txt tsp.output.txt tsp.packet.txt tsduck.commands.txt

    - name: Download test suite
      if: github.repository == 'tsduck/tsduck'
      run: |
        curl -fsL "https://github.com/${{ github.repository }}-test/tarball/master" -o test.tgz
        mkdir -p ../tsduck-test
        tar -C ../tsduck-test -x -z -f test.tgz --strip 1

    - name: Run test suite on installed version
      if: github.repository == 'tsduck/tsduck'
      run: |
        cd ../tsduck-test
        ./run-all-tests.sh && status=$? || status=$?
        for f in $(find tmp -name '*.diff'); do
            echo "==== $f";
            cat "$f"
        done
        exit $status

    - name: Build sample applications
      if: github.repository == 'tsduck/tsduck'
      run: |
        [[ -n $ENABLE_SCRIPT ]] && source "$ENABLE_SCRIPT" || true
        make -C sample

    - name: Publish tools package
      uses: actions/upload-artifact@v4
      with:
        name: tsduck-${{ inputs.distro }}-${{ inputs.arch }}
        path: pkg/installers/${{ env.TSTOOLS }}
        retention-days: ${{ inputs.retention_days }}

    - name: Publish dev package
      uses: actions/upload-artifact@v4
      with:
        name: tsduck-dev-${{ inputs.distro }}-${{ inputs.arch }}
        path: pkg/installers/${{ env.TSDEV }}
        retention-days: ${{ inputs.retention_days }}

    - name: Publish command lists
      if: inputs.command_list_artifact
      uses: actions/upload-artifact@v4
      with:
        name: command-lists
        path: tsduck.commands.zip
        retention-days: ${{ inputs.retention_days }}
